### PR TITLE
Fixes property links don't work in de formal language (updated)

### PR DESCRIPTION
**Pull request by thomas-topway-it**
(Follow-up of previous pull request)

updates of the following:  https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5493

fixes: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5342

### CODE REVIEW

**Comment by thomas-topway-it** [comment]
@JeroenDeDauw  hello Jeroen, there are some test failing but I don't think they are related to the current pull request (they seem rather to be caused by some change in the test environment), comparing to the previous pull request (https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5493 ) I've cleaned a bit the code and rebased the branch

**Comment by JeroenDeDauw** [comment]
You didn't add any tests for the new behavior and no one has verified this PR via manual testing, so I am hesitant to merge the PR.

**Comment by thomas-topway-it** [comment]
added a test for each edited class. The tests seem to work as expected, they test de-formal language instead than EN (that does not require any mapping). The tests fail with the original classes and succeed with the updated classes.

**Comment by thomas-topway-it** [comment]
@JeroenDeDauw can this be finally merged ?

**Pull request merged**
