### PR TITLE
Add TableSchemaManager/FieldType, refs 1940

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1940

This PR addresses or contains:

- Field type hinting declared by something like `$type == 'p'` is missing expressiveness as to what a field (and its type) is to represent.
- `FieldType` will replace something like `array( 'o_blob' => 'l', 'o_hash' => 't' );` with
`array( 'o_blob' => FieldType::TYPE_BLOB, 'o_hash' => FieldType::FIELD_TITLE );`

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
Before 2.5 you would do:

```
		// Set up table for internal IDs used in this store:
		SMWSQLHelpers::setupTable(
			SMWSQLStore3::ID_TABLE,
			array(
				'smw_id' => $idType,
				'smw_namespace' => $dbtypes['n'] . ' NOT NULL',
				'smw_title' => $dbtypes['t'] . ' NOT NULL',
				'smw_iw' => $dbtypes['w'] . ' NOT NULL',
				'smw_subobject' => $dbtypes['t'] . ' NOT NULL',
				'smw_sortkey' => $dbtypes['t']  . ' NOT NULL',
				'smw_proptable_hash' => $dbtypes['l']
			),
			$db,
			$reportTo
		);
		SMWSQLHelpers::setupIndex(
			SMWSQLStore3::ID_TABLE,
			array(
				'smw_id',
				'smw_id,smw_sortkey',
				'smw_iw', // iw match lookup
				'smw_title,smw_namespace,smw_iw,smw_subobject', // id lookup
				'smw_sortkey' // select by sortkey (range queries)
			),
			$db
		);
```

With 2.5 you do:

```
		$table = new Table( SQLStore::ID_TABLE );

		$table->addColumn( 'smw_id', FieldType::FIELD_ID_PRIMARY );
		$table->addColumn( 'smw_namespace', array( FieldType::FIELD_NAMESPACE, 'NOT NULL' ) );
		$table->addColumn( 'smw_title', array( FieldType::FIELD_TITLE, 'NOT NULL' ) );
		$table->addColumn( 'smw_iw', array( FieldType::FIELD_INTERWIKI, 'NOT NULL' ) );
		$table->addColumn( 'smw_subobject', array( FieldType::FIELD_TITLE, 'NOT NULL' ) );
		$table->addColumn( 'smw_sortkey', array( FieldType::FIELD_TITLE, 'NOT NULL' ) );
		$table->addColumn( 'smw_proptable_hash', FieldType::TYPE_BLOB );

		$table->addIndex( 'smw_id' );
		$table->addIndex( 'smw_id,smw_sortkey' );
		$table->addIndex( 'smw_iw' ); // iw match lookup
		$table->addIndex( 'smw_title,smw_namespace,smw_iw,smw_subobject' ); // id lookup
		$table->addIndex( 'smw_sortkey' ); // select by sortkey (range queries)
```

For example, `FieldType::FIELD_ID_PRIMARY` is matched to a DB back-end specific field definition without requiring the table schema to know about it which comes in handy when definition do vary as in case of #1912.

**Comment by mwjames** [comment]
@kghbln Happy testing on the sandbox when running `setupStore.php`/`update.php`!

**Comment by kghbln** [comment]
@mwjames Just did some testing on sandbox (MariaDB) and I have to repeat myself :)

1. running "setupStore.php" on existing tables / no issues
2. running "setupStore.php --delete" to drop existing tables / no issues
3. running "setupStore.php" to create the tables / no issues

so :+1: from me for now!

**Comment by kghbln** [comment]
Ah, in contrast to yesterday the "rebuildData.php" script exited with "Speicherzugriffsfehler" (error while accessing the memory). Since I am using Memcached I suspect https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1931.

```
(1400/1608)     Finished processing ID 1401 (Malignant_melanoma#0#_QUERY324918fb1b3de81fa39f060533c94120)
Speicherzugriffsfehler
```

**Comment by mwjames** [comment]
> Since I am using Memcached I suspect #1931.

This is strange, one thing that changed was the `LinksInValue` setting.

**Comment by mwjames** [comment]
> Speicherzugriffsfehler

This smells like a PHP rather then a MW issue.

**Comment by mwjames** [comment]
Does the PHP log reveal something (https://duckduckgo.com/html?t=disconnect&q=Speicherzugriffsfehler)?

**Comment by mwjames** [comment]
Another thing that comes to mind is that #1959 uses an iterator, so maybe trying (via git) before and after [0] to see if the issue is deterministic.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/dcc1028e51edc4840a123537a6650f4ab62253bc

**Comment by kghbln** [comment]
> This is strange, one thing that changed was the LinksInValue setting.

Indeed. Since neither "--ignore-exceptions" nor setting the cache setting to "CACHE_NONE" did help It seems unrelated in the end. Next round will be to disable "LinksInValue".

> This smells like a PHP rather then a MW issue.

SMW log returns for the exit spot

```
2016-10-26 17:04:29 phalaris 0210020150926-02100_: Clear CachedPropertyValuesPrefetcher for Emilzola#3#
2016-10-26 17:04:29 phalaris 0210020150926-02100_: SMW\ParserData::updateStore doUpdate
2016-10-26 17:04:29 phalaris 0210020150926-02100_: Clear CachedPropertyValuesPrefetcher for Emilzola#2#
2016-10-26 17:04:29 phalaris 0210020150926-02100_: SMW\ParserData::updateStore doUpdate
2016-10-26 17:04:29 phalaris 0210020150926-02100_: SMW\Notifications\ChangeNotification\ChangeNotificationFilter::hasChangeToNotifyAbout Emilzola#2# in procTime (sec): 3.19E-5
2016-10-26 17:04:29 phalaris 0210020150926-02100_: EchoEvent was not triggered
2016-10-26 17:04:29 phalaris 0210020150926-02100_: SMW\SQLStore\QueryDependency\QueryDependencyLinksStore::pruneOutdatedTargetLinks finished on Emilzola#2# with procTime (sec): 2.22E-5
2016-10-26 17:04:29 phalaris 0210020150926-02100_: SMW\SQLStore\QueryDependency\EntityIdListRelevanceDetectionFilter::getFilteredIdList procTime (sec): 2.1E-5
2016-10-26 17:04:29 phalaris 0210020150926-02100_: SMW\SQLStore\QueryEngine\Fulltext\TextByChangeUpdater::pushUpdatesFromPropertyTableDiff procTime (sec): 1.0E-5
2016-10-26 17:04:29 phalaris 0210020150926-02100_: Event on.after.semanticdata.update.complete doPurgeParserCache for Emilzola#2# (as DeferredCallableUpdate)
2016-10-26 17:04:29 phalaris 0210020150926-02100_: Event on.after.semanticdata.update.complete doPurgeParserCache for Emilzola#2# doUpdate
```
The exceptions log spams me with:
```
MWException from line 883 of /.../w/extensions/Echo/includes/formatters/BasicFormatter.php: Unrecognised parameter item
```

**Comment by kghbln** [comment]
Well disabling `LinksInValues` fixes the issue. A bit unexpected but a result to be considered for https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1963

**Comment by kghbln** [comment]
Back to this pull: :+1: :)

**Pull request merged**
