### PR TITLE
Make SemanticMediaWiki compatible with new ElasticSearch

### PR DESCRIPTION
**Pull request by marijnvanwezel**
This pull request makes Semantic MediaWiki compatible with new ElasticSearch (8.x tested). It is currently still a draft, since I have not yet updated the tests. It is working in my personal testing environment.

There are a number of major changes in the ElasticSearch API, as well as some breaking changes in the ElasticSearch PHP package, that this pull request addresses. Most notably:

* Mapping types have been removed (https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html);
* Elasticsearch PHP methods now return `Promise` objects, which need to be explicitly converted to a type;
* The `cat` API no longer returns a JSON by default;
* The associative array syntax for hosts is no longer supported (https://github.com/elastic/elasticsearch-php/issues/1214). This required the addition of a configuration variable, `$wgElasticsearchCredentials`;
* `doc_values` is no longer supported on properties of type `text`.

### CODE REVIEW

**Comment by marijnvanwezel** [comment]
I apologise for the somewhat messy commit history. If/when this is merged, a squash commit might be appropriate.

**Comment by jaideraf** [comment]
I would suggest you to "**Make SemanticMediaWiki compatible with ElasticSearch 7.10.x**" wich is probably the last version of _ElasticSearch_ Wikimedia will support[0]. After that, a migration to _OpenSearch_[1] will follow because of license issues[2].

[0] https://www.mediawiki.org/wiki/Extension:CirrusSearch
[1] https://phabricator.wikimedia.org/T325028
[2] https://en.wikipedia.org/wiki/OpenSearch_(software)#OpenSearch

**Comment by marijnvanwezel** [comment]
I have not tested it, but I think this PR is also compatible with ElasticSearch 7.x, or requires minimal changes to make it compatible.

**Comment by marijnvanwezel** [comment]
I will try to see if I can get a test wiki running with ElasticSearch 7.10.2 and this PR somewhere in the coming week (probably Friday).

**Comment by malberts** [comment]
Thanks for starting with this! Another compatibility question is whether this will still work with ES 6.x, or if these changes can accommodate it. If not, then this will have to be part of SMW 5.x.

IMO if it's very difficult/time-consuming, then it is probably not worth it to complicate the code to support MW 1.35-era ElasticSearch 6.x. Perhaps SMW 5.x is a good time to raise SMW's minimum versions to MW 1.39 and ES 7.x.

**Comment by marijnvanwezel** [comment]
I have confirmed that file ingestion is now also working with this pull request.

Screenshot 2023-02-27 at 16 28 39

**Comment by MPThLee** [comment]
Just for a note. It won't be compatible with 6.x if update to 7.x Unless using compatibility layer (like [CirrusSearch did](https://www.mediawiki.org/wiki/Extension:CirrusSearch/ES6CompatTransportWrapper)) which is available on 6.8. Well, It technically 'works' but not recommended. 

There's a lot of changes compared to [`to 6.0`](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/breaking-changes-6.0.html) and [`to 7.0`](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/breaking-changes-7.0.html).

**Comment by krabina** [comment]
See https://phabricator.wikimedia.org/T280482 for reference

**Comment by marijnvanwezel** [comment]
Ad asked Cindy and she will ask the Wikimedia Foundation what their stance will be. For now, it is probably best to:

1. Make Semantic MediaWiki compatible with the latest open-source version of ElasticSearch (7.10.x);
1. Wait until Wikimedia updates the minimum requirements of CirrusSearch;
1. Make Semantic MediaWiki compatible with the versions of ElasticSearch or OpenSearch (depending on the outcome of point 2) that are supported by CirrusSearch;
1. Try to keep Semantic MediaWiki and CirrusSearch compatible.

@krabina @jaideraf What do you think?

I didn't have time to test this patch on 7.10 unfortunately, but hopefully I will have time for it next week.

**Comment by krabina** [comment]
I totally agree!

**Comment by jaideraf** [comment]
I totally agree, too!

**Comment by marijnvanwezel** [comment]
@JeroenDeDauw I am also wondering what you think. In particular, see [this comment by jaideraf](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5451#issuecomment-1446382069) and [this comment by me](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5451#issuecomment-1454050701). Thank you in advance for taking the time to look at this!

**Comment by JeroenDeDauw** [comment]
What you wrote sounds reasonable to me

**Comment by cicalese** [comment]
I was able to test this patch successfully with the following versions:

MediaWiki: 1.39.1
PHP: 7.4.33
Elasticsearch: 7.10.2

**Comment by krabina** [comment]
Great, thank you for testing! Is this now ready for integration, @JeroenDeDauw, @gesinn-it-gea ?

**Comment by wgevaert** [comment]
Some time ago, we tested the branch from `marijnvanwezel/SemanticMediaWiki` and one of our testers did find some issues. We have then reverted to a version with ES 6.8, so we do not have full details of the issues.

issues:
1. Sort parameter does not seem to work. Tested the following wikicode: ```{{#ask:[[Modification date::+]]
|?Modification date
|sort=Modification date
}}```. Does not give results. Without sort it does give results
2. Running rebuildData gave "errors" and after that "nothing worked anymore" (no results from ask queries. (I do not have more info because we moved back to ES6.8 and testers did not make screenshots).

**Comment by krabina** [comment]
@cicalese and @marijnvanwezel  can you reproduce the sorting problem?
I guess problem 2 would have been noticed.

**Comment by marijnvanwezel** [comment]
I was unable to reproduce problem 2, but I was able to reproduce problem 1. ES reports the following syntax error in queries with sort:

```
org.elasticsearch.common.ParsingException: Failed to parse; org.elasticsearch.xcontent.XContentParseException: [1:112] [bool] failed to parse field [must]
```

I am looking into why this happens.

**Comment by marijnvanwezel** [comment]
Query without sort:

```
{
    "index": "smw-data-mediawiki",
    "body": {
        "_source": false,
        "from": 0,
        "size": 51,
        "query": {
            "constant_score": {
                "filter": {
                    "bool": {
                        "filter": {
                            "exists": {
                                "field": "P:29.datField"
                            }
                        }
                    }
                }
            }
        },
        "sort": [
            {
                "subject.sortkey.sort": {
                    "order": "asc"
                },
                "subject.title.sort": {
                    "order": "asc"
                }
            }
        ]
    }
}
```

Query with sort:

```
{
    "index": "smw-data-mediawiki",
    "body": {
        "_source": false,
        "from": 0,
        "size": 51,
        "query": {
            "constant_score": {
                "filter": {
                    "bool": {
                        "must": [
                            {
                                "bool": {
                                    "filter": {
                                        "exists": {
                                            "field": "P:29.datField"
                                        }
                                    }
                                }
                            },
                            [
                                {
                                    "exists": {
                                        "field": "P:29.datField"
                                    }
                                }
                            ]
                        ]
                    }
                }
            }
        },
        "sort": [
            {
                "P:29.datField": {
                    "order": "asc"
                }
            }
        ]
    }
}
```

**Comment by bertrandgorge** [comment]
I've added some documentation here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5614 (hope I got it right)

**Pull request merged**
