### PR TITLE
Move src directory to the top level

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
This includes moving some classes that did not have a namespace
matching their location. And updating the refs to those classes.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
The build that is failing does not indicate anything is wrong here. If I'm not mistaken, this build used to be in the "allowed failures" section for exactly this reason: it can fail if certain incompatibilities arise between the setup on master and the one submitted in the PR.

**Comment by mwjames** [comment]
Errors at the top with:

> \''MW_INSTALL_PATH=/home/travis/build/SemanticMediaWiki/mw'\'' );'
+php maintenance/update.php --quick
PHP Warning:  Class 'SMW\MediaWiki\Jobs\UpdateJob' not found in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/SemanticMediaWiki.php on line 60
PHP Stack trace:
PHP   1. {main}() /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php:0
PHP   2. require_once() /home/travis/build/SemanticMediaWiki/mw/maintenance/update.php:206

**Comment by JeroenDeDauw** [comment]
The problem lies here https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/build/travis/install-semantic-mediawiki.sh#L19-L47, not in this PR

**Comment by mwjames** [comment]
> The error occurs due to SMW being composer installed with SMW master, which does not have the psr4 section. So if you then update the code to that of the PR, ofc its not gonna work.

So having a PR that only changes the `composer.json` (with the psr-4 section) first merged before this one?

**Comment by JeroenDeDauw** [comment]
Yeah sure, that'd work. Though what is the point now? Just merge this and you have the same result for less work

**Comment by mwjames** [comment]
This PR caused a "Test Coverage has decreased to 63% (-8%)" [0]

[0] https://scrutinizer-ci.com/g/SemanticMediaWiki/SemanticMediaWiki/inspections/d7fa8f13-3723-4d34-b54d-c9be0e3581c6

**Comment by JeroenDeDauw** [comment]
huh... any idea why?

**Comment by mwjames** [comment]
> huh... any idea why?

Missing entries in `phpunit.xml.dist`.
```
    <filter>
        <whitelist addUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">src</directory>
            <directory suffix=".php">includes</directory>
            <directory suffix=".php">maintenance</directory>
        </whitelist>
    </filter>
```

**Pull request merged**
