### PR TITLE
Move away from deprecated Validator code

### LINKED ISSUE #384: The deprecated ParserHook class is still used
`InfoParserFunction` and `DocumentationParserFunction` still derive from the highly deprecated `ParserHook`. SMW is currently blocking removal of this class from Validator.

We can retain a similar declarative [ParamProcessor](https://github.com/JeroenDeDauw/ParamProcessor) based approach by using the [ParserHooks library](https://github.com/JeroenDeDauw/ParserHooks), which does not suffer from the same design issues.

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes #384

Might also take care of #880

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Oh smag you MediaWiki... really? >_>

**Comment by mwjames** [comment]
What about [0] ?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.php#L33-L40

**Comment by JeroenDeDauw** [comment]
That is still working because the latest release of ParserHooks uses Validator rather than ParamProcessor. Which will change. So we should drop that check. I'm wondering if it makes sense to add another one...

**Comment by JeroenDeDauw** [comment]
@mwjames revieeeeeeeeeeeeeeeeeeeeeew! ;p

**Comment by mwjames** [comment]
> revieeeeeeeeeeeeeeeeeeeeeew! ;p

Let me first add a small integration test that calls both parser function so we can ensure that before and after returns the same result.

**Comment by JeroenDeDauw** [comment]
I manually checked that the thing are still working. With this type of change, I'd expect any breakage to be non-subtle.

You are right that tests are rather absent here so far. It should be easier now to write one that gives the code a bunch of input parameters and then checks the output is as expected.

**Comment by JeroenDeDauw** [comment]
@mwjames I might be writing such tests later today but feel this got a bit cookie licked by you now, and want to avoid us doing the same task in parallel. So please clarify if you will do this today or not.

**Comment by mwjames** [comment]
> So please clarify if you will do this today or not.

I'l do the integration test, should be done with it in 10 min or so.

**Comment by mwjames** [comment]
Done with #1019 just having some trouble with #smwdoc to adhere the language specific test setting.

**Comment by mwjames** [comment]
Done with 51bd826

**Comment by JeroenDeDauw** [comment]
Great thanks. This test is now failing after I merged this PR. https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/62772387

Looks like this is caused by the code no longer accessing the global on every run since it's injected at configuration time now. I suspect this is not an issue for the production code and is just something occurring in the test environment. Any idea how to best deal with this?

**Comment by JeroenDeDauw** [comment]
Yeah, so the test is changing the global, which will of course not change the value the code under test has...

**Comment by mwjames** [comment]
> Yeah, so the test is changing the global, which will of course not change the value the code under test has...

Well, yes that's the point as it defines the boundaries the test is supposed to be run. We could kill all hooks before the test invocation and register them again on each run to ensure that all registered hooks do adhere the settings (as in a normal LocalSettings environment).

**Comment by JeroenDeDauw** [comment]
Should be fixed by 54a89b910e5b6a9ce46a5293bf15d68da8e11d6e

**Comment by JeroenDeDauw** [comment]
Well can just sidestep the language variant behaviour. If the thing checks some HTML is output, that is enough of a smoke test. More precise behaviour is better tested with a test that has better isolation.

**Pull request merged**
