### PR TITLE
Remove special page "SemanticStatistics", refs 2181

### LINKED ISSUE #2181: Remove special page "SemanticStatistics"
### Issue

The information provided on this page has step by step been added to extend special page "Statistics". Special page "Statistics" now even provides more information that special page "SemanticStatistics" ever has. Thus it should probably be removed.

@mwjames @JeroenDeDauw

### PR DESCRIPTION
**Pull request by TK-999**
This PR is made in reference to: #2181

This PR addresses or contains:
>The information provided on this page has step by step been added to extend special page "Statistics". Special page "Statistics" now even provides more information that special page "SemanticStatistics" ever has. Thus it should probably be removed.

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #2181

### CODE REVIEW

**Comment by kghbln** [comment]
Thanks for the pull! Just requested a review!

**Comment by JeroenDeDauw** [comment]
Huh, we have no tag for breaking changes (from user perspective)?

I suppose since we are working on 3.0, it is indeed the time to remove this page. +2 from my side

**Comment by mwjames** [comment]
@kghbln @Nikerabbit Before merging, I just want to make sure we don't get into any trouble where the `semanticstatistics`, `smw_semstats_text` key is deleted from other non-en i18n files.

**Comment by Nikerabbit** [comment]
@mwjames Deletion is okay.

**Comment by mwjames** [comment]
Thanks

**Pull request merged**
