### PR TITLE
Add RdbmsTableBuilder to replace SMWSQLHelpers

### PR DESCRIPTION
**Pull request by mwjames**
- RDBMS specific code has been moved into corresponding subclasses with `RdbmsTableBuilder` itself implementing the `TableBuilder` interface
- Add unit/integration tests to verify that tables/indicies are created as specified

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln I tried to be extra observant (and added an extra integration test) to avoid any breakage but this PR can potentially contain a regression during the table setup/update therefore I'm given a prior notice to watch out for issues in this regards. Since I need this for subsequent work I'm unable to wait for someone to test this within a timeframe of a week or longer.

**Comment by kghbln** [comment]
So what I need to do is getting the pr in on sandbox, run the database update and see if there are worries?!

**Comment by mwjames** [comment]
> So what I need to do is getting the pr in on sandbox, run the database update and see if there are worries?!

Since all tests passed, I don't expect any issues. It is just in case that something "funny" occurs during a table update in future then we might have to look at this PR.

**Comment by mwjames** [comment]
I'm just raising awareness that 2.5 contains such change.

**Comment by kghbln** [comment]
Just updated sandbox, ran "update.php" followed by "rebuildData.php" and I was not able to see irregularities nor did I get errors in the log. Seems cool.

**Pull request merged**
