### PR TITLE
Adjust the tests so that that they can run in a "normal" MediaWiki environment.

### PR DESCRIPTION
**Pull request by hexmode**
When I was working on an extension that depended on SMW, I had to modify the tests so that they would run in a more conventional MW test environment.  Otherwise, name resolution caused the tests to fail.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
This is great! Would merge if the CI passed but it seems like it is not evening running now. Probably unrelated to this PR.

**Comment by JeroenDeDauw** [comment]
If tests can now be run with standard approach, getting them to run on GitHub actions is hopefully also easier

**Comment by gesinn-it** [comment]
> 
> 
> This is great! Would merge if the CI passed but it seems like it is not evening running now. Probably unrelated to this PR.

travis.org → travis.com is probably the reason that the CI is not executed at the moment. It should not make much effort to switch to travis.com. I think I don't have sufficient rights / account to do this.

**Comment by gesinn-it** [comment]
grafik

**Comment by JeroenDeDauw** [comment]
I'll have a look. GH Actions would be nice tho

**Comment by gesinn-it** [comment]
@JeroenDeDauw GH actions is fine too in future. At the moment I'd prefer to stay with Travis and focus on getting SMW 4.0 out and come back to infrastructure topics later.

**Comment by JeroenDeDauw** [comment]
Think stuff is done now https://travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/builds

**Comment by JeroenDeDauw** [comment]
Not working for some reason

image

**Comment by hexmode** [comment]
I've been tweaking my PR to make it work with better and now I'm actually seeing the tests run for quite a while.

As a result, I'm seeing a number of "deprecated in MediaWiki 1.31" (1.35, too, but this is about 1.31).  I think the next release should only support 1.35+.

**Comment by JeroenDeDauw** [comment]
Yes, master can use 1.35, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Comment by JeroenDeDauw** [comment]
Tests should run now when rebasing or adding a commit

**Comment by JeroenDeDauw** [comment]
I'd like to get this merged but needs rebase

**Comment by JeroenDeDauw** [comment]
Looks like the conflict is with your own changes ;)

**Pull request closed without merging**
