### PR TITLE
Add support for travis ci containter

### PR DESCRIPTION
**Pull request by paladox**
This PR is made in reference to: #

This PR addresses or contains:
- ...
- ...
- ...

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

https://docs.travis-ci.com/user/migrating-from-legacy/

### CODE REVIEW

**Comment by mwjames** [comment]
Sorry, but you cannot  do this as other services like `SPARQL` triple stores rely on being installed using `sudo`.

**Comment by paladox** [comment]
Oh but what does it need sudo for?

We can install packages by doing

addons:
  apt:
    packages:

**Comment by paladox** [comment]
Or we can use the trusty beta with sudo?, but container is faster.

**Comment by mwjames** [comment]
> Oh but what does it need sudo for?

You may look at [0].

> Or we can use the trusty beta with sudo?, but container is faster.

I know but stability of the integration platform is more important than speed. 

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/travis/install-services.sh

**Comment by mwjames** [comment]
>  trusty beta with sudo?

One would have to verify that each job (and we have 10 of them) is doing an equally good execution compared to the current setup. Those services listed above have to run no matter what, whether they run with/without `sudo` doesn't really matter but the current setup required them to be setup with `sudo`.

**Comment by paladox** [comment]
Ive added the package here https://github.com/travis-ci/apt-package-whitelist/pull/3453 for the container.

**Comment by paladox** [comment]
the container runs on ubuntu precise which the tests were doing already does.

**Pull request closed without merging**
