### PR TITLE
Special:Browse improve mobile display (replace <table> with <div>)

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

- Replaces the use of `<table>` with `<div>` (together with `display: table;`)
- Provides better responsiveness towards smaller screens 
- Avoids `MobileFrontend` display  issues (uneven table columns) as seen in 

image

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
* http://softwareengineering.stackexchange.com/questions/277778/why-are-people-making-tables-with-divs
* http://www.dummies.com/web-design-development/css3/using-the-div-tag-to-create-tables/
* http://divtable.com/generator/

**Comment by mwjames** [comment]
@kghbln Once this is merged, some manual testing with different browsers (incl. MobileFrontend) would be nice.

PS: The autocomplete input in connection with `MobileFrontend` doesn't work (or better is disabled) for reasons listed in #2377.

**Comment by mwjames** [comment]
## Before

image

## After

image

**Comment by kghbln** [comment]
I only have limited options to test this since I do not have a mobile device and also run Linux. So I can just test

https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Parcourir/:Main-5FPage&mobileaction=toggle_view_mobile 

on a desktop for Chrome and Firefox with latest versions at the time of writing this. Both views work perfect for me.

One thing I realize is that mobile editing does not work but I cannot tell if this is related to this change. I guess not. I get redirected to the editor but end up here:

https://sandbox.semantic-mediawiki.org/w/index.php?title=Main_Page&section=0#/editor/0

Also I do not see the factbox.

Both issues however are not observed using "Special:Browse" this pr actually addresses.

I will ping the testers group after confirming that the latter observations are indeed unrelated to this pr.

**Comment by mwjames** [comment]
> Also I do not see the factbox on regular mobile page view.

The MobileFrontend doesn't implement all necessary hooks that are run for the Vector skin, so unless the `SkinAfterContent`, `SkinTemplateNavigation` are supported there is not a lot we can do.

> One thing I realize is that mobile editing does not work but I cannot tell if this is related to this change.

No.

**Comment by kghbln** [comment]
@SemanticMediaWiki/testers It will be nice if you could test "Special:Browse" on sandbox, e.g. https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Main-5FPage and report back. I have listed the presumably most popular combinations:

Linux
- [ ] Chrome 57 @kghbln - works
- [ ] Firefox 52 @kghbln - works

Mac
- [ ] Safari 10
- [ ] Chrome 57
- [ ] Firefox 52

Windows
- [ ] Chrome 57
- [ ] Firefox 52
- [ ] Edge 38
- [ ] Opera 43
- [ ] Explorer 10

**Comment by kghbln** [comment]
> One thing I realize is that mobile editing does not work but I cannot tell if this is related to this change. I guess not. I am supposedly being redirected to the editor but end up here:
> https://sandbox.semantic-mediawiki.org/w/index.php?title=Main_Page&section=0#/editor/0

That's indeed a Minerva issue tracked on [Phabricator](https://phabricator.wikimedia.org/T162708).

**Comment by kghbln** [comment]
Cool. Windows got tested for Chrome and Firefox. Some Mac users around?

**Comment by rcdeboer** [comment]
I've tested Edge and Explorer on Windows. Seems to work fine on both.

**Pull request merged**
