### PR TITLE
WikiPageValue to use Sanitizer on caption/label output / Test XSS injection

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: # [0]

This PR addresses or contains:

- Use Sanitizer::removeHTMLtags instead of htmlspecialchars_decode

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

[0] http://wikimedia.7.x6.nabble.com/Modify-table-header-in-quot-further-results-quot-td5068597.html

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI

[0] query headers should display with the same output now in `Special:Ask` as compared with embedded queries.

[0] http://sandbox.semantic-mediawiki.org/wiki/Modify_table_head

**Comment by kghbln** [comment]
> query headers should display with the same output now in Special:Ask as compared with embedded queries.

@stefahn FYI

@mwjames Great, this works perfect now! Many thanks! I probably should have come up with this earlier. Will it be possible to allow just wiki links like `[[page|label]]` and `[[page]]` for [`intro` and `outro`](http://sandbox.semantic-mediawiki.org/wiki/Modify_intro_and_outro_parameter)?

**Comment by stefahn** [comment]
@kghbln Thanks for informing me on this!

@mwjames Great work! Thanks a lot! Waiting for the next release in which this improvement will be included.

**Comment by mwjames** [comment]
> Will it be possible to allow just wiki links like [[page|label]] and [[page]] for intro and outro? 

It's a different function but #2007 should help providing the expected results.

**Comment by kghbln** [comment]
> It's a different function but #2007 should help providing the expected results.

WOW, this is great. Thanks a lot!

**Pull request merged**
