### PR TITLE
Comma as default valuesep with template format

### PR DESCRIPTION
**Pull request by matthew-a-thompson**
See comment from @cicalese in #2331 regarding need for valuesep to default to comma when this parameter is offered by the template output format.

### CODE REVIEW

**Comment by kghbln** [comment]
Thanks for the pull. Just requested a review.

**Comment by kghbln** [comment]
@mwjames Is this backportable to 2.5.x?

**Comment by mwjames** [comment]
> @mwjames Is this backportable to 2.5.x?

Back-ported to 2.5.x with 36cec82.

**Comment by mwjames** [comment]
https://sandbox.semantic-mediawiki.org/wiki/Issue/2522

**Comment by kghbln** [comment]
> https://sandbox.semantic-mediawiki.org/wiki/Issue/2522

or https://sandbox.semantic-mediawiki.org/wiki/Template_sep_valuesep

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3ATemplate_format&type=revision&diff=52032&oldid=51666)

**Comment by cicalese** [comment]
Thank you all so much for getting this done!

Cindy

**Pull request merged**
