### PR TITLE
Special:Browse to use `smwbrowse`, deprecate `BrowseBySubject` API, refs 2696

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2696

This PR addresses or contains:

- Deprecates the `BrowseBySubject` API module in favour of `smwbrowse`
- `Special:Browse` is to use the `smwbrowse` API module, `group` and `incoming` display option from within `Special:Browse` will now trigger a API request instead of a GET request

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
Finally [documented.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AAPI%3Abrowsebysubject&type=revision&diff=73730&oldid=62673)

**Comment by kghbln** [comment]
@mwjames I also [moved over the comment](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AAPI%3Asmwbrowse&type=revision&diff=73731&oldid=73727) to the docu page of the new module.

**Comment by mwjames** [comment]
> I also moved over the comment to the docu page of the new module. If untrue pls revert of amend.

If browsing a subject, you can define the `subobject` as part of the parameter:
`'api.php?action=smwbrowse&browse=subject&params={ "subject": "Main page", "ns" :0, "iw": "", "subobject": "" }',`

**Comment by kghbln** [comment]
This means that with the new module you can indeed add e.g. "Foo#_SubobjectHash"?

**Comment by mwjames** [comment]
> This means that with the new module you can indeed add e.g. "Foo#_SubobjectHash"?!

Yes, you can browse the specific subject by calling it via `'api.php?action=smwbrowse&browse=subject&params={ "subject": "Foo", "ns" :0, "iw": "", "subobject": "_SubobjectHash" }'`

See the live example with (`{ "subject": "Recurring events", "ns" :0, "iw": "", "subobject": "_4de2ff4dac99786efae69783cb0abd21" }`)[0].

[0] https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:ApiSandbox#action=smwbrowse&format=json&browse=subject&params=%7B%20%22subject%22%3A%20%22Recurring%20events%22%2C%20%22ns%22%20%3A0%2C%20%22iw%22%3A%20%22%22%2C%20%22subobject%22%3A%20%22_4de2ff4dac99786efae69783cb0abd21%22%20%7D

**Comment by kghbln** [comment]
Great, thanks! I guess I sorted out the docu of this module and added and example for an subobject.

**Pull request merged**
