### PR TITLE
Add entity specific collation support (smw_sort), refs 2065

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2065

This PR addresses or contains:

- Prototype on how to extend SMW and support a flexible (based on `$smwgEntityCollation`) collation mapping for entities.
- `$smwgEntityCollation` should correspond to the `$wgCategoryCollation` setting (also in regards to selected argument values), yet it is kept separate to have a better control over changes in regards to the collation, sorting, and display of values.
- As mentioned in #2065, a new field `smw_sort` is required that can hold a collated sort value and no longer conflicts with the search and match `smw_sortkey` field. 
- The `smw_sortkey` becomes a field that stores a literal value for a search hence it will be renamed in a follow-up to reflect that intention. 
- This PR alters the DB schema and can therefore not be back-ported.
- When changing the `$smwgEntityCollation` option it is expected that a user applies the same caution as for the standard MediaWiki system with either `rebuildData.php` or `updateEntityCollation.php` being run immediately post the change to ensure that data are updated and correspond to the setting.
- `$smwgEntityCollation` uses `identity` as default setting and will produce the same sorting results as without this change

## Example

Output example of the ID_TABLE with a `$wgCategoryCollation = 'uppercase';` setting.

image

## Update

In case the table is updated and data exists but without the `smw_sort` field being present, the `update.php` or `setupStore.php` will initiate a post processing where the content of `smw_sortley` is copied once to the `smw_sort` field during the setup. The message will be similar to:

```
Checking post creation activities ...
   Table smw_object_ids ...
   ... copying smw_sortkey to smw_sort ... done.
   ... done.
```
Depending on the size of the table, this process may take a moment. Any update on the collation/sort field hereafter has to be done executing the `updateEntityCollation.php` script.

The `updateEntityCollation.php` maintenance script will output something like:

```
$ php maintenance/updateEntityCollation.php

[ Notes ]

- $smwgEntityCollation              uca-default-u-kn
- $wgCategoryCollation              numeric

The setting of $smwgEntityCollation and $wgCategoryCollation are different
and may result in an inconsitent sorting display for entities.

[ Update ]

- Selecting rows ...                1 to 100659
- Updating the smw_sort field ...     0% (313/100659)

```

## Technical notes

- `SMW_SPARQL_QF_COLLATION` (see `DefaultSettings.php`) which allows to replicate collation specific information using `swivt:sort`
- `Collator` is the interface to MediaWiki's `Collation` class
- `TableFieldUpdater` is the sole responsible class to update the `smw_sortkey` and `smw_sort` field
- `TableIntegrityExaminer` will copy the content of `smw_sortkey` once at the time `smw_sort` is added to the schema
- `TableBuilder::getProcessLog` returns a list of activities occurred during the table update and is used in `TableIntegrityExaminer`
- `SortPropertyValueResourceBuilder` now handles the export of `_SKEY` resources
- `updateEntityCollation.php` script provides a tool for mass updates on the occasion that the `$smwgEntityCollation` setting is changed

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln Some testing guidelines:

- Run `update.php` or `setupStore.php` and you expect to see `... copying smw_sortkey to smw_sort ... done.`  only the first time the script is run
- `smw_sort` field should be visible in the `smw_object_ids` table with the same content as `smw_sortkey`
- Change `$smwgEntityCollation` to something like `numeric` or `uca-default-u-kn` [0]
- After the setting has changed, you are required to run `updateEntityCollation.php` with the result that the content in `smw_sort` has changed accordingly 
- Sorting in [1] should be different from [2] (using the default `identity` setting)

[0] https://www.mediawiki.org/wiki/Manual:$wgCategoryCollation
[1] https://sandbox.semantic-mediawiki.org/wiki/Issue/2429/NumericSorting
[2] https://cloud.githubusercontent.com/assets/1245473/25782835/abf402c8-338c-11e7-9e0b-940bae59503e.png

**Comment by mwjames** [comment]
> Run update.php or setupStore.php and

I had to run `Special:SemanticMediaWiki` `updatetables` (as replacement for `update.php` or `setupStore.php`) otherwise the sandbox would have been blocked on:

```
Original exception: [7e298e0712bc0dbc0186f5b2] /wiki/Issue/2429/NumericSorting DBQueryError from line 1054 of /var/www/htdocs/mw/02100/w/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading?
Query: SELECT smw_id,smw_sortkey,smw_sort FROM `02100_smw_object_ids` WHERE smw_title = 'Issue/2429/NumericSorting' AND smw_namespace = '0' AND smw_iw = '' AND smw_subobject = '' LIMIT 1
Function: SMWSql3SmwIds::getDatabaseIdAndSort
Error: 1054 Unknown column 'smw_sort' in 'field list' (localhost)
```

> expect to see ... copying smw_sortkey to smw_sort ... done. only the first time the script is run

The output contained:

```
Checking post creation activities ...
   Table smw_object_ids ...
   ... copying smw_sortkey to smw_sort ... done.
   ... done.
```

**Comment by kghbln** [comment]
Documented:
- [`$smwgSparqlQFeatures`](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgSparqlQFeatures&type=revision&diff=57790&oldid=52081)
- [`$smwgEntityCollation`](https://www.semantic-mediawiki.org/wiki/Help:$smwgEntityCollation)
- [updateEntityCollation.php](https://www.semantic-mediawiki.org/wiki/Help:Maintenance_script_"updateEntityCollation.php")

**Comment by kghbln** [comment]
@mwjames [Code docu](https://doc.semantic-mediawiki.org/namespaceSMW_1_1Maintenance.html) does not seem to have notes about the maintenance script

**Comment by mwjames** [comment]
> Code docu does not seem to have notes about the maintenance script

Yes, because `updateEntityCollation.php` has no class in `SMW\Maintenance` as it uses `TableFieldUpdater` directly to push related updates when running the script.

**Comment by kghbln** [comment]
Thanks for the information. Just wanted to make sure! :)

**Comment by kghbln** [comment]
@mwjames Another question: The default for `$smwgEntityCollation` is "identity" is different to MW's `$wgCategoryCollation` which is "uppercase". So running "updateEntityCollation.php" should through a not about this incongruent setting even though the sysadmin did not change a thing. My theory is that SMW was always different in this respect however I one chooses to make a change in this respect the sysadmin should probably do congruent settings for both configuration parameters?!?

**Comment by mwjames** [comment]
> The default for $smwgEntityCollation is "identity" is different to MW's $wgCategoryCollation which is "uppercase". 

Well, the default SMW sort mode has been that equally of "identity" therefore it should remain so since we don't want to break existing queries that would otherwise carry a different sort match. If users want to change the setting then of course it is suggested to match both.

**Comment by kghbln** [comment]
> Well, the default SMW sort mode has been that equally of "identity"  ...

That's what I have guessed. Thanks for confirming!

**Pull request merged**
