### PR TITLE
[FacetedSearch] Updates for SMW 4.1.3

### PR DESCRIPTION
**Pull request by YOUR1**
This https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4663 was an old MR by James. I think this is quite valuable, so I made sure that his code isn't lost and made it working on 4.1.3.

### CODE REVIEW

**Comment by YOUR1** [comment]
> Thank you @YOUR1, this is quite valuable indeed. Could you look at the failing tests here on the GitHub?

Took some commits (long live sleep deprivation) - but here you go.

**Comment by YOUR1** [comment]
@JeroenDeDauw I'm not quite sure why one check is skipped and one cancelled. Can you recheck?

**Comment by jaideraf** [comment]
Very interesting functionality! 👍🏼  I tested and generally it works. Just the export feature that is not working (the JSON, CSV and RDF export)

https://wikincat.org/wiki/Especial:FacetedSearch?profile=work&q=%5B%5BCategory%3AObra%5D%5D&reset=true&utf8=%E2%9C%93&limit=50&offset=0&csum=324179152&format=table&order=asc&size=50&uselang=en

I wish I could hide some administrative properties from the filters, I don't know how to do it yet. 
@kghbln @krabina take a look.

**Comment by YOUR1** [comment]
> Very interesting functionality! 👍🏼 I tested and generally it works (it requires the update.php). Just the export feature that is not working (the JSON, CSV and RDF export):
> 
> https://wikincat.org/w/index.php?title=Special:FacetedSearch&q=%5B%5BCategory%3AObra%5D%5D&profile=work&uselang=en
> 
> I wish I could hide some administrative properties from the filters, I don't know how to do it yet. @kghbln @krabina take a look.

The export functionality is working fine on my side, can you give me more info about the error you are encountering?

**Comment by krabina** [comment]
Interesting. I found a page showing some help information: https://wikincat.org/wiki/Especial:FacetedSearch?profile=default&q=&utf8=%E2%9C%93&limit=0&offset=0&csum=

The thiing is: this is an even more complex interface then Special:aAsk. So it is not so much for the end user, but for SMW professionals. Which is fine, but I thought that faceted search would build on full-text search that cen be narrowed down based on facets. Something like this: https://www.mediawiki.org/wiki/Extension:WikiSearchFront

**Comment by jaideraf** [comment]
> The export functionality is working fine on my side, can you give me more info about the error you are encountering?

Indeed. In **Firefox** it is working fine, but in **Chrome** the console says: 

error

I don't know, maybe it is something wrong with my side (https/network/redirects...). Thank you.

**Comment by jaideraf** [comment]
> Perhaps your wiki is configured on http:// instead of https://.

Wow, just exactly that. Just changed `$wgServer = "http://wikincat.org";` to `$wgServer = "https://wikincat.org";` and the problem is gone. 👍🏼

**Comment by krabina** [comment]
So it seems to be working fine? Since it is a new feature it is not breakting anything. Basically we could go ahead an merge this. Any objections?

**Comment by JeroenDeDauw** [comment]
Would be great if someone could add a line about what this PR improves to https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/releasenotes/RELEASE-NOTES-4.2.0.md

**Comment by robinwiel** [comment]
@JeroenDeDauw Done! #5654

**Comment by Nikerabbit** [comment]
Can you please rename the message key `categories` that conflicts with MediaWiki core?

**Comment by JeroenDeDauw** [comment]
Yes, please prefix all new messages with `smw_`  or similar

**Comment by krabina** [comment]
@YOUR1 can you do this, please?

**Comment by YOUR1** [comment]
That's already been done by someone else: https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/73c768f3912ee8a5770500bd54541ba8b2e4cd0b

**Comment by krabina** [comment]
ah, thank you @kghbln!

**Comment by JeroenDeDauw** [comment]
Are there any nice screenshots of this new feature we can use to advertise it on social media?

**Comment by krabina** [comment]
There are some in the original PR https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4663

**Comment by JeroenDeDauw** [comment]
Would be nice to get some good ones that are not 4 years old

**Comment by YOUR1** [comment]
> Would be nice to get some good ones that are not 4 years old
Can't the sandbox wiki be updated to the latest release? 

Our farm has only dutch sites on it, so that's not very nice to demonstrate...

**Comment by kghbln** [comment]
> Can't the sandbox wiki be updated to the latest release?

Yes, it can. I just did it.

**Comment by kghbln** [comment]
As a sidenote. In case someone runs into issues importing the required profile, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5654#issuecomment-2238673159

**Comment by krabina** [comment]
> > Can't the sandbox wiki be updated to the latest release?
> 
> Yes, it can. I just did it. https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:FacetedSearch

Can you give an example of what to search for? I cannot find anything.

**Comment by YOUR1** [comment]
> > Can you give an example of what to search for? I cannot find anything.
> 
> The NFL namespace is full of data: https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:Index?prefix=&namespace=3300. It could make sense, at least for US Americans. Apart from that, I am facing the same situation as you.

[[Category:NFL:Season]] has data in it?

See link: https://sandbox.semantic-mediawiki.net/wiki/Sp%C3%A9cial:FacetedSearch?q=%5B%5BCat%C3%A9gorie%3ANFL%3ASeason%5D%5D&utf8=%E2%9C%93&limit=50&offset=0&csum=964386528&pv%5BNFL%3AExpPts%5D%5B%5D=&pv%5BNFL%3AOnsidekick%5D%5B%5D=&pv%5BNFL%3AAbsScoreDiff%5D%5B%5D=&format=table&order=asc&size=50

**Comment by jaideraf** [comment]
> Can you give an example of what to search for? I cannot find anything.

Try [[Catégorie:City]]

**Comment by JeroenDeDauw** [comment]
That's nice already. What about something more visual? I saw a map in the old screenshots by MWJames. A map or similar visualization would be neat to show off.

**Comment by YOUR1** [comment]
> That's nice already. What about something more visual? I saw a map in the old screenshots by MWJames. A map or similar visualization would be neat to show off.

It's possible but it requires an additional schema profile. See: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/Schema/docs/facetedsearch.profile.md

**Pull request merged**
