### PR TITLE
Add query profile to #concept

### PR DESCRIPTION
**Pull request by mwjames**
https://github.com/SemanticMediaWiki/SemanticNotifications/pull/10

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
What is a query profile?

**Comment by mwjames** [comment]
> What is a query profile?

Something like:

http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Browse/Berlin-23_QUERY414f168636444d974d7576148e15cffa

image

**Comment by JeroenDeDauw** [comment]
So a query profile is the meta data we store about it since some versions back?

**Comment by mwjames** [comment]
> So a query profile is the meta data we store about it since some versions back?

Yes.

SemanticMediaWiki/SemanticNotifications#10 requires the information to be available in the `CompositePropertyTableDiffIterator` so that any change to its query can be watched and eventually trigger a notification.

**Comment by JeroenDeDauw** [comment]
+1

**Pull request merged**
