### PR TITLE
Add create restriction on properties, refs 2232

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2232

This PR addresses or contains:

- Adds `$smwgCreateProtectionRight` setting
- If enabled, restrict creation of new properties to user with the assigned right only
- https://www.semantic-mediawiki.org/wiki/Authority_mode

image

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI, I'll leave this open for a week in case you want to comment.

**Comment by kghbln** [comment]
Indeed a nice enhancement which supports data curation and gardening! One question: How does this integrate with special page "WantedProperties" which currently has a slightly different scope? I can imagine that such properties which were not yet created could be listed there too - somehow marked in a special way.

**Comment by mwjames** [comment]
> integrate with special page "WantedProperties" which currently has a slightly different scope? I can imagine that such properties which were not yet created could be listed there too 

I'll try to squeeze in a follow-up on this.

**Comment by mwjames** [comment]
> I'll try to squeeze in a follow-up on this.

Done in #2615.

**Comment by kghbln** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Create_protection - to be fluffed

**Comment by mwjames** [comment]
>https://www.semantic-mediawiki.org/wiki/Help:Create_protection - to be fluffed

I gave it a quick note.

**Comment by kghbln** [comment]
> I gave it a quick note.

Cool, my earlier comment was more of a not to self. Nice. [`$smwgCreateProtectionRight`](https://www.semantic-mediawiki.org/wiki/Help:$smwgCreateProtectionRight) is documented too. :)

**Comment by mwjames** [comment]
@kghbln Quick question, Do you think we make the collection display of the same size as the infobox (280px) as the current box feels a bit overwhelming when reading (focusing on) the text.

**Comment by kghbln** [comment]
Yeah, sure. Since I do not use mobile devices I have no idea how the wiki appears on respective clients. For me personally on a desktop things are already pretty tiny.

**Pull request merged**
