### PR TITLE
TableBuilder: Use || instead of 'or' for if statement

### PR DESCRIPTION
**Pull request by paladox**
## Summary by CodeRabbit

- **Bug Fixes**
	- Enforced a check for valid logical operators by removing an exclusion rule.
  
- **Style**
	- Added a newline at the end of the configuration file for better formatting.

- **Refactor**
	- Improved clarity in the logical operation within the `recursive_array_search` method.

### CODE REVIEW

**Review by alistair3149 — APPROVED** [review]

**Comment by alistair3149** [comment]
@coderabbitai review

**Comment by paladox** [comment]
I'm not sure why all the tests are failing now?

**Comment by paladox** [comment]
> .Deprecated: Caller from SMW\SQLStore\PropertyStatisticsStore::setUsageCount ignored an error originally raised from SMW\SQLStore\PropertyStatisticsStore::insertUsageCount: [1062] Duplicate entry '1' for key 'p_id' in /var/www/html/includes/debug/MWDebug.php on line 381

huh

**Comment by alistair3149** [comment]
Hmm the changes in this PR shouldn't cause the test failures, that's very weird

**Comment by paladox** [comment]
> Hmm the changes in this PR shouldn't cause the test failures, that's very weird

I think https://github.com/gesinn-it-pub/docker-compose-ci/pull/6 could have broken it and which https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5865 fixes it? I thought it was pinned because of the submodule but idk. It seems to run when I fix the commands in the composer file to match the changes in the build.

**Comment by JeroenDeDauw** [comment]
CI is broken on master: 
image
https://github.com/SemanticMediaWiki/SemanticMediaWiki/actions?query=branch%3Amaster

**Comment by paladox** [comment]
@JeroenDeDauw see https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5866#issuecomment-2549295774

**Pull request merged**
