### PR TITLE
Output option to highlight search tokens in result set

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

- Adds the `-hl`output formatter, allowing it to highlight search tokens in a result set

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
https://sandbox.semantic-mediawiki.org/wiki/Issue/2253

image

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by mwjames** [comment]
Here is an example [0] when one is looking for a needle in a haystack.

[0] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:Ask&x=-5B-5B~~rheumatological-5D-5D%2F-3FHas-20abstract-23-2Dhl&format=broadtable&link=all&headers=show&searchlabel=...%20further%20results&class=sortable%20wikitable%20smwtable&offset=&limit=50&mainlabel=

**Comment by kghbln** [comment]
[Finally documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AFull-text_search%2FSearching&type=revision&diff=51779&oldid=50298). Cool feature!

**Pull request merged**
