### PR TITLE
Inject RecurringEvents, refs 3541

### LINKED ISSUE #3541: `#set_recurring_event` creates only 26 subobjects
### Setup and configuration

- MediaWiki | 1.31.1 (8e4e0d8)19:00, 15. Nov. 2018
- PHP | 7.0.30-0+deb9u1 (apache2handler)
- MariaDB | 10.1.26-MariaDB-0+deb9u1
- Semantic MediaWiki | 3.1.0-alpha (a3460c1) 08:20, 15. Nov. 2018

### Issue
`#set_recurring_event` creates only 26 subobjects. Configuration parameter `$smwgDefaultNumRecurringEvents` is thus being ignored even in default install.

Note that this is not an SMW 3.0.0 regression but was originally detected on SMW 2.5.8

### Steps to reproduce
[Birthday events template](https://sandbox.semantic-mediawiki.org/wiki/Mod%C3%A8le:TestBirthdays) with the following content:
```
{{#set_recurring_event:
 Is birthday
 |property=Has date
 |start={{{birth|}}}
 |end={{{death|}}}
 |unit=year
 |period=1
 |event=birthday
 |eventcolour=ff8000
 |eventname={{{name|}}}
}}
```
[Data setting and query](https://sandbox.semantic-mediawiki.org/wiki/Issue/3541). The result only returns 26 events though 100 are expected.

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #3541

This PR addresses or contains:

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #3541

### CODE REVIEW

**Comment by kghbln** [comment]
Thanks a lot for the pull. This was one of the biggest issues in 2.5 and 3.0 I believe.

**Comment by kghbln** [comment]
@mwjames Since we were not testing `#set_recurring_event` at all I figured it will be a good idea to add some more testing #3592 and #3593

**Comment by mwjames** [comment]
> @mwjames Since we were not testing #set_recurring_event at all I figured it will be a good idea to add some more testing #3592 and #3593

That's the spirit I'd like to from others  (@kghbln @hexmode @krabina @planetenxin @s7eph4n @jamesmontalvo3)  to get involved and evolve the software, not necessarily by extending its functionality but by providing test scenarios to keep existing (or assumed) functions tested and provide means for upcoming changes to be less likely in a center for a regression.

**Comment by kghbln** [comment]
> That's the spirit I'd like to from others

Thanks for the cheer-up. However I must admit that adding these tests still proved to be insufficient to catch all issues, i.e. expanding test is an ongoing process.

**Pull request merged**
