### PR TITLE
Swap implode arguments

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fix https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4501

### CODE REVIEW

**Comment by kghbln** [comment]
Officially we do not support PHP 7.4 for SMW 3.1. Not sure whether to back-port or not.

**Comment by JeroenDeDauw** [comment]
Can backport

Should never have been in this order in the first place

**Comment by mwjames** [comment]
> Should never have been in this order in the first place

It what supported in PHP 7.4-.

> Officially we do not support PHP 7.4 for SMW 3.1. Not sure whether to back-port or not.

Can be backported but it doesn't change the fact that PHP 7.4 isn't supported on either 3.1 or master because first of all it isn't in the CI matrix and aside the technicality, it requires more work to get pass all tests.

**Comment by JeroenDeDauw** [comment]
> It what supported in PHP 7.4-.

Many things are still supported in PHP 8 and yet should still not be done.

**Pull request merged**
