### PR TITLE
1.28-alpha / postgres setup/tests are broken [DNM]

### PR DESCRIPTION
**Pull request by paladox**
This PR is made in reference to: #

This PR addresses or contains:

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
Someone did something so that 1.28 + postges no longer can be installed:

```
CREATE DATABASE
+php maintenance/install.php --dbtype postgres --dbuser postgres --dbname its_a_mw --pass nyan TravisWiki admin --scriptpath /TravisWiki
PHP 5.5.38 is installed.
Warning: Could not find APCu, XCache or WinCache.
Object caching is not enabled.
Found ImageMagick: /usr/bin/convert.
Image thumbnailing will be enabled if you enable uploads.
Found the Git version control software: /usr/bin/git.
Using server URL "/TravisWiki".
Warning: Your default directory for uploads (/home/travis/build/SemanticMediaWiki/mw/images/) is not checked for vulnerability
to arbitrary script execution during the CLI install.
Using the intl PECL extension for Unicode normalization.
The environment has been checked.
You can install MediaWiki.
Setting up database
done
Checking for language PL/pgSQL
done
Creating schema
done
Creating tables
PHP Fatal error:  Call to undefined method DatabasePostgres::getSchemaPath() in /home/travis/build/SemanticMediaWiki/mw/includes/installer/PostgresInstaller.php on line 609
PHP Stack trace:
PHP   1. {main}() /home/travis/build/SemanticMediaWiki/mw/maintenance/install.php:0
PHP   2. require_once() /home/travis/build/SemanticMediaWiki/mw/maintenance/install.php:156
PHP   3. CommandLineInstaller->execute() /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:110
PHP   4. CliInstaller->execute() /home/travis/build/SemanticMediaWiki/mw/maintenance/install.php:142
PHP   5. Installer->performInstallation() /home/travis/build/SemanticMediaWiki/mw/includes/installer/CliInstaller.php:136
PHP   6. call_user_func:{/home/travis/build/SemanticMediaWiki/mw/includes/installer/Installer.php:1515}() /home/travis/build/SemanticMediaWiki/mw/includes/installer/Installer.php:1515
PHP   7. PostgresInstaller->createTables() /home/travis/build/SemanticMediaWiki/mw/includes/installer/Installer.php:1515

Fatal error: Call to undefined method DatabasePostgres::getSchemaPath() in /home/travis/build/SemanticMediaWiki/mw/includes/installer/PostgresInstaller.php on line 609

Call Stack:
    0.0003     283432   1. {main}() /home/travis/build/SemanticMediaWiki/mw/maintenance/install.php:0
    0.0027     743736   2. require_once('/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php') /home/travis/build/SemanticMediaWiki/mw/maintenance/install.php:156
    0.0727   12287376   3. CommandLineInstaller->execute() /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:110
    0.2881   24001600   4. CliInstaller->execute() /home/travis/build/SemanticMediaWiki/mw/maintenance/install.php:142
    0.2881   24002776   5. Installer->performInstallation() /home/travis/build/SemanticMediaWiki/mw/includes/installer/CliInstaller.php:136
    0.3210   24453712   6. call_user_func:{/home/travis/build/SemanticMediaWiki/mw/includes/installer/Installer.php:1515}() /home/travis/build/SemanticMediaWiki/mw/includes/installer/Installer.php:1515
    0.3210   24454048   7. PostgresInstaller->createTables() /home/travis/build/SemanticMediaWiki/mw/includes/installer/Installer.php:1515
```

**Comment by mwjames** [comment]
I'm so glad that WMF is really testing it changes. https://phabricator.wikimedia.org/T148332!

**Comment by paladox** [comment]
@mwjames I'm going to see If I can setup PostgreSQL in ci, per https://phabricator.wikimedia.org/T22343 and https://phabricator.wikimedia.org/T39602

Plus PostgreSQL seems to be broken beyond fixing this problem, see https://phabricator.wikimedia.org/T147599

**Comment by paladox** [comment]
One error is now fixed.

**Comment by paladox** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1930 can be closed once it is tested.

**Comment by mwjames** [comment]
https://phabricator.wikimedia.org/T148332 was closed but a new error https://phabricator.wikimedia.org/T148628 appeared.

**Comment by mwjames** [comment]
Please someone rescue me from insanity, instead of addressing the problem you'd be invited to ... !?!

>... As frustrating as it is to deal with MediaWiki's half-hearted Postgres support, blocking unrelated patches which aim to improve that support won't help.
>@mwjames: are you maybe interested in organizing a discussion about the state of non-MySQL DB engines in MediaWiki? You can still propose sessions for WikiDev17 until the end of the week :)
https://www.mediawiki.org/wiki/Wikimedia_Developer_Summit/Call_for_participation

https://gerrit.wikimedia.org/r/#/c/317863/

**Comment by mwjames** [comment]
... and another one https://phabricator.wikimedia.org/T149468, so someone is really pulling a rabbit here.

**Comment by mwjames** [comment]
I posted the necessary analysis in [0] and since this is no SMW issue, it is expected that MW-core fixes the regression.

[0] https://phabricator.wikimedia.org/T149454#3142728

**Pull request closed without merging**
