### PR TITLE
Fix Concept on postgres

### PR DESCRIPTION
**Pull request by mwjames**
refs #779

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
+1

**Comment by mwjames** [comment]
```
SMW\Tests\Integration\Query\ConceptQueryDBIntegrationTest::testConceptQueryForAnyValueCondition
Failed asserting that actual size 0 matches expected size 6.
```

**Comment by mwjames** [comment]
I didn't fix the issue because the tests was not run on group `SMWExtension`.

**Comment by mwjames** [comment]
@arkadini Maybe if you have time, could you have a look at this because it is the only SMW code that's doesn't play well with `postgres` (`ConceptCache.php`) or manually test if something like `{{#concept: [[Modification date::+]]|some ...}}` does actually work on `postgres`.

```php
		if ( $wgDBtype == 'postgres' ) { // PostgresQL: no INSERT IGNORE, check for duplicates explicitly
			$where = $queryPart->where . ( $queryPart->where ? ' AND ' : '' ) .
				"NOT EXISTS (SELECT NULL FROM $concCacheTableName" .
				" WHERE {$concCacheTableName}.s_id = {$queryPart->alias}.s_id " .
				" AND  {$concCacheTableName}.o_id = {$queryPart->alias}.o_id )";
		} else { // MySQL just uses INSERT IGNORE, no extra conditions
			$where = $queryPart->where;
		}

		// TODO: catch db exception

		$db->query( "INSERT " . ( ( $wgDBtype == 'postgres' ) ? '' : 'IGNORE ' ) .
			"INTO $concCacheTableName" .
			" SELECT DISTINCT {$queryPart->joinfield} AS s_id, $cid AS o_id FROM " .
			$db->tableName( $queryPart->joinTable ) . " AS {$queryPart->alias}" .
			$queryPart->from .
			( $where ? ' WHERE ' : '' ) . $where . " LIMIT $smwgQMaxLimit",
			$fname );
```

https://www.semantic-mediawiki.org/wiki/Help:Concepts

**Comment by JeroenDeDauw** [comment]
@mwjames perhaps we should write the dev list asking for some postgres help?

**Comment by yoonghm** [comment]
My changes to mediawiki on postgres driver has been merged into the master
https://gerrit.wikimedia.org/r/#/c/241497/

You may want to uncomment tests cases.

**Comment by mwjames** [comment]
> My changes to mediawiki on postgres driver has been merged into the master

This is good but we can't run against master because API tests are broken again (due to MW changes in MW 1.26) so we run most tests on MW 1.25.2 (or lower). We have one test job that runs on master just to verify that it is broken [0].

It could also be that we also need https://gerrit.wikimedia.org/r/#/c/241489/ merged be re-enable postgres on MW 1.26* (or worst 1.27*).

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/84122249

**Comment by mwjames** [comment]
In regards to

```php
	" WHERE {$concCacheTableName}.s_id = {$queryPart->alias}.s_id " .
	" AND  {$concCacheTableName}.o_id = {$queryPart->alias}.o_id )";
```

See my comments at  https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1165#issuecomment-143312628.

**Pull request closed without merging**
