### PR TITLE
Fix "Deprecated: Return type of x should either be compatible with Iterator::x"

### PR DESCRIPTION
**Pull request by paladox**
I have made the types match https://www.php.net/manual/en/class.iterator.php

We require php 7.4+ so there is no incompatibility.

### CODE REVIEW

**Comment by paladox** [comment]
@JeroenDeDauw if you prefer, I can use "#[\ReturnTypeWillChange]". Which would be a noop and fix the warning.

**Comment by JeroenDeDauw** [comment]
If the tests are indeed running with PHP 7.4, then that is an issue that should be fixed, though presumably in a separate PR.

**Comment by paladox** [comment]
@JeroenDeDauw this is ready to be merged.

**Comment by JeroenDeDauw** [comment]
The PHP CI issue is now tracked by
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5813

**Pull request merged**
