### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Making this a PR for extra visibility. If I missed anything, let me know. Or make your own PR.

**Comment by jaideraf** [comment]
@JeroenDeDauw it should mention (maybe in the Upgrading section, I don't know) the new way the extension is loading: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5144

```
wfLoadExtension( 'SemanticMediaWiki' );
enableSemantics( 'example.org' );
```

**Comment by JeroenDeDauw** [comment]
@hexmode can you confirm that is the correct way to do things after your change?

**Comment by hexmode** [comment]
@JeroenDeDauw Yes, that should do it.

**Pull request merged**
