### PR TITLE
Use distinct sortfield list (MySQL 5.7), refs 2078

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2078

This PR addresses or contains:

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln This one needs manual confirmation since we cannot test 5.7 (only 5.6) on Travis and MariaDB 10.1 doesn't choke on this very issue.

**Comment by kghbln** [comment]
@mwjames The field test tells that we are back in business. I can however only test SMW and not related extensions since as always Composer does not allow to mix dev with stable. So we will need a backport and release 2.4.4 if we want to continue with the whole lot on smw.o.

Only one thing is realise are there nasty commas on [Version history](https://www.semantic-mediawiki.org/wiki/Help:SMW_History) we are now getting. This may however be unrelated to this issue here.

**Comment by kghbln** [comment]
I will be off for about 2 hours.

**Comment by mwjames** [comment]
> Only one thing is realise are there nasty commas on Version history we are now getting. This may however be unrelated to this issue here.

Relates to #2022 where when no `sep=` is defined it falls back to `,` (let's discussion this on #2022)

**Comment by mwjames** [comment]
> So we will need a backport and release 2.4.4 if we want to continue with the whole lot on smw.o.

Okay, I'll make a backport but leave the admin stuff (tags etc.) to you guys.

**Comment by kghbln** [comment]
@mwjames Thanks a lot for your immediate fix!

**Comment by mwjames** [comment]
> @mwjames Thanks a lot for your immediate fix!

The backport fails on Travis so I need to spend time on it (d....)!

**Comment by kghbln** [comment]
> The backport fails on Travis so I need to spend time on it (d....)!

That's indeed truly desagreable. However, perhaps there are good changes that this will also show a way for master as soon as we test against MySQL 5.7 when using Ubuntu 16.04.

**Comment by mwjames** [comment]
> That's indeed truly desagreable. 

I found the error, this happens when you need to copy line by line because master has already changed quite a bit.

**Comment by kghbln** [comment]
> I found the error

I am glad that is was not too time consuming.

**Comment by mwjames** [comment]
> I am glad that is was not too time consuming.

Travis went green https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/cb75adb6fa9cd3d96926ba975806c4ce278fdaf1.

**Pull request merged**
