### PR TITLE
Make tests work with MW 1.35

### PR DESCRIPTION
**Pull request by hexmode**
Added a few skips, but otherwise made it work with REL1_35

### CODE REVIEW

**Comment by hexmode** [comment]
I'm a bit confused by [these failures](https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/523997560#L1750) since it looks like the problem is that [the language code was set to ja](https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/523997560#L728) for some reason.

**Comment by hexmode** [comment]
[sorting problem or test problem](https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/523997561#L1851)?

**Comment by gesinn-it** [comment]
> 
> 
> I'm a bit confused by [these failures](https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/523997560#L1750) since it looks like the problem is that [the language code was set to ja](https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/523997560#L728) for some reason.

The "ja" tests existed for quite some time but were never corretly executed. During my last fixes for Travis, "ja" test are executed as planned but reporting the issues you see now.

**Comment by gesinn-it** [comment]
> 
> 
> [sorting problem or test problem](https://app.travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/jobs/523997561#L1851)?

Side note: @Seb35 was working on fixes for some sorting issues related to triplestores in #4998 .

**Comment by JeroenDeDauw** [comment]
If the JA tests where not running before and they are not working when enabled now, then I suggest disabling them until the main tests are green. Could just removed the parameter in `.travis.yml`

**Comment by gesinn-it** [comment]
> Could just removed the parameter in `.travis.yml`

...or commented so that we don't forget to re-enable / fix them later

**Comment by hexmode** [comment]
> If the JA tests where not running before and they are not working when enabled now, then I suggest disabling them until the main tests are green. 

I'll do this momentarily.

**Comment by hexmode** [comment]
Just noticed the sorting failure was on PostgreSQL.  Adding an exception for that test.

**Comment by hexmode** [comment]
Um... I'm really sorry about pushing to master.  Could you take my privileges to do that away?

**Comment by hexmode** [comment]
> Um... I'm really sorry about pushing to master. Could you take my privileges to do that away?
[
Reverted my changes](https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/d72eaf4bc096318c276726a532934a62c4c0e49c) and made [a new pull request](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5026).

**Pull request merged**
