### PR TITLE
Ren smwgSparqlDatabaseConnector to smwgSparqlRepositoryConnector

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

- Replaces `$smwgSparqlDatabaseConnector` with `$smwgSparqlRepositoryConnector`

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
Documented [here](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgSparqlCustomConnector&type=revision&diff=55903&oldid=52060) and [there](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgSparqlRepositoryConnector&type=revision&diff=55902&oldid=51501). Hope that I got also all the links and related pages, too.

**Comment by mwjames** [comment]
> Documented here and there. Hope that I got also all the links and related pages, too.

I know its a bit of work but I wanted this to be in line with [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/src/SPARQLStore#repository-connector

**Comment by kghbln** [comment]
> I know its a bit of work but I wanted this to be in line with [0].

I believe that I am in if it comes to consistency. Also a chance to tidy stuff.

**Pull request merged**
