### PR TITLE
Move PropertyPage, ConceptPage

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2784 

This PR addresses or contains:

- Just in case some activities in relation to #2784 are going to happen, I dusted off an old PR that moves the property and concept page to its own `SMW\Page` NS
- It contains some minor refactoring and injects some of the required services using a factory 
- Adds some simple unit tests to assert the general functionality

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln @s7eph4n 

I added a minor design change which can be switched to but by default it still uses the old `smw-table smw-property-page-results legacy` (legacy class). Removing `legacy` switches to the new design and since I'm not sure it makes much difference or whether the new aliment is an improvement or not it is hidden from the "normal" user. Feel free to suggest a better design.

## Legacy
image

## New
image

**Comment by s7eph4n** [comment]
It makes it better aligned with the rest of the page, so I think it is a good move. :+1: 

N.B. 1: At some point we could think about a general rework of the styling, e.g. aligning _Pages with improper assignments_ and _Pages using..._, better use of "screen real estate", etc.
(A general SMW style overhaul might be a candidate for one of the [Outreach Programs](https://www.mediawiki.org/wiki/Outreach_programs).)

N.B. 2: MW supports Less since 1.22. Would it make sense to switch?

**Comment by mwjames** [comment]
> N.B. 1: At some point we could think about a general rework of the styling, e.g. aligning Pages with improper

#2786

> N.B. 2: MW supports Less since 1.22. Would it make sense to switch?

#2787

**Comment by kghbln** [comment]
Note that due to 6792db0 the new styling is default which  is indeed the better approach. PR now documented [here](https://www.semantic-mediawiki.org/wiki/Help:Property_page) and [there](https://www.semantic-mediawiki.org/wiki/Help:Concept_page)

**Pull request merged**
