### PR TITLE
Remove localized extension titles 

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #

This PR addresses or contains:
- Assure that the fallback in en is always used.

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
Because Semantic MediaWiki is a _Eigenname_. It should not have been translated in the first place.

**Comment by akuckartz** [comment]
It is a descriptive Eigenname. The translations can still be useful for some communities. Can "smw-title" be renamed to "smw-translated-title" or something similar so that the translations do not get lost?

**Comment by kghbln** [comment]
The translated strings are still available and preserved at translatewiki.net they however will not be synced into the repo. I find it highly irritating to have a different name on Special:Version.

**Comment by Nikerabbit** [comment]
Surely transliterations should be allowed?

**Pull request merged**
