### PR TITLE
 Remove long deprecated functions from SMWQueryProcessor

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Part of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1014

### CODE REVIEW

**Comment by mwjames** [comment]
Quick check on github, refs #2737:

```
SMWQueryProcessor::processFunctionParams -> Use getComponentsFromFunctionParams which has a cleaner interface.

    SemanticComments – CE_CommentParserFunctions.php
    SemanticCompoundQueries – CompoundQueryProcessor.php
```
```
SMWQueryProcessor:: getResultFromFunctionParams -> vanish after release of SMW 1.8., -> Use getQueryAndParamsFromFunctionParams

    SemanticFormsSelect – ApiRequestProcessor.php
    SemanticFormsSelect – SemanticFormsSelect.php
```
```
SMWQueryProcessor:: getResultFromQueryString -> vanish after release of SMW 1.8, use ->createQuery and -> getResultFromQuery

    SemanticResultFormats – SRF_SlideShowApi.php
    SemanticComments – CE_CommentParserFunctions.php
```

**Comment by kghbln** [comment]
So this would be breaking for the mentioned extensions. Should I open issues for them referencing this pull prior to merging this?

- SemanticComments
- SemanticCompoundQueries
- SemanticFormsSelect
- SemanticResultFormats

**Comment by JeroenDeDauw** [comment]
I suggest to remove these functions in SMW 3.1 instead so that the mentioned extensions are compatible with 3.0 even if they are not upgraded.

**Comment by JeroenDeDauw** [comment]
Left:

* [ ] processFunctionParams in https://github.com/SemanticMediaWiki/SemanticCompoundQueries/blob/master/src/CompoundQueryProcessor.php

Heh only one since SemanticComments is archived

**Comment by mwjames** [comment]
@kghbln Just to be on the safe side, this needs a section in the release notes.

**Pull request merged**
