### PR TITLE
Fix property description sublanguage

### PR DESCRIPTION
**Pull request by thomas-topway-it**
fixes https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5342

Implements:

> Edge-Cases (only if the definition does not match)
> 
> If there is a definition in de-xxx and the wiki is in de, use the de-xxx
> if there is a definition in de and the wiki is in de-xxx, use de

provides a "languagesFallbackInverse" map, with a list of dialects/formal languages for each main language.
Uses standard MW method `MediaWikiServices::getInstance()->getLanguageFallback()->getFirst()` for language fallback

## Summary by CodeRabbit

- **New Features**
  - Enhanced language fallback handling for property specifications.

### CODE REVIEW

**Comment by jaideraf** [comment]
@JeroenDeDauw this can be merged?

**Comment by JeroenDeDauw** [comment]
Design wise, the new code looks like it should be in a dedicated class.

Safety wise I see there are no automated tests. I don't trust myself or anyone else to catch all bugs just by looking at 300 lines of code. 

@jaideraf did you test this PR? Does it fix the issue? Does the related functionality still work as expected?

**Comment by thomas-topway-it** [comment]
the code has been tested, however I will try to add a test

**Comment by thomas-topway-it** [comment]
the code has been tested, however I will try to add a test

**Comment by JeroenDeDauw** [comment]
@thomas-topway-it refactor and test would still be great!

**Comment by thomas-topway-it** [comment]
I'm working on that, I'm sorry for the delay

**Comment by thomas-topway-it** [comment]
@JeroenDeDauw I've added the test `testTryOutFalldownAndInverse`, now I have to refactor placing it in a separate class as suggested (the `tryOutFalldownAndInverse` method must be also public) -- I needed some time to understand more in depth how tests work

**Comment by thomas-topway-it** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5690

**Pull request merged**
