### PR TITLE
List format: Fix xss vulnerability

### PR DESCRIPTION
**Pull request by s7eph4n**
F'up #3182

This PR is made in reference to: #3182

This PR addresses or contains:
- List format: Fix xss vulnerability

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
htmlspecialchars is for in the body of tags, not attribute values or in the opening tag itself.

This string is not affected by htmlspecialchars, so the XSS is still there

> onclick='alert(\'XSS\')'

This code also violates the practice of escaping directly in the HTML building code. Perhaps that is OK, but then some XSS specific tests are definitely in order.

**Comment by s7eph4n** [comment]
> htmlspecialchars is for in the body of tags, not attribute values or in the opening tag itself.

Do you have a link to read up on that? Judging from the existence of the [ENT_QUOTES and ENT_COMPAT flags](https://secure.php.net/manual/en/function.htmlspecialchars.php) I would assume that it is intended to be used also for attribute values. WMF devs [seem to agree](https://github.com/wikimedia/mediawiki/blob/master/includes/parser/Sanitizer.php#L1130).

> This string is not affected by htmlspecialchars, so the XSS is still there

Could you explain? How exactly would you inject the JS code here so that it becomes active?

> This code also violates the practice of escaping directly in the HTML building code.

I am not sure what you mean. How should the code be changed so that it escapes directly in the HTML building code (without spreading the html code chunks all over the place instead of keeping them defined in one place)?

**Comment by JeroenDeDauw** [comment]
> Do you have a link to read up on that? Judging from the existence of the ENT_QUOTES and ENT_COMPAT flags I would assume that it is intended to be used also for attribute values. WMF devs seem to agree.

No, just my memory. The last time that I build HTML like this was long ago, so perhaps I misremember.

> Could you explain? How exactly would you inject the JS code here so that it becomes active?

Something like this? https://3v4l.org/l8FYr

**Comment by JeroenDeDauw** [comment]
Merging as this is already more secure

**Comment by mwjames** [comment]
On the topic of tests and XSS, see [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0704.json

**Pull request merged**
