### PR TITLE
ArticleDelete to restrict pool of properties in update dispatcher, refs 2453

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2453

This PR addresses or contains:

- Only use the incoming properties to restrict the list of potential referenced entities that require an update after a subject has been deleted.

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln I cannot really quantify the impact in light of the #2453 comments but the list of follow-up `UpdateJob` should be less.

**Comment by kghbln** [comment]
> @kghbln I cannot really quantify the impact in light of the #2453 comments but the list of follow-up UpdateJob should be less.

I will have a look once in a while. I usually only see this en passant since my cron does the jobs round the clock. However in comparison to Wikia I only deal with homeopathic numbers. I think having a smaller number is good.

**Comment by TK-999** [comment]
@mwjames , thank you very much! I will communicate this and will get back in touch once we've reapplied it. :)

**Comment by mwjames** [comment]
Back-ported to 2.5.x with 3b6e30d.

**Pull request merged**
