### PR TITLE
Add `smw_countmap` field, refs 4611

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #4611

This PR addresses or contains:

- Part of the technical tweaks for #4611
- Adds `smw_countmap` as extra field to the `smw_object_aux` (#4227) table which stores a map of counts of properties and categories used per entity
- It allows to prefetch that information for a list of entities without having to lookup each single property table to match the entity which means that for a list of 500 result matches we only require one SQL query to know which properties (and categories) are used on all 500 entities (including they amount of values assigned to each property)
-  Information is stored in a simple blob field type since we don't want query the information in the field (that information is stored separately), we only want to fetch the entire content at once to build an aggregation map
- Changes `smwgUpgradeKey` to `smw:2020-02-29`
- `updateEntityCountMap.php` script is provided to update the field information 

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

## Example

A count map per entity will look similar to something like the following example.

```json
{
	"Has_Url": 1,
	"Has_annotation_uri": 1,
	"Has_area": 1,
	"Has_boolean": 1,
	"Has_date": 1,
	"Has_email": 1,
	"Has_number": 1,
	"Has_page": 3,
	"Has_record": 1,
	"Has_status": 1,
	"Has_telephone_number": 1,
	"Has_temperature": 1,
	"Has_wattage": 3,
	"_ERRC": 1,
	"_INST": {
		"Sample_pages": 1,
		"Lorem_ipsum": 1
	},
	"_MDAT": 1,
	"_SKEY": 1,
	"_SOBJ": 1
}
```

### CODE REVIEW

**Comment by mwjames** [comment]
Of the first occasion where the field was added to the table, an incomplete task is registered reminding an administrator to do something.

image
image

**Comment by kghbln** [comment]
Doku:
* [maintenance script "updateEntityCountMap.php"](https://www.semantic-mediawiki.org/wiki/Help:Maintenance_script_updateEntityCountMap.php)
* [field "smw_countmap"](https://www.semantic-mediawiki.org/wiki/Field:smw_countmap)

**Comment by kghbln** [comment]
@mwjames I documented the scrip similarily to the "populateHashField.php" when it comes to them manipulating the ".smw.json" file. However if I look at sandbox's file is see neither of the expected entries. Did the way the completion is being checked change in the meantime?

**Comment by mwjames** [comment]
> Did the way the completion is being checked change in the meantime?

The incomplete task/name are tied to a message key  [0,1] which avoids that the `SetupFile` [2] has to have any specific knowledge about any task. The leftover of line 300 to 315 should be removed from `SetupFile` at once point. Once a task is completed it is removed which signals to the `SetupFile` that there are no incomplete tasks.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/maintenance/populateHashField.php#L85-L92
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/maintenance/updateEntityCountMap.php#L30-L33
[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/src/SetupFile.php#L291-L328

Eventually

**Comment by kghbln** [comment]
Thanks for the info. I adapted the docu.

**Pull request merged**
