### PR TITLE
Add MaintenanceLogger, refs #832

### PR DESCRIPTION
**Pull request by mwjames**
image

refs #832

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln Currently outputs what is normally seen when using `--report-runtime`, feel free to add whatever information you want to have logged.

**Comment by kghbln** [comment]
Wow, that's great already. Probably 'maintenance' should be localizable and changed to 'data maintenance script' or perhaps even better 'is a software script that performed data maintenance for Semantic MediaWiki' to have it fit into the general mw log message scheme. Is this the "logentry-smw-maintenance" system message piping into this position though I do not really see where it is used.

What does the $1 mean in "log-show-hide-smw"? I'd say that this is the show/hide for selecting this log to be shown or not.

I could not have made something like this possible since I just did not have enough exposure time to php I'm afraid.

**Comment by mwjames** [comment]
> Probably 'maintenance' should be localizable and changed to 'data maintenance script' or perhaps even better 'is a software script that performed data maintenance for Semantic MediaWiki'

'maintenance' (could be "maintenance-script" in case this fits better) is an event type correlating with the recommendation found in [0]. 

```
{
	"log-name-foo": "Foo log",
	"log-description-foo": "These events track when Foo events happen in the system.",
	"logentry-foo-bar": "$1 {{GENDER:$2|did bar}} to page $3"
}
```

[1] sets the type which could be anything (non localized) and is only bound to the `MaintenanceLogger`.

>  What does the $1 mean in "log-show-hide-smw"? I'd say that this is the show/hide for selecting this log to be shown or not.
 
Relates to `wgFilterLogTypes` and here I'm just following [2].

> I could not have made something like this possible since I just did not have enough exposure time to php I'm afraid.

This I understand hence the helping hand. Most maintenance scripts had been re-factored before allowing us to add something without making the code worse.

MediaWiki dependency is isolated to the `ManualEntryLogger` and the `MaintenanceLogger` is a wrapper reducing the interface and some noise by keeping `ManualEntryLogger` from directly interacting with other parts of the code so that we now simply do:

```php
if ( $this->hasOption( 'with-log' ) ) {
	$maintenanceLogger = $maintenanceFactory->newMaintenanceLogger( 'RebuildConceptCache' );
	$maintenanceLogger->log( $maintenanceHelper->transformRuntimeValuesForOutput() );
}
```

[0] https://www.mediawiki.org/wiki/Manual:Logging_to_Special:Log

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1361/files#diff-160abe824e4fea8250d6af4f4857896eR34

[2] https://github.com/wikimedia/mediawiki/blob/master/languages/i18n/en.json#L2731-L2732

**Comment by kghbln** [comment]
First I have to apologize fro having kept you waiting so long.

Admittedly I do not know how to transform the linked instructions on the mw help page into usable code. Even after two hours I have no idea what to make out of these instructions. Currently the system messages "log-show-hide-smw" and "logentry-smw-maintenance" are dead code.

Is it just a matter of replacing 'maintenance' by the system message "logentry-smw-maintenance"? so we get:

"17:49, 5 February 2016 RebuildData (Talk | block) Maintenance related events emitted by Semantic MediaWiki (Memory used: 32060080 (b: 17812552, a: 49872632) with a runtime of 47.34 sec)"

instead of currently:

"17:49, 5 February 2016 RebuildData (Talk | block) maintenance (Memory used: 32060080 (b: 17812552, a: 49872632) with a runtime of 47.34 sec)"

Another thing that should probably be done is that the users "RebuildData" and "RebuildConceptCache" cannot be registered to avoid piggybacking, but this is an extra. The [NewUserMessage](https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FNewUserMessage/master/NewUserMessage.class.php) extension does this. Perhaps this is useful code.

**Comment by mwjames** [comment]
Example usage:

* `php maintenance/rebuildPropertyStatistics.php --with-maintenance-log`
* `php maintenance/rebuildData.php --with-maintenance-log`
* `php maintenance/rebuildConceptCache.php --with-maintenance-log`

**Comment by mwjames** [comment]
@kghbln `log-show-hide-smw` follows the same pattern as in [0].

[0] https://github.com/wikimedia/mediawiki/blob/master/languages/i18n/en.json#L2829-L2830

**Comment by kghbln** [comment]
@mwjames [This is really cool!](http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AJournal&type=smw&user=&page=&year=&month=-1&tagfilter=&hide_thanks_log=1&hide_patrol_log=1&hide_tag_log=1&hide_smw_log=1)

**Pull request merged**
