### PR TITLE
Update testing environment for SMW 3.1.0

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #3918 

This PR addresses or contains:
- Update testing environment for SMW 3.1.0

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames Let's see what happens.

**Comment by JeroenDeDauw** [comment]
+1

**Comment by mwjames** [comment]
So, here whats happening for https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/555127949, you got:
-  Failed 12634.8
 PHP: 7.3
 DB=sqlite; MW=REL1_33; PHPUNIT=6.5.*
 1 min 55 sec
- Failed  12634.4
 PHP: 7
 DB=sqlite; MW=REL1_31; SITELANG=ja; PHPUNIT=5.7.*
 11 min 26 sec
- Failed  12634.3
 PHP: 7
 DB=mysql; MW=REL1_31; VIRTUOSO=6.1; PHPUNIT=5.7.*
 7 min 48 sec

> Failed 12634.8

Has been fixed with #4136 

> Failed  12634.4

Includes 27 failures.

For `SITELANG=ja;`, some MW services remain stall even though we set a different `ContentLanguage` this wasn't an issue with MW 1.27 but since the Parser and other services rely on the MediaWikiService wiring some of them are not reset causing the use the wgLanguage setting (aka sitelanguage). Currently, I have no quick fix (or time) to find out which of those services interfere with the output generation.

> Failed  12634.3

Related to `VIRTUOSO=6.1`, skipping tests in `f-0306` for `virtuoso`.

**Comment by kghbln** [comment]
> SITELANG=ja;

What about making this an allowed failure? I know that this is not a nice idea but ...

**Comment by mwjames** [comment]
> What about making this an allowed failure? I know that this is not a nice idea but ...
> Currently, I have no quick fix (or time) to find out which of those services interfere with the output generation.

The issue remains (as outlined above) but #4145 is skipping those tests now.

**Comment by kghbln** [comment]
> The issue remains (as outlined above) but #4145 is skipping those tests now.

I think we should create a dedicated issue for this.

**Pull request merged**
