### PR TITLE
JSONScriptTestCaseRunner: Remove unneeded definition of testDatabaseTableBuilder var

### PR DESCRIPTION
**Pull request by paladox**
It's already defined in SMWIntegrationTestCase

## Summary by CodeRabbit

- **Bug Fixes**
	- Removed deprecated property to streamline test case execution.
  
- **New Features**
	- Introduced a new preferred method for page creation, enhancing flexibility in testing.

### CODE REVIEW

**Comment by paladox** [comment]
Not sure if this will fix https://github.com/SemanticMediaWiki/SemanticDrilldown/pull/85. But this is already defined in the class it's extending. We don't want to overwrite it by defining it in JSONScriptTestCaseRunner as well.

**Comment by paladox** [comment]
Ahhh

doing something like:

```
<?php

class test {
    protected $test = 'test';
}

class test2 extends test {
    protected $test;

    public function getProtectedProperty(){
        return $this->test;
    }

}

$testCase = new test2();
echo $testCase->getProtectedProperty();
```

shows that the protected var from the first class gets overwritten. So instead of 'test' nothing returns.

**Comment by gesinn-it-ilm** [comment]
@paladox good point. Yes, that var is unneeded there. Not sure if this update will affect the MW 1.42 for SemanticDrilldown in a proper way, but let's see.

**Review by gesinn-it-ilm — APPROVED** [review]

**Comment by paladox** [comment]
Nope that didn't fix it for Drilldown :(

**Pull request merged**
