### PR TITLE
Added PHP 7.1 to TravisCI

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by mwjames** [comment]
This looks awful, especially the "Segmentation fault" (and we do pass on 7.0.x).

```
Using PHP 7.1.0alpha3
Semantic MediaWiki: 2.5.0-alpha (SMWSQLStore3, sqlite)
MediaWiki:          1.28.0-alpha (Extension vendor autoloader)
Site language:      en
Execution time:     2016-07-12 06:58
Xdebug:             Disabled (or not installed)

Runtime:	PHP 7.1.0alpha3
Configuration:	/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/phpunit.xml.dist
..E.E....E...................................................   61 / 3696 (  1%)
.............................................................  122 / 3696 (  3%)
..............................................
Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
PHP Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
PHP Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
PHP Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
PHP Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
PHP Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
Warning: Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
PHP Warning:  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195
...............  183 / 3696 (  4%)
.............................................................  244 / 3696 (  6%)
.............................................................  305 / 3696 (  8%)
.............................................................  366 / 3696 (  9%)
.......................S.....................................  427 / 3696 ( 11%)
.............................................................  488 / 3696 ( 13%)
.............................................................  549 / 3696 ( 14%)
.............................................................  610 / 3696 ( 16%)
....E........................................................  671 / 3696 ( 18%)
.............................................................  732 / 3696 ( 19%)
.............................................................  793 / 3696 ( 21%)
.............................................................  854 / 3696 ( 23%)
.............................................................  915 / 3696 ( 24%)
.............................................................  976 / 3696 ( 26%)
............................................................. 1037 / 3696 ( 28%)
.....................................................E....... 1098 / 3696 ( 29%)
............................................................. 1159 / 3696 ( 31%)
............................................................. 1220 / 3696 ( 33%)
............................................................. 1281 / 3696 ( 34%)
............................................................. 1342 / 3696 ( 36%)
............................................................. 1403 / 3696 ( 37%)
............................................................. 1464 / 3696 ( 39%)
..........EE................................................. 1525 / 3696 ( 41%)
............E................................................ 1586 / 3696 ( 42%)
............................................................. 1647 / 3696 ( 44%)
............................................................. 1708 / 3696 ( 46%)
............................................................. 1769 / 3696 ( 47%)
.......................................................E..... 1830 / 3696 ( 49%)
...........................EEEEEEEE.......E...E.EEEEEEE....Segmentation fault (core dumped)
```

**Comment by JeroenDeDauw** [comment]
Did not realize I changed one of the builds that is allowed to fail. @mwjames can you perhaps add a comment explaining the reason for allowing failure to each?

**Comment by mwjames** [comment]
>  Parameter 1 to SMW\MediaWiki\Hooks\HookRegistry::SMW\MediaWiki\Hooks\{closure}() expected to be a reference, value given in /home/travis/build/SemanticMediaWiki/mw/includes/Hooks.php on line 195

I did some digging (shh...) and something (and I mean not SMW) is broken starting with with 7.1.0alpha2.

https://3v4l.org/vMc1N demonstrates the issue in the MW's Hooks class (copied the class to a minimum).

### Issue
```
Output for 7.1.0alpha2 - 7.1.0alpha3
Warning: Parameter 1 to {closure}() expected to be a reference, value given in /in/vMc1N on line 51
Foo: 
123
Foo2: 
123-bar
```
```
Output for 5.3.0 - 5.6.23, hhvm-3.9.1 - 3.12.0, 7.0.0 - 7.1.0alpha1
Foo: 
123-bar
Foo2: 
123-bar
```

### Cause
 It is caused by using a direct `&$this` parameter in the callback as parameter. (maybe related to https://github.com/php/php-src/commit/a9512af8109e889eb2c6042c57797184930667cd).

```
//Stub class using &$this as direct reference
class Foo {
    
    public function doSomething( $var ) {
        Hooks::run( 'foo', array( &$this, &$var ) );
        return $var;
    }
    
}

// Stub class causes no error after $this is being redeclared
class Foo2 {
    
    public function doSomething( $var ) {
        $foo = $this;

        Hooks::run( 'foo', array( &$foo, &$var ) );
        return $var;
    }
    
}
```
### Solution
I don't have the time follow-up with either MW or PHP, so someone interested in getting this resolved should take the lead.

@legoktm FYI

**Comment by mwjames** [comment]
The response from https://bugs.php.net/bug.php?id=73751 is:

>This change is caused by https://wiki.php.net/rfc/this_var, which no longer allows taking a reference to $this (instead, you will get a value).
>We changed call_user_func_array() in 7.1 to still perform the call (even though a warning is emitted) to make sure this and similar discrepancies do not cause BC breaks beyond additional warnings.

Tracked in https://phabricator.wikimedia.org/T153505

**Comment by mwjames** [comment]
```
Using PHP 7.1.0

Semantic MediaWiki: 2.5.0-alpha (SMWSQLStore3, mysql)
MediaWiki:          1.29.0-alpha (Extension vendor autoloader)
Site language:      en

Execution time:     2017-02-19 01:31
Debug logs:         Disabled
Xdebug:             2.5.0 (enabled)

PHP Deprecated:  Function mcrypt_create_iv() is deprecated in /home/travis/build/SemanticMediaWiki/mw/includes/libs/CryptRand.php on line 254
PHP Stack trace:
```
https://phabricator.wikimedia.org/T143788
https://s3.amazonaws.com/archive.travis-ci.org/jobs/203149178/log.txt

**Comment by JeroenDeDauw** [comment]
Any bets on if we will hit the one year mark on this one? >_>

**Comment by mwjames** [comment]
> Any bets on if we will hit the one year mark on this one? >_>

Actually, the test suite passes except for:

```
Using PHP 7.1.3

Semantic MediaWiki: 3.0.0-alpha (SMWSQLStore3, mysql)
MediaWiki:          1.29.0-alpha (Extension vendor autoloader)
Site language:      en

Execution time:     2017-04-20 06:32
Debug logs:         Disabled
Xdebug:             2.5.0 (enabled)

PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

Runtime:	PHP 7.1.3 with Xdebug 2.5.0


FAILURES!
Tests: 4723, Assertions: 14211, Failures: 3, Skipped: 14.

There were 3 failures:

1) SMW\Tests\Integration\MediaWiki\LinksUpdateTest::testDoUpdateUsingNoAnnotations
Failed asserting that actual size 3 matches expected size 0.

/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/MediaWiki/LinksUpdateTest.php:171
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/MwDBaseUnitTestCase.php:125
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:111

2) SMW\Tests\Integration\MediaWiki\Import\RedirectPageTest::testPageImportToCreateRedirect
SMW\Tests\Utils\Validators\SemanticDataValidator::assertContainsPropertyValues for '_INST' as '__sin' with (Regression test, Redirect test, Simple redirect test)
Failed asserting that an array contains 'Lorem ipsum'.

/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:378
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:290
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:77
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/MediaWiki/Import/RedirectPageTest.php:151
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/MediaWiki/Import/RedirectPageTest.php:120
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/MwDBaseUnitTestCase.php:125
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:111

3) SMW\Tests\Integration\MediaWiki\Import\TimeDataTypeTest::testImportOfDifferentDateWithAssortmentOfOutputConversion
SMW\Tests\Utils\Validators\SemanticDataValidator::assertContainsPropertyValues for '_INST' as '__sin' with (Regression test)
Failed asserting that an array contains 'Lorem ipsum'.

/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:378
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:290
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/Validators/SemanticDataValidator.php:77
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/MediaWiki/Import/TimeDataTypeTest.php:207
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/MwDBaseUnitTestCase.php:125
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:111
```

Failures are related to MW-master (or appeared with MW 1.28), I added some comments in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2278#issuecomment-282474485.

PS: Only MW-master (1.29) is compatible with PHP 7.1 due to https://phabricator.wikimedia.org/T143788 and https://phabricator.wikimedia.org/T153505.

**Comment by JeroenDeDauw** [comment]
\o/

**Pull request merged**
