### PR TITLE
Have smwdoc show special message for debug and count formats

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Fixes https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3186

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@kghbln will need manual verification as I can't easily write a test for this

**Comment by JeroenDeDauw** [comment]
@mwjames I'd like to write an integration test for this that takes the wikitext and returns some output, kinda like https://github.com/JeroenDeDauw/Maps/blob/master/tests/Integration/Parser/DisplayMapTest.php. Can you give me a pointer of what the best way to do that for SMW stuff is currently?

**Comment by mwjames** [comment]
> https://github.com/JeroenDeDauw/Maps/blob/master/tests/Integration/Parser/DisplayMapTest.php.

Using just `new \Parser` can create of a lot of surprises especially
when you have different language settings to care for. Testing the
output as part of an embedding page will be different from a plain
`\Parser` call therefore the `JSONScript` in SMW takes care of it and
keeps away the headaches.

> Can you give me a pointer of what the best way to do that for SMW stuff is
> currently?

A simple `smwdoc` test can be found at [0], for details see [1].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0107.json
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/JSONScript#designing-an-integration-test

> src/ParserFunctions/DocumentationParserFunction.php (38)

A quick look reveals that the `DocumentationParserFunction` now
contains format specific aspects and I would go for a different
approach such as:

```
-		'count'      => 'SMW\Query\ResultPrinters\ListResultPrinter',
-		'debug'      => 'SMW\Query\ResultPrinters\ListResultPrinter',
+		'count'      => 'SMW\Query\ResultPrinters\NullResultPrinter',
+		'debug'      => 'SMW\Query\ResultPrinters\NullResultPrinter',
```

```
@@ -590,17 +590,21 @@ class SMWQueryProcessor implements QueryContext {
 	 * @return ParamDefinition[]
 	 */
 	public static function getFormatParameters( $format ) {
 		SMWParamFormat::resolveFormatAliases( $format );

-		if ( array_key_exists( $format, $GLOBALS['smwgResultFormats'] ) ) {
-			$resultPrinter = self::getResultPrinter( $format );
+		if ( !array_key_exists( $format, $GLOBALS['smwgResultFormats'] ) ) {
+			return [];
+		}

-			return ParamDefinition::getCleanDefinitions(
-				$resultPrinter->getParamDefinitions( self::getParameters( null,
$resultPrinter ) )
-			);
-		} else {
-			return array();
+		$resultPrinter = self::getResultPrinter( $format );
+
+		if ( $resultPrinter instanceof
\SMW\Query\ResultPrinters\NullResultPrinter ) {
+			return [];
 		}
+
+		return ParamDefinition::getCleanDefinitions(
+			$resultPrinter->getParamDefinitions( self::getParameters( null,
$resultPrinter ) )
+		);
 	}
```

```
@@ -80,19 +80,11 @@ class DocumentationParserFunction implements HookHandler {
 	 * @param string $format
 	 *
 	 * @return ParamDefinition[]
 	 */
 	private function getFormatParameters( $format ) {
-		if ( !array_key_exists( $format, $GLOBALS['smwgResultFormats'] ) ) {
-			return array();
-		}
-
-		$resultPrinter = SMWQueryProcessor::getResultPrinter( $format );
-
-		return ParamDefinition::getCleanDefinitions(
-			$resultPrinter->getParamDefinitions(
SMWQueryProcessor::getParameters( null, $resultPrinter ) )
-		);
+		return SMWQueryProcessor::getFormatParameters( $format );
 	}
```

```
+class NullResultPrinter extends ResultPrinter {
+
+	/**
+	 * @see ResultPrinter::getName
+	 *
+	 * {@inheritDoc}
+	 */
+	public function getName() {
+		return 'null';
+	}
+
+	/**
+	 * @see ResultPrinter::getResultText
+	 *
+	 * {@inheritDoc}
+	 */
+	protected function getResultText( QueryResult $queryResult, $outputMode ) {
+		return '';
+	}
+
+}
```

Cheers

**Comment by kghbln** [comment]
I was not sure if this one is stalled or so. Thus I expanded the test cases file. Let's see what happens. I a second step I will add James' code suggestions since it appears that Jeroen is ok with them.

**Comment by mwjames** [comment]
> @kghbln pushed 1 commit.
>
> 5b0ea8e  Update p-0107.json

Nice follow up.

A small issue with "#1 (#1019)" (this one should be called #2 list ...
since you have two #1 making the error handling a bit more difficult)
on:

```
==== (expected) ====
[ <td>Text ], [ <td><i>leer</i> ]
```

but actually outputs:

```
==== (actual) ====
<table class="wikitable sortable">
<tr>
<th>â§¼validator-describe-header-parameterâ§½
</th>
<th>â§¼validator-describe-header-typeâ§½
</th>
<th>â§¼validator-describe-header-defaultâ§½
</th>
<th>â§¼validator-describe-header-descriptionâ§½
</th></tr>
...
```

> file. Let's see what happens. I a second step I will add James' code
> suggestions since it appears that Jeroen is ok with them.

Don't worry about this, I'll do this during a sprint (I put a note on
my list). So, once the test suite passes, feel free to merge.

Cheers

**Comment by kghbln** [comment]
> A small issue with "#1 (#1019)" (this one should be called #2 list ... since you have two #1 making the error handling a bit more difficult) on:

Indeed, that's what happens if you copy paste. Ah, I was not really expecting ⧼validator-type-string⧽.

> Don't worry about this, I'll do this during a sprint (I put a note on my list). So, once the test suite passes, feel free to merge. 

Ok, will do.

**Comment by kghbln** [comment]
Do we have an either or situation. Pass PHPUnit 4.8 or 5.7 or something to avoid this decision making ... but making PHP 5.7 an allowed failure until we move on to this version?

**Comment by mwjames** [comment]
> Do we have an either or situation. Pass PHPUnit 4.8 or 5.7 or something to
> avoid this decision making ... but making PHP 5.7 an allowed failure until
> we move on to this version?

It is the MW version that causes the failure as explained in an earlier comment.

**Comment by kghbln** [comment]
> Do we have an either or situation. Pass PHPUnit 4.8 or 5.7 or something to avoid this decision making ... by making PHP 5.7 an allowed failure until we move on to this version?

No, I will just remove these lines from the test. I guess this is the most pragmatic approach since we still can verify that the expected line is appearing.

**Comment by kghbln** [comment]
> It is the MW version that causes the failure as explained in an earlier comment.

I think I did not really understand it before ... :| Now I do ...

**Comment by mwjames** [comment]
> I think I did not really understand it before ... :| Now I do ...

My comment went into the garbage collector somehow and included:

"Best avoid `⧼` vs. `&lt;` (aka <) as far as I remember missing
language keys changed the indicator form from `<` to `⧼` in some MW
release."

**Pull request merged**
