### PR TITLE
Use top navigation in JSONView, refs 3673

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #3673

This PR addresses or contains:

- Moving the interaction buttons into a top navigation

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

## Before

image

## After

image

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames This only seems to work in some places

**works**
- [property groups](https://sandbox.semantic-mediawiki.org/wiki/smw/schema:Group:Exif_special_properties)
- [profiles](https://sandbox.semantic-mediawiki.org/wiki/smw/schema:Search-profile-form-definition)

**does not work**
- [Property constraints](https://sandbox.semantic-mediawiki.org/wiki/smw/schema:Constraint:NonNegativeInteger)
- [Formatters](https://sandbox.semantic-mediawiki.org/wiki/smw/schema:Keyword_link_formatter)

**Comment by mwjames** [comment]
> @mwjames This only seems to work in some places

> does not work    Property constraints

This needs an extra HTML element and when the page is cached (parser cache) this is missing which is why a purge will fix this as in case of [0].

[0] https://sandbox.semantic-mediawiki.org/wiki/smw/schema:Constraint:NonNegativeInteger

**Comment by kghbln** [comment]
Ok, cool. I am pretty sure that I purged the page before writing all of this. Probably I only did an F5 in the browser instead of a Ctrl + F5.

**Comment by mwjames** [comment]
> Probably I only did an F5 in the browser instead of a Ctrl + F5.

Isn't enough as we need to purge the parser cache to create a new HTML output.

**Pull request merged**
