### PR TITLE
Create SMW_LanguageHu.php

### PR DESCRIPTION
**Pull request by hangya**
Hungarian translation

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks a lot!

**Comment by kghbln** [comment]
Thanks a ton! Do not forget [SMW_Aliases.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/languages/SMW_Aliases.php) and [SMW_Magic.php](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/languages/SMW_Magic.php) though the latter may very well be broken. Still ...

**Comment by JeroenDeDauw** [comment]
> though the latter may very well be broken.

What?? Do we have an issue for that?

**Comment by kghbln** [comment]
> What?? Do we have an issue for that?

Oops, just tested this and the localized parserfunctions and behaviour switches indeed do work. This was not the case last time I tested this with presumably SMW 1.5.2 or so. Great, so @hangya go for the localization! Thanks!

**Comment by JeroenDeDauw** [comment]
> SMW 1.5.2

2010 called, it wants its SMW version back!

**Pull request merged**
