### PR TITLE
Datatable to support ad-hoc (JSON,CSV ...) export, refs

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2420

This PR addresses or contains:

- Adds JSON, CSV, RSS, and RDF as export option directly to the output

image

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI, Needs a bit of testing once merged!

**Comment by kghbln** [comment]
https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/2718

Very cool! So far additional field tests showed that  the results were as expected. I think however that it needs a bit of tweaking for narrow screens / mobile devices.

grafik

**Comment by kghbln** [comment]
PS I believe to know [from where](https://sandbox.semantic-mediawiki.org/wiki/Books) you go this idea. :)

**Comment by mwjames** [comment]
> I think however that it needs a bit of tweaking for narrow screens / mobile devices.

Yes, but those are CSS only and specific to a screen maybe using `flex...` or so could be a solution. It is a bit of work to find the right soluton for small screens (e.g `@media screen and (max-width: 420px)` etc.) but related files are:

*  https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/smw/ext.smw.dropdown.css
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/res/smw/printer/ext.smw.tableprinter.css

[0] https://www.w3schools.com/css/css_rwd_intro.asp
[1] http://www.tutorialspoint.com/css/css_responsive.htm

**Comment by kghbln** [comment]
I put this on my list. Hopefull I will not forget so poke in case ...

**Comment by krabina** [comment]
documented at https://www.semantic-mediawiki.org/wiki/Help:Table_format and https://www.semantic-mediawiki.org/wiki/Demo:Table_formats_compared

**Pull request merged**
