### PR TITLE
jquery.hoverIntent is being removed from core of mediawiki

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by mwjames** [comment]
> 	jquery.hoverIntent is being removed from core of mediawiki

For which release? If you use the same resource identifier `jquery.hoverIntent` it will probably clash with those defined in some MW release before the removal (we still support MW 1.19).

The more fundamental question is why does SMW need the  `jquery.hoverIntent` resource, I can't recall any SMW-core function that makes direct use of it.

**Comment by paladox** [comment]
Someone says there is please visit https://gerrit.wikimedia.org/r/#/c/184140/ comment 4.

**Comment by mwjames** [comment]
Our tests actual catch the issue mentioned above: 
```
1) Warning
The data provider specified for SMW\Tests\System\ResourcesAccessibilityTest::testModulesScriptsFilesAreAccessible is invalid.
ResourceLoader duplicate registration error. Another module has already been registered as jquery.hoverIntent
/home/travis/build/SemanticMediaWiki/mw/tests/phpunit/MediaWikiPHPUnitCommand.php:80
/home/travis/build/SemanticMediaWiki/mw/tests/phpunit/MediaWikiPHPUnitCommand.php:64
2) Warning
The data provider specified for SMW\Tests\System\ResourcesAccessibilityTest::testModulesStylesFilesAreAccessible is invalid.
ResourceLoader duplicate registration error. Another module has already been registered as jquery.hoverIntent
```

@JeroenDeDauw Sometimes you gotta love our tests.

**Comment by mwjames** [comment]
I'm pretty sure we don't use this hence closing the issue with appreciation for the initial work from paladox.

**Pull request closed without merging**
