### PR TITLE
Use MW43 DBAL

### PR DESCRIPTION
**Pull request by osnard**

### CODE REVIEW

**Comment by krabina** [comment]
Great, thank you. This is a first attempt to get SMW working with 1.43 LTS

**Comment by gesinn-it-gea** [comment]
I'm not sure if changing all the individual calls to getConnection is the right approach. After the change, the DB is accessed directly without SMW's Store being involved. Wouldn't it be better to change the access logic somewhere in SMW's Store abstraction layer?

class SQLStore extends Store:
```
	public function getConnection( $type = 'mw.db' ) {
		return parent::getConnection( $type );
	}
```

abstract class Store implements QueryEngine
```
	public function getConnection( $type ) {
		if ( $this->connectionManager === null ) {
			$this->connectionManager = ApplicationFactory::getInstance()->getConnectionManager();
		}

		return $this->connectionManager->getConnection( $type );
	}
```

class ConnectionManager
```
	public function getConnection( $id = null ) {
		$id = strtolower( $id );

		if ( self::$isConnectable === null ) {
			self::$isConnectable = $this->isConnectable();
		}

		if ( isset( self::$connectionProviders[$id] ) ) {
			return self::$connectionProviders[$id]->getConnection();
		}

		throw new RuntimeException( "{$id} is not registered as connection provider" );
	}
```

class ConnectionProvider implements IConnectionProvider ...

**Comment by osnard** [comment]
Closing this in favor of https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5679

My change was only a quick test / draft. The other one is much more mature already. Doesn't make sense to keep this.

**Comment by squirrelslair** [comment]
It appears that this was closed in favour of [#5679](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5679), but that one was closed mentioning this one. 
I tried running composer and update after these were closed and was still getting the error. So, is this fixed?

**Comment by jaideraf** [comment]
@squirrelslair did you follow these steps? https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5634#issuecomment-2344458646

There is not a release yet asserting support for MediaWiki above 1.41. See: 
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Pull request closed without merging**
