### PR TITLE
Update RELEASE-NOTES-4.2.0.md

### PR DESCRIPTION
**Pull request by robinwiel**
Updated the release notes to mention these PRs and their contributors:
- #5631 
- #5633 

## Summary by CodeRabbit

- **New Features**
  - Introduced `Special:FacetedSearch` page for narrowing query results with faceted views.
  - Enabled the use of the "source" parameter in API-modules "ask" and "askargs" for setting query sources.

### CODE REVIEW

**Comment by jaideraf** [comment]
Maybe it should be noted that `Special:FacetedSearch` feature requires to run the MediaWiki `update.php` script (or the SMW `setup­Store.php`).

**Comment by JeroenDeDauw** [comment]
How so? This isn't obvious to me from looking at the PR

**Comment by JeroenDeDauw** [comment]
So that just affects the faceted search? In other words: update.php is only needed if you want to use the new faceted search

**Comment by jaideraf** [comment]
> So that just affects the faceted search? In other words: update.php is only needed if you want to use the new faceted search

Yes, that's right. If you go to `Special:FacetedSearch` without this page imported by `setup­Store.php`, you will get a error on that page.

**Comment by jaideraf** [comment]
Off course this error is only when you upgrade SMW without running setup­Store.php (or update.php). In a fresh install, everthing should be fine.

**Comment by robinwiel** [comment]
> So that just affects the faceted search? In other words: update.php is only needed if you want to use the new faceted search

Should I include that sentence in the release notes?

**Comment by kghbln** [comment]
I replaced this attempt with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5656 since it was not going forward.

**Comment by kghbln** [comment]
This happens if one does not run update.php or setupStore.php and try to access Special:FacetedSearch.

## Issue
```
[9b835b880c9888bf06cb0b2b] /wiki/Sp%C3%A9cial:FacetedSearch SMW\MediaWiki\Specials\FacetedSearch\Exception\DefaultProfileNotFoundException: The Faceted Search is missing a default profile! The default profile is expected to be imported but somehow it went missing. Please read the documentation and avoid using `--skip-import` during the setup!
```
## Backtrace:
```
from /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/FacetedSearch/Profile.php(140)
#0 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/FacetedSearch/Profile.php(88): SMW\MediaWiki\Specials\FacetedSearch\Profile->loadProfile()
#1 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/FacetedSearch/Profile.php(77): SMW\MediaWiki\Specials\FacetedSearch\Profile->getProfileList()
#2 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/FacetedSearch/HtmlBuilder.php(102): SMW\MediaWiki\Specials\FacetedSearch\Profile->getProfileCount()
#3 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialFacetedSearch.php(179): SMW\MediaWiki\Specials\FacetedSearch\HtmlBuilder->buildEmptyHTML()
#4 /../w/includes/specialpage/SpecialPage.php(701): SMW\MediaWiki\Specials\SpecialFacetedSearch->execute()
#5 /../w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#6 /../w/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#7 /../w/includes/MediaWiki.php(904): MediaWiki->performRequest()
#8 /../w/includes/MediaWiki.php(562): MediaWiki->main()
#9 /../w/index.php(50): MediaWiki->run()
#10 /../w/index.php(46): wfIndexMain()
#11 {main}
```
Moreover, if you have `$smwgImportReqVersion = false;` running either of the two scripts will not help the cause. Simply commenting out this configuration parameter will not help either. One needs to set `$smwgImportReqVersion = 2;` to trigger the import of the missing default profile.

**Pull request closed without merging**
