### PR TITLE
Improvements to DataRebuilder

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@mwjames I do not see any behaviour change... yet there must be one since the test fails now. Any idea?

**Comment by mwjames** [comment]
> yet there must be one since the test fails now. Any idea?

I haven't looked at it but according to the error a mock was expected to run but wasn't reached.

```
1) SMW\Tests\Maintenance\DataRebuilderTest::testRebuildSelectedPagesWithPageOption
Expectation failed for method name is equal to <string:makeTitleOf> when invoked at sequence index 0.
The expected invocation at index 0 was never reached.
```

**Comment by JeroenDeDauw** [comment]
Yeah I looked at the test failure already

**Comment by mwjames** [comment]
> Yeah I looked at the test failure already

`makeTitleOf` was made private hence the mock failed. `TitleCreator` is now injected which allows for proper mocking during `testRebuildSelectedPagesWithPageOption`.

**Pull request merged**
