### PR TITLE
Hopefully fix postgres issue #5287

### LINKED ISSUE #5287: Postgresql setup fails with Error: Call to undefined method Wikimedia\Rdbms\DatabasePostgres::onTransactionIdle()
### Setup

- SMW version: 4.0.2
- MW version: 1.38.2
- PHP version: PHP 7.4.30 (cli) (built: Jul  7 2022 15:51:43)
- DB system and version: PostgreSQL 13.7 (Debian 13.7-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Issue
I created the database and applied this:
```
CREATE EXTENSION IF NOT EXISTS citext;
ALTER DATABASE wiki_fsinf_at SET bytea_output = 'escape';
```
Then setting up a new mediawiki instance with smw fails. Using this command:
```
php maintenance/install.php Wiki Admin --pass=... --dbtype=postgres --dbschema=public --dbserver=... --dbname=... --dbuser=... --dbpass=...
mv LocalSettings.php.orig LocalSettings.php
php maintenance/update.php --quick
```

Will lead during the execution of ``php maintenance/update.php --quick;`` to this:

```
--- Post-creation examination ---------------------------------------------

Checking selected fixed properties IDs ...
   ... done.
Checking internal properties border ...
   ... space for internal properties allocated ...                        ✓
   ... done.
Checking predefined properties ...
   ... initialize predefined properties ...
   ... done.
Checking smw_hash field consistency ...
   ... updating the setup file key ...                                    ✓
   ... done.
Checking smw_sortkey, smw_sort fields ...
   ... done.
Checking smw_touched field ...
   ... done.
Checking smw_countmap field consistency ...                               ✓
   ... done.
Checking entity collation type ...                                        ✓
   ... done.
Checking `smw_id` sequence consistency ...
[56aab62775d239fe82fd93f2] [no req]   Error: Call to undefined method Wikimedia\Rdbms\DatabasePostgres::onTransactionIdle()
Backtrace:
from /var/www/[...]/includes/libs/rdbms/database/DBConnRef.php(69)
#0 /var/www/[...]/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Sequence.php(86): Wikimedia\Rdbms\DBConnRef->__call()
#1 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(488): SMW\MediaWiki\Connection\Sequence->restart()
#2 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/PostgresTableBuilder.php(474): SMW\SQLStore\TableBuilder\PostgresTableBuilder->doCheckOnPostCreation()
#3 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/TableBuilder/TableBuildExaminer.php(171): SMW\SQLStore\TableBuilder\PostgresTableBuilder->checkOn()
#4 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(239): SMW\SQLStore\TableBuilder\TableBuildExaminer->checkOnPostCreation()
#5 /var/www/[...]/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(451): SMW\SQLStore\Installer->install()
#6 /var/www/[...]/extensions/SemanticMediaWiki/src/Store.php(489): SMW\SQLStore\SQLStore->setup()
#7 /var/www/[...]/includes/installer/DatabaseUpdater.php(533): SMW\Store::setupStore()
#8 /var/www/[...]/includes/installer/DatabaseUpdater.php(501): DatabaseUpdater->runUpdates()
#9 /var/www/[...]/maintenance/update.php(193): DatabaseUpdater->doUpdates()
#10 /var/www/[...]/maintenance/doMaintenance.php(114): UpdateMediaWiki->execute()
#11 /var/www/[...]/maintenance/update.php(264): require_once(string)
#12 {main}

```

### PR DESCRIPTION
**Pull request by someone-somenet-org**
Since no one cared to fix this for more than a year, i did it by myself.

Seems to work but is not well tested or what do I know what QA steps you folks do.

Hopefully fixes #5287

### CODE REVIEW

**Comment by someone-somenet-org** [comment]
Is there any way to know what db engine is in use?

**Comment by JeroenDeDauw** [comment]
There is but I don't recall the details. You could try asking on MediaWiki IRC, mailing list or https://app.element.io/#/room/#mwstake-general:matrix.org

**Comment by someone-somenet-org** [comment]
I believe that the mysql tests are just broken - they fail for all PRs, even those that are not related to any database changes.

**Comment by someone-somenet-org** [comment]
Anyway - this change seems to work on mysql and seems to fix postgres.

**Comment by mdoggydog** [comment]
For others who have stumbled upon this pull request while trying to upgrade to MW 1.39, GitHub has a convenient trick: you can simply download  https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5518.patch to get the patch file for this pull request.  Then use `patch` to hot-patch your SMW source tree in your `extensions` directory.  Be careful to do it again on your next SMW upgrade if this has not been fixed "upstream" yet.

It's kind of ironic that some effort was put into the adapter class in `src/MediaWiki/Connection/Database.php` to detect and account for the name change.  Apparently that adapter class is not used consistently within the SMW codebase?  (This pull request here amusingly replaces `onTransactionIdle` with `onTransactionCommitOrIdle` in that file, too. :smiley: )

In any case, `onTransactionIdle()` is nowhere to be found in MW 1.39+.  It really seems about time to get rid of it in SMW.

**Comment by someone-somenet-org** [comment]
ping. Can any dev take a lok at this?

This bug has been open for more than a year now without **ANY** dev-action and it seems pretty trivial to me to fix.

**Comment by marijnvanwezel** [comment]
I also came across this when trying to work on #5451 (to make it also compatible with 8.10). The changes look good, so can this please be merged? @JeroenDeDauw 

We should add Postgres to the CI/CD pipeline to avoid these issues in the future.

**Pull request merged**
