### PR TITLE
Remove unused imports and fix type hints

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Failure looks unrelated

**Comment by mwjames** [comment]
> Failure looks unrelated

- Installing [mparam-processor/param-processor[ ([1.6.0): Downloading 

Something changed between yesterday and today to have the test fail.

```
There were 4 errors:
1) SMW\Test\ParameterListDocBuilderTest::testGivenMinimalParameter_defaultIsRequired
TypeError: Return value of ParamProcessor\ParamDefinition::getMessage() must be of the type string, null returned
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinition.php:233
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:90
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:40
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/ParameterListDocBuilderTest.php:50
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:94
2) SMW\Test\ParameterListDocBuilderTest::testGivenParameterWithDefault_defaultIsListed
TypeError: Return value of ParamProcessor\ParamDefinition::getMessage() must be of the type string, null returned
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinition.php:233
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:90
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:40
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/ParameterListDocBuilderTest.php:75
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:94
3) SMW\Test\ParameterListDocBuilderTest::testGivenParameterWithAliases_aliasesAreListed
TypeError: Return value of ParamProcessor\ParamDefinition::getMessage() must be of the type string, null returned
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinition.php:233
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:90
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:40
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/ParameterListDocBuilderTest.php:104
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:94
4) SMW\Test\ParameterListDocBuilderTest::testGivenBooleanParameter_defaultIsListedAsString
TypeError: Return value of ParamProcessor\ParamDefinition::getMessage() must be of the type string, null returned
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/param-processor/param-processor/src/ParamDefinition.php:233
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:90
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/ParameterListDocBuilder.php:40
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/ParameterListDocBuilderTest.php:135
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:94
```

**Comment by JeroenDeDauw** [comment]
Will fix that. Though that is caused by a change after I made the PR here.

**Comment by mwjames** [comment]
It still pulls in the 1.6.0 `ParamProcessor` version which is why tests are still failing. Maybe doing a force push will allow this to fetch the new version via Composer.

**Comment by JeroenDeDauw** [comment]
Eh. Seems like I need to update the GH hook on packagist. Prodded it manually now. So should be fluff now-ish or in a few min.

**Pull request merged**
