### PR TITLE
Added PHP 7.1 to TravisCI

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by mwjames** [comment]
See https://github.com/travis-ci/travis-ci/issues/6148

**Comment by mwjames** [comment]
Maybe `PHPUNIT=4.8.*` (5.* will most likely not work).

**Comment by JeroenDeDauw** [comment]
Ok, so not 7.1 yet :(

I don't understand what you are saying about PHPUnit. Why would we need an older version?

**Comment by mwjames** [comment]
> I don't understand what you are saying about PHPUnit. Why would we need an older version?

I think you have this backwards, by default 3.8.* would be installed and I suggested you use 4.8.* instead since running 5.4.* will break the job.

**Comment by JeroenDeDauw** [comment]
Oh, the default version of PHPUnit does not work with PHP 7?

**Comment by mwjames** [comment]
> Oh, the default version of PHPUnit does not work with PHP 7?

 As far as I recall, the mock objects went berserk the last time I tried PHPUnit 3.8* with SMW/MW/PHP 7.

**Pull request closed without merging**
