### PR TITLE
Fix warnings about undefined DB_SLAVE on mediawiki master

### LINKED ISSUE #4100: Warnings about DB_SLAVE not being defined
### Setup and configuration

(Dupe of #4093?)

- SMW version: master
- MW version: master
- PHP version: 7.3.6-1+0\~20190531112735.39+stretch~1.gbp6131b7 
- DB system and version: Percona XtraDB Cluster: mysql  Ver 14.14 Distrib 5.7.25-28, for debian-linux-gnu (x86_64) using  7.0

### Issue
When running MediaWiki's `maintenance/install.php`, the following warning is printed:
```
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP)
```

### Steps to reproduce
```
$ php maintenance/install.php  wiki adminp
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /home/mah/work/code/mediawiki/core/extensions/SemanticMediaWiki/DefaultSettings.php on line 163
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /home/mah/work/code/mediawiki/core/extensions/SemanticMediaWiki/DefaultSettings.php on line 167
You need to provide the option "pass" or "passfile"
```

### PR DESCRIPTION
**Pull request by hexmode**
This PR is made in reference to: #4100 

Fixes #4100

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Looks good

Did the constant get renamed in MW?

**Comment by hexmode** [comment]
> Did the constant get renamed in MW?

Yes, See #4093

**Comment by kghbln** [comment]
I am not so good a programming. The patch provides a compat shim for for MediaWiki earlier than MW 1.34? Anyways searching for `DB_SLAVE` [reveals many more occurences](https://github.com/SemanticMediaWiki/SemanticMediaWiki/search?q=DB_SLAVE&unscoped_q=DB_SLAVE)

**Comment by hexmode** [comment]
This provides a DB_SLAVE constant for SMW to use without doing a search-and-replace on SMW.  If we're not worried about supporting versions of MW without DB_REPLICA, then doing a search and replace on DB_SLAVE would be better.

Alternatively, we can do the search and replace and provide a shim for older mediawiki that only define DB_SLAVE.

**Comment by legoktm** [comment]
My understanding (when I filed #4093) was that SMW is only supporting 1.27+. DB_REPLICA is available since 1.27.4/1.28.0, so I don't think there should be any need to keep using DB_SLAVE.

**Comment by JeroenDeDauw** [comment]
SMW master only supports MW 1.31+, see https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md

**Pull request closed without merging**
