### PR TITLE
Backport PR #1758 to 2.4.x branch.

### PR DESCRIPTION
**Pull request by crlf0710**
Since #1757 is a show stopper for certain configuration, and 2.5's release schedule is not decided yet,  i want to try back-porting #1758  back to 2.4.x branch.

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by crlf0710** [comment]
@mwjames Hi, what do you think? Any chance to include this in a future release of 2.4.x branch?

Notice that some inline documentation still says "since 2.5" though.

**Comment by mwjames** [comment]
> Since #1757 is a show stopper for certain configuration, and 

Well, I only know of Wikia to use the "Global Transaction Identifier" actively.

> 2.5's release schedule is not decided yet

We expect that to happen in March [0].

> @mwjames Hi, what do you think? Any chance to include this in a future release of 2.4.x branch?

If it is really urgent then of course we can merge this to the 2.4.x and since this isn't your normal "bug/regression" backport, I'd would count on @kghbln to release this as separate 2.4.6 to isolate it in case something unanticipated happens (I'm not running any 2.4.x, so I cannot check against an actual instance). The tests pass so there shouldn't be any issue but as always the devil is in the details.

> Notice that some inline documentation still says "since 2.5" though.

Nothing to worry about.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/milestones

**Comment by crlf0710** [comment]
Hi, thanks for the reply!

My hosting service's database provider has their "Global Transaction Identifier" turned on, which caused this problem. It occurs only with certain category queries, leading us have to workaround those queries.

Good to know that 2.5 will come in March, however i bet it will take some time after it is released before my mediawiki hosting service is able to finish evaluating the new version, upgrading their stuff, adapt to the feature changes, do testing etc.

Actually it is not in a very urgent status (current queries have been workaround-ed), but I will be very grateful if there be a separate 2.4.6 version that ship this fix before the 2.5 release, then i can go to persuade them do the upgradation soon.

Thanks a lot!

**Comment by kghbln** [comment]
Since there are no objections for @JeroenDeDauw and @mwjames I could indeed merge and release as 2.4.6 during next week.

**Comment by mwjames** [comment]
> Since there are no objections for @JeroenDeDauw and @mwjames I could indeed merge and release as 2.4.6 during next week.

No objections from my side, so I leave this to you guys!

**Pull request merged**
