### PR TITLE
Move class_alias to its own file

### PR DESCRIPTION
**Pull request by mwjames**
Refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1367

### CODE REVIEW

**Comment by mwjames** [comment]
This also __prepares__ the init in case someone wants to play with the `extension.json` stuff (would require 1.27+ and a functional requires section for extensions [0] though):

```
{
	"name": "Semantic MediaWiki",
	"version": "...",
	"author": [	],
	"url": "https://github.com/SemanticMediaWiki/SemanticMediaWiki/",
	"descriptionmsg": "...",
	"license-name": "GPL-2.0+",
	"type": "semantic",
	"requires": {
		"MediaWiki": ">= 1.27"
	},
	"MessagesDirs": {
		"SemanticMediaWiki": [
			"i18n"
		]
	},
	"AutoloadClasses": {
		"SemanticMediaWiki": "SemanticMediaWiki.php"
	},
	"callback": "SemanticMediaWiki::initExtension",
	"ExtensionFunctions": [
		"SemanticMediaWiki::onExtensionFunction"
	],
	"load_composer_autoloader":true,
	"manifest_version": 1
}
```

[0] "The key of the requires object is the name of the dependency (currently only MediaWiki supported), the value is a valid version constraint (the format has to match the one used by composer)." https://www.mediawiki.org/wiki/Manual:Extension_registration#Requirements_.28Dependencies.29

**Comment by JeroenDeDauw** [comment]
+1, though I'd go with simply Aliases.php, and perhaps not put it in the root

**Comment by mwjames** [comment]
> simply Aliases.php, and perhaps not put it in the root

There is one called Aliases.php in the includes DIR for PHPStorm. Would that interfere?

**Comment by JeroenDeDauw** [comment]
You could rename that one, it's name does not really matter. It's not included by anything after all.

**Pull request merged**
