### PR TITLE
Restore PHP 7.3 compat and bump to 4.0rc1

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@SemanticMediaWiki/testers once this is merged it'd be super helpful if you could try out SMW master. Especially on a server with PHP 7.3 and/or MediaWiki 1.37.

**Comment by kghbln** [comment]
I did not even get to 1.37: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5165 I really appreciate support for PHP 7.3 with this release. Thanks a ton!!!

**Comment by kghbln** [comment]
So far the release candidate is working for me on 1.35.x with PHP 7.3. Will be nice to get other confirmations. Probably tomorrow I will try 1.37.x with PHP 7.3

**Comment by kghbln** [comment]
I just did a field test with MW 1.37 on PHP 7.3, a rather small wiki. It is working for me including a rebuild data. (The issues came from SESP and not SMW itself.) Will be nice to get other confirmations.

**Pull request merged**
