### PR TITLE
Add MW 1.40 to CI

### PR DESCRIPTION
**Pull request by malberts**
First attempt at running CI, not tested locally.

### CODE REVIEW

**Comment by malberts** [comment]
Looks like we're blocked until https://github.com/wikimedia/mediawiki-docker/pull/124 gets merged.

**Comment by malberts** [comment]
This is now failing due to PHPUnit 9.x incompatibility: 
https://github.com/SemanticMediaWiki/SemanticMediaWiki/actions/runs/5540476976/jobs/10136912202#step:11:37

See https://github.com/sebastianbergmann/phpunit/issues/4024

**Comment by gesinn-it-gea** [comment]
we created Docker images for combinations of MW and PHP versions as this is not available from the official MW Docker. Setup is the same: https://github.com/gesinn-it/docker-mediawiki-base/

Maybe this helps you with streamlining the CI. See an example of this in action here: https://github.com/SemanticMediaWiki/SemanticDrilldown/pull/61

**Comment by jaideraf** [comment]
MW 1.40 has already been added to CI. So this pull can be closed.

**Pull request closed without merging**
