### PR TITLE
rebuildData to output more verbose info, add `--ignore-exceptions`, r…

### PR DESCRIPTION
**Pull request by mwjames**
…efs #1327

Output more verbose information about what entity is being rebuild.

- Add `--ignore-exceptions` and `--redirects` option
- Option `--categories` is `-c`

image

ID's marked with * are in reference to the MW `page` table where the same ID does not necessarily represent the same entity (see 30).

image

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln OK, I didn't plan on this but `--ignore-exceptions` was just added (in case of an exception, the file `exception-....log` [0] will contain that information).

Happy testing!

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1433/files#diff-05d44ea7d2b4980df07a3b7396a34eeeR142

**Comment by jamesmontalvo3** [comment]
This change is phenomenal and I can't thank you enough for it. Looking forward to testing it out. If I'm reading it right it puts the log file in the `extensions` directory. Any reason that directory was chosen? Mind if I take a stab at changing the `--ignore-exceptions` option to allow specifying a log file? Would it be better to have yet another option like `--exception-log=/some/path` or maybe make just the one option?

**Comment by kghbln** [comment]
This is utterly great. Thanks a ton! It does not relieve admins from tracking down the issues and reporting them but it helps actually getting the task of rebuilding data done as well.

Having the log file in the extensions directory is not ideal especially in farmed environments, so being able to specify a path will be preferable. I do not think an extra option is necessary, so I can imagine

``--ignore-exeptions`` would write to the standard path specified by the script and

``--ignore-exeptions=/some/path`` would allow to specify an alternate path for the log

Not logging exceptions does not make much sense I believe so this option appears not necessary to me.

**Comment by mwjames** [comment]
> Having the log file in the extensions directory is not ideal especially in farmed environments, so being able to specify a path will be preferable. 

I'd go for the `--exception-log=/some/path` option, as the connotation of `--ignore-exeptions` is a either or decision (== boolean) which in case of a `true` could imply an additional information but I'd rather split them.

**Comment by kghbln** [comment]
> I'd go for the --exception-log=/some/path option ...  but I'd rather split them.

You have a point here. That's fine with me too.

**Comment by mwjames** [comment]
> I'd go for the --exception-log=/some/path option

... and so it is done `php maintenance/rebuildData.php -v --ignore-exceptions --exception-log="/D/xampp/tmp/logs/"
`

**Comment by kimcollin** [comment]
Glad u liked it

On Friday, 4 March 2016, James Montalvo <notifications@github.com> wrote:

> This change is phenomenal and I can't thank you enough for it. Looking
> forward to testing it out. If I'm reading it right it puts the log file in
> the extensions directory. Any reason that directory was chosen? Mind if I
> take a stab at changing the --ignore-exceptions option to allow
> specifying a log file? Would it be better to have yet another option like
> --exception-log=/some/path or maybe make just the one option?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1433#issuecomment-192537146>
> .
>


-- 
Kimberly collins

**Pull request merged**
