### PR TITLE
Fix SMW_PHPUNIT_DIR

### PR DESCRIPTION
**Pull request by paladox**
For some reason under MW 1.41+ is failing with finding this define, even tho it is in bootstrap. Adding it to Setup seems to have fixed it.

## Summary by CodeRabbit

- **New Features**
	- Introduced a new constant for PHPUnit directory to streamline testing setup.
  
- **Bug Fixes**
	- Adjusted references to the PHPUnit directory constant to ensure proper namespace resolution across multiple test files.

- **Chores**
	- Removed redundant conditional definition for the PHPUnit directory constant in setup tests.

### CODE REVIEW

**Comment by paladox** [comment]
@coderabbitai review

**Comment by jaideraf** [comment]
@JeroenDeDauw @gesinn-it-gea this decreases the number of errors in CI.

**Comment by gesinn-it-gea** [comment]
@JeroenDeDauw I'm not sure 100% about this PR. Can you have a look please.

**Comment by JeroenDeDauw** [comment]
@gesinn-it-gea what are you unsure about? I don't see anything dubious

**Review by JeroenDeDauw — APPROVED** [review]

**Comment by gesinn-it-gea** [comment]
@JeroenDeDauw I was just not sure if this change could affect "other ways of testing" (like manually). I'm used to the Docker approach, so I'm not always 100% sure about the others.

**Pull request merged**
