### PR TITLE
Revert "Replace HTTP with HTTPS"

### PR DESCRIPTION
**Pull request by kghbln**
Reverts SemanticMediaWiki/SemanticMediaWiki#3225 per https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3226#issuecomment-405829923

### CODE REVIEW

**Comment by kghbln** [comment]
wth

**Comment by JeroenDeDauw** [comment]
image

**Comment by kghbln** [comment]
Me neither. It seems that you have to immediately revert. Does not matter. It all happened.

**Comment by Kumioko** [comment]
@kghbln , @mwjames. Sorry about the confusion and trouble gents. I'm just learning the ropes here. Just for clarification, why aren't these types of changes allowed? I feel like the argument of the code being stable and shouldn't be changed could be extended to almost anything, so I'm not really clear on why it's not allowed here.

**Comment by mwjames** [comment]
> @kghbln , @mwjames. Sorry about the confusion and trouble gents. I'm just
> learning the ropes here. Just for clarification, why aren't these types of

This is fine and appreciated.

> shouldn't be changed could be extended to almost anything, so I'm not really
> clear on why it's not allowed here.

I tried to clarify that with my comment [0] and [1]. It is not so much
about not being allowed as to follow a common (meaning accepted)
convention [1] for RDF resource links.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3226#issuecomment-405829923
[1] https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/

Cheers

**Comment by Kumioko** [comment]
@mwjames Thank you for the clarification

**Pull request closed without merging**
