### PR TITLE
MaintenanceLogger to check for wgMaxNameChars, refs 1983

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1983

This PR addresses or contains:

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln Instead of a nameless "PHP Catchable fatal error...", now it will throw an `Exception` informing about the required min length in `wgMaxNameChars`.

**Comment by mwjames** [comment]
Scrutinizer — Errored

**Comment by kghbln** [comment]
Hey, great another step to more user friendliness. :)

**Comment by kghbln** [comment]
Ah, this check every logger individually.

**Comment by mwjames** [comment]
> Ah, this check every logger individually.

Yes.

We isolated the  `MaintenanceLogger` from its invocation using the `MaintenanceFactory` therefore allows us to apply the check independently from the respective caller..

**Pull request merged**
