### PR TITLE
Consolidate category settings `smwgCategoryFeatures`, refs 2798

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2798 

This PR addresses or contains:

- Adds `smwgCategoryFeatures` and replaces:
  - `smwgUseCategoryHierarchy` with `SMW_CAT_HIERARCHY`
  - `smwgCategoriesAsInstances` with `SMW_CAT_INSTANCE`
  - `smwgUseCategoryRedirect` with `SMW_CAT_REDI`
- Default is defined with `SMW_CAT_REDI | SMW_CAT_INSTANCE | SMW_CAT_HIERARCHY`

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames Wouldn't it be a bit more consistent to call `SMW_CAT_REDI` `SMW_CAT_REDIRECT`?

**Comment by kghbln** [comment]
[Documented in wiki.](https://www.semantic-mediawiki.org/wiki/Help:$smwgCategoryFeatures)

**Comment by mwjames** [comment]
> @mwjames Wouldn't it be a bit more consistent to call SMW_CAT_REDI SMW_CAT_REDIRECT?

Fine by me, you want to do a PR?

**Comment by kghbln** [comment]
> Fine by me, you want to do a PR?

Yes and done. :) I guess I covered all spots.

**Pull request merged**
