### PR TITLE
Do not write objects into ExtensionData

### PR DESCRIPTION
**Pull request by cicalese**
See #4868.

This is still a work in progress. It needs tests.

### CODE REVIEW

**Comment by cicalese** [comment]
All tests have failed for a reason that appears to be unrelated to these changes. Suggestions?

**Comment by gesinn-it** [comment]
@JeroenDeDauw @cicalese my recent changes for Travis should have fixed the issues. What's the recommendend procedure? Throw away this PR and create a new PR against recent master?

**Comment by cicalese** [comment]
Thank you, @gesinn-it! I'm not sure the best way to rebase, but I will look into it.

**Comment by hexmode** [comment]
This is old and it looks like #5285 is a more current fix.

**Pull request closed without merging**
