### PR TITLE
Petty http to https replacements and fix a typo

### PR DESCRIPTION
**Pull request by Kumioko**
This PR is made in reference to: #

This PR addresses or contains:
- ...
- ...
- ...

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
@Kumioko Thanks a lot for your effort! The tests [are failing](https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/405117577#L1689). Thus they must be adapted in "XmlResponseParserTest.php", too. See e.g. [here](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Unit/SPARQLStore/QueryEngine/XmlResponseParserTest.php#L108).

**Comment by mwjames** [comment]
Hi,

> @Kumioko Thanks a lot for your effort! The tests [are
> failing](https://travis-

Tests here fail for a reason namely to verify the stability of the URI form.

By convention, RDF resource links like (e.g.
"http://www.w3.org/2001/XMLSchema ...") are not to be modified and
should remain with `http` as they are about identifying a resource
(where http === https, see [0]) and not about a specific security
aspect.

[0] https://www.w3.org/blog/2016/05/https-and-the-semantic-weblinked-data/

Cheers

**Comment by kghbln** [comment]
> Tests here fail for a reason namely to verify the stability of the URI form.

So these changes will theoretically only be ok for new instances while it is a no go for existing instances. So basically https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3225 needs to be reverted, too.

**Comment by mwjames** [comment]
> So these changes will theoretically only be ok for new instances while it is
> a no go for existing instances. So basically
> https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3225 needs to be
> reverted, too.

To clarify, changes to the documentation are fine but everything that
touches those RDF resource links (either in real or in tests,
specially XML files and output) are off-limits as it is expected to
those URIs are stable now and in future.

Cheers

**Comment by kghbln** [comment]
@mwjames Thanks for the info

@Kumioko I am sorry for my confusion but this cannot be merged to to the info provided to this pull.

**Pull request closed without merging**
