### PR TITLE
Increase type safety in DIProperty

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Prompted by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4541

### CODE REVIEW

**Comment by mwjames** [comment]
Throwing around types isn't going to solve anything here as evident by the broken tests, the implicit behaviour of type casting is part of the historic technical debt in SMW which has to be addressed differently.

The type system isn't the holy grail and should only be used for new classes where the behaviour is tested, adding it in retrospect to "old" classes will most likely fail as shown in the case above. Even if you correct all cases in SMW core, it doesn't mean that is going to be solved in extensions hereby exposing them to unnecessary breakage just to "satisfy" the need for a type.

**Comment by akuckartz** [comment]
> the implicit behaviour of type casting is part of the historic technical debt in SMW which has to be addressed differently.

How?

**Comment by mwjames** [comment]
> How?

There a couple of ways, one is to install PHP 7.4 encounter one issue at a time, identify what is expected, look at what is implicit, and resolve the implicit implication or assumption and make it explicit by either type casting the value directly or find another solution. Anyway, doing this will require diligence, time, and effort just adding a couple of types to the method signature will cause all sorts of trouble.

**Comment by JeroenDeDauw** [comment]
James I knew this would break the tests. It makes the issue more visible. So no this is not proof types are bad.

And yes, obviously types are not a holy grail. Just like tests are not.

> should only be used for new classes

I strongly disagree with this. It goes against both my theoretical understanding and my lived experience over the last 5+ years.

**Comment by JeroenDeDauw** [comment]
On the topic of type casing: if you really want to have this type casting happen you should fix the type docs, because then they are currently _wrong and misleading_. This is one of the great advantages of having the types in the code: you notice when they are wrong.

**Pull request merged**
