### PR TITLE
Add contributors list to release notes

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
In order of commit count...

**Comment by mwjames** [comment]
legoktm -> https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1079

**Comment by JeroenDeDauw** [comment]
Well yeah, that does not show up when running git shortlog :) Perhaps we should also credit people that significantly contributed by testing and stuff like that? I don't know how to easily compile such a list though.

**Comment by mwjames** [comment]
yoonghm -> on the postgres issue #1175, #1165

**Comment by mwjames** [comment]
cicalese -> pre testing #1131
bogota #1120

**Comment by mwjames** [comment]
plegault3397 -> #1007 (would have been a pain if hadn't been identified early on)

**Comment by JeroenDeDauw** [comment]
I've updated the list to include those. Though please do add them yourself, this is git after all ;)

Did @gesinn-it do something, or was that just SRF?

**Pull request merged**
