### PR TITLE
Fix coding style issues #899

### PR DESCRIPTION
**Pull request by jongfeli**
This PR is made in reference to: #899

This PR addresses or contains:
- Fix coding style issues

Update: https://github.com/jongfeli/Code-violations-SemanticMediaWiki/blob/master/all

### CODE REVIEW

**Comment by mwjames** [comment]
@JeroenDeDauw The comments violation looks odd! My IDE always uses:

```
/**
 *
 * 
 */
```

**Comment by JeroenDeDauw** [comment]
Thanks @jongfeli! As @mwjames pointed out, the comment block style change is not desired. Weird that the tool did this

**Comment by jongfeli** [comment]
@JeroenDeDauw, @mwjames I understand but what I do not understand is why my **Bluefish** suddenly decides to change comments where it did not in the past.... I tried to fix this online but that just takes to long and things get messy.

I will do this style check over again, synced and pulled from master but not today, the weather is to good... :)

I see that I can close this pull request but I am not sure if that is the right way to "get rid" of it.

**Comment by JeroenDeDauw** [comment]
Sure, it's fine to create a new PR instead of somehow fixing this one. Closed this one, since you still have the branch on your remote, so can cherry-pick anything from it if you like.

**Pull request closed without merging**
