### PR TITLE
query with "imported from" property

### PR DESCRIPTION
**Pull request by thomas-topway-it**
fixes issue https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4971

- fixes mixed wikitext/html in Imported from printout caption
- fixes empty declarativeName (i.e. vocabulary name used as caption of the imported property between parenthesis) (see here https://www.semantic-mediawiki.org/wiki/User:Krabina_Bernhard/ontology)

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
@thomas-topway-it if you are still working on PRs, please set them to "draft". Otherwise we get spammed by commit notifications. This way it is also clear for the reviewers, that they should not start with the review yet.

**Comment by thomas-topway-it** [comment]
@gesinn-it-gea ah, right, I hoped nobody else was subscribed to the pull request. In fact I had to do a lot of tests on the remote branch itself since there was a discrepancy with my local tests. They fail because `RevisionGuard` in the file `JSONScriptServicesTestCaseRunner.php` is null and on the other side it cannot be a mockup  like the following
```
		$revisionGuard = $this->getMockBuilder( '\SMW\MediaWiki\RevisionGuard' )
			->disableOriginalConstructor()
			->getMock();
```

 otherwise other tests not related to the current edits will fail. I have now verified that setting a revisionGuard with the following 
`
$mediaWikiNsContentReader->setRevisionGuard( SMW\Services\ServicesFactory::getInstance()->singleton( 'RevisionGuard' ) );
`
seems to set a null revisionGuard. So following I have to check this point.

**Comment by thomas-topway-it** [comment]
@gesinn-it-gea it is now ready for review. I have added a test, based on a simple query like the following

```
{{#ask: [[Imported from::+]]
|?Imported from
|format=plainlist 
}}   
```

the test fails with the original class and succeeds with the updated class. (the original class returns a result like the following, https://www.semantic-mediawiki.org/wiki/User:Krabina_Bernhard/ontology, with escaped html and without captions)

**Comment by thomas-topway-it** [comment]
@JeroenDeDauw can this be finally merged ?

**Comment by YOUR1** [comment]
Seems good to me.

**Comment by krabina** [comment]
Reviewd by @YOUR1 (thank you!). Can we merge, @gesinn-it-gea @JeroenDeDauw ?

**Comment by krabina** [comment]
Closiing this because of the rebased https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5606

**Pull request closed without merging**
