### PR TITLE
Add ExtraneousLanguage JSON format, refs #1691, #1561

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1691, #1561

This PR addresses or contains:

- Moves SMW specific language elements from PHP to JSON
- Support for partial fallback
- If a json file (e.g. `zh-hant.json`) contains `isLanguageRedirect` then only a `fallbackLanguage` is required
- The `CanonicalFallbackLanguage` is `en`
- Adds `LanguageFallbackFinder`, `LanguageFileContentsReader`

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
I have been re-basing this PR for months and I hope that we can have it merged rather soon. It mostly brings fallback and partial fallback support.

This PR needs extra care therefore I'd like @kghbln (I know its a pain) to test this more thoroughly to ensure that we do not introduce any regression.

- Namespace settings remain with the content language (switching content language does work as before)
- Property labels and names display does match the user language or content language
- DataTypes are recognized in the content language

PS: A script has transformed content that resided in PHP files and copied them into a JSON file to match the specification but I kept the "old" PHP files for now to make it possible to compare entries with that of the JSON format. Once merged changes should only happen to the new files.

**Comment by kghbln** [comment]
The issue is that it is impossible to install development branches of SMW with master of other software on sandbox via composer. I am getting the usual "Your requirements could not be resolved to an installable set of packages". I currently need sandbox including the other semantic software to prepare my second presentation and probably the two tutorials for SMWCon. I currently have not other testsite at hand.

**Comment by kghbln** [comment]
Sorry for being extremely grumpy this morning. Early this week I had a server upgrade and you wouldn't believe how unstable PHP opcaching can be - pretty disappointing. Well I still suffering from time comsuming aftermaths.

**Comment by mwjames** [comment]
> Sorry for being extremely grumpy this morning.

Don't worry about it. I wanted to draw attention to a PR that has the potential for a regression and I'd like at least a second pair of eyes (some integration tests complained in an earlier iteration) to look at this from a "I worked with it and it doesn't seem to be broken".

Anyway, if I find time (in my weekly support window) then I will just merge it later today and we can observe the results on the sandbox.

**Comment by kghbln** [comment]
> Anyway, if I find time (in my weekly support window) then I will just merge it later today and we can observe the results on the sandbox.

I am sorry that I had to let you down on this. :(

**Comment by mwjames** [comment]
@kghbln This requires a follow-up on removing all the PHP lang. related scripts from the `languages` directory. Also, currently those json files are placed under `languages/i18n` (defined in [0]).

Somehow I want to remove the `languages` directory from the root, so suggestions on how to move forward would be much appreciated.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L26

**Comment by kghbln** [comment]
@mwjames I have not tested thoroughly yet but sandbox did not change to bellies up mode so far and a fast look though did not show anomalies. Will have a second peep at it soon.

I am not sure if MediaWiki requires the language information for namespaces, magic words etc. to be in the languages directory. If it does not which I think is the case it may only be a matter of changing 
`$GLOBALS['smwgExtraneousLanguageFileDir'] = __DIR__ . '/languages/i18n';` to `$GLOBALS['smwgExtraneousLanguageFileDir'] = __DIR__ . '/i18n/i18n';` or perhaps `$GLOBALS['smwgExtraneousLanguageFileDir'] = __DIR__ . '/i18n/extra';` etc.

**Comment by mwjames** [comment]
> I am not sure if MediaWiki core requires the language information for namespaces, magic words etc. to be in the languages directory.

I think it is matter of customization:

- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/load.php#L54-L55
- https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/Setup.php#L176-L182

> If it does not which I think is the case it may only be a matter of changing

I would appreciate if you could take the lead on this.

**Comment by kghbln** [comment]
> I think it is matter of customization:

Which is good.

> I would appreciate if you could take the lead on this.

It looks like not a lot of brain is needed to do this so this Saturday ...

**Comment by kghbln** [comment]
@mwjames It will be nice if you could note something about [services](https://www.semantic-mediawiki.org/w/index.php?title=Services&action=edit&redlink=1)

**Comment by mwjames** [comment]
> It will be nice if you could note something about services

You mean [0] or something else?

[0] https://www.semantic-mediawiki.org/wiki/Extraneous_language

**Comment by kghbln** [comment]
> You mean [0] or something else?

I meant in connection with [`$smwgServicesFileDir`](https://www.semantic-mediawiki.org/wiki/Help:$smwgServicesFileDir) so this page would be an overview pointing to services like extraerroneous language and other services if currently? present.

**Comment by mwjames** [comment]
> I meant in connection with $smwgServicesFileDir so this "services" 

I did a super quick write up in https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/c158446b70caed8168d9cee9551e7eb96311e8f9, hope this helps.

**Comment by kghbln** [comment]
> I did a super quick write up in c158446, hope this helps.

Cool - all on wiki now!

**Pull request merged**
