### PR TITLE
Fix usage of `|+align=...` in `format=table`

### PR DESCRIPTION
**Pull request by mwjames**
```
{{#ask: [[Currency::+]]
 |?Currency|+align=right|+limit=2
 |format=table
}}
```

https://phabricator.wikimedia.org/T18571

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln It seems no one really missed this feature `|+align=right` otherwise someone would have complained. At least now it is tested.

**Comment by mwjames** [comment]
http://sandbox.semantic-mediawiki.org/wiki/Issue/1357

**Comment by mwjames** [comment]
[0] this one needs more love.

[0] https://www.semantic-mediawiki.org/wiki/Help:List_of_printout_parameters

**Comment by kghbln** [comment]
> `|+align=right` per ?-row

Indeed, so far we only seem to have had a global `|align=right` as in

```
...
|?...
|format=table
|align=right
...
```
So this is not just a bug fix but also an enhancement?!

**Comment by mwjames** [comment]
> So this is not just a bug fix but also an enhancement?!

According to [0] NO, it states "This has now been implemented: additional parameters to individual ?printouts can be given by writing "|+ parameter=value" after the printout. Currently, there are parameters for limiting and ordering results ("limit=number" and "order=ascending/descending"), and special parameters for some printouts (e.g. format=table supports "align=right" and "align=center").

The bug remains open since these parameters do not work properly with Special:Ask yet: they are simply lost when clicking on "further results"."

Of course, the "...do not work properly with Special:Ask yet: they are simply lost when clicking on "further results"" remains valid but that's for a follow-up.

[0] https://phabricator.wikimedia.org/T18571

**Comment by kghbln** [comment]
> According to [0] NO

Ah, true so the docu of this on smw.o was messed up from the start since it states it should be used globally for a query. I guess this has not been used wide spread since it is pretty useless. However, now there is more light on this. Cool this makes sense.

Since this is only format specific for table and broadtable it should probably appear in `#smwdoc` for these two?

**Comment by mwjames** [comment]
> Since this is only format specific for table and broadtable it should probably appear in #smwdoc for these two?

#smwdoc deals with enabled parameters while `|+align=` (or in case of the record type `|+index=`) are printout specific parameters and not bound to an "official" parameter declaration.

**Comment by kghbln** [comment]
> #smwdoc deals with enabled parameters

Yeah, still a bit edgy. However, it makes sense not to do exceptions.

**Comment by mwjames** [comment]
> Of course, the "...do not work properly with Special:Ask yet: they are simply lost when clicking on "further results"" remains valid but that's for a follow-up.

Just as a side note, trying to use something like `?Has number|+align=right|+limit=2|+order=asc` in the `Special:Ask` printout text area will fail because of the `|` usage.

**Pull request merged**
