### PR TITLE
Test against MW 1.43

### PR DESCRIPTION
**Pull request by paladox**
## Summary by CodeRabbit

- **New Features**
	- Expanded testing matrix to include support for MediaWiki version 1.43 with PHP 8.2 and MariaDB 11.2.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Seems like this MediaWiki version of combo of MW+PHP is not supported by @gesinn-it-gea

**Comment by gesinn-it-gea** [comment]
https://github.com/wikimedia/mediawiki-docker/blob/main/update.py#L39

or:

https://github.com/gesinn-it/docker-mediawiki-base/blob/main/helpers.sh#L7

**Comment by paladox** [comment]
> As soon as the docker image for 1.43 is available, this will work (docker images can be built earliest when tags for a release are available).

There's one for 1.43 rc1 https://github.com/wikimedia/mediawiki/releases/tag/1.43.0-rc.0

**Comment by gesinn-it-gea** [comment]
I know that there's an rc tarball. But using this failed due to a missing key on https://www.mediawiki.org/keys/keys.txt

See: https://github.com/gesinn-it/docker-mediawiki-base/actions/runs/12283634881/job/34277536695#step:10:2460

A mail to wikitech-l did not get any answer.

**Comment by gesinn-it-gea** [comment]
I can temp. disable sig check

**Comment by paladox** [comment]
isable sig check

Looks like it was added with https://github.com/wikimedia/operations-mediawiki-config/commit/584d13a6acfd385f9fba6bd00846c919631f544e

**Comment by paladox** [comment]
Looks like it may be fixed? See https://lists.wikimedia.org/hyperkitty/list/wikitech-l@lists.wikimedia.org/thread/NE4NOIUZRPG7BQTPXGFI6EZE4K2W3BVB/

**Comment by gesinn-it-gea** [comment]
https://hub.docker.com/layers/gesinn/mediawiki-base/1.43-php8.1/images/sha256-0ae63e1f8bb26f6acd4bcd79eda65d0a6ba3828f4cc966c3fae5a009c5b04957

**Comment by gesinn-it-gea** [comment]
The image still has to be integrated into the subsequent layers...

**Comment by paladox** [comment]
@gesinn-it-gea I've done https://github.com/gesinn-it/docker-mediawiki/pull/8

**Comment by paladox** [comment]
Looks like PHPUnit_Framework_TestCase needs replacing with PHPUnit\Framework\TestCase.

I dunno about > Warning: Cannot declare interface MediaWiki\Json\JsonUnserializable, because the name is already in use in /var/www/html/includes/json/JsonDeserializable.php on line 51
tho

**Comment by paladox** [comment]
MW 1.39+ uses phpunit 8.5 or above: https://github.com/wikimedia/mediawiki/blob/REL1_39/composer.json#L99

So we can simply just replace PHPUnit_Framework_TestCase with PHPUnit\Framework\TestCase without breaking MW 1.39 support.

https://github.com/sebastianbergmann/phpunit/blob/8.5/src/Framework/TestCase.php

**Pull request merged**
