### PR TITLE
Fix using "SMW_PHPUNIT_DIR" const

### PR DESCRIPTION
**Pull request by paladox**
We don't want to use the current files namespace to import SMW_PHPUNIT_DIR. Instead use \SMW_PHPUNIT_DIR.

## Summary by CodeRabbit

- **Bug Fixes**
	- Updated constant references in test cases to ensure correct namespace resolution, preventing potential issues.
  
- **Tests**
	- Adjusted multiple test methods to utilize fully qualified names for constants, enhancing reliability of test execution.

### CODE REVIEW

**Comment by alexander-gesinn** [comment]
image

awesome :-)

**Comment by paladox** [comment]
@coderabbitai full review

**Comment by paladox** [comment]
Hmm, seems \SMW_PHPUNIT_DIR fails as well.

**Comment by paladox** [comment]
Unless I use the one from https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/148227c477024b4fe7ffb8ca7d42133f872c91c9/tests/phpunit/SetupCheckTest.php#L29 ?

**Comment by paladox** [comment]
I'm not sure how to fix so gonna close this.

**Pull request closed without merging**
