### PR TITLE
Improve MW 1.35 compatibility

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Oh cmon shit software >_>

**Comment by JeroenDeDauw** [comment]
Fails: https://travis-ci.org/github/SemanticMediaWiki/SemanticMediaWiki/jobs/700263355

Looks like brittle tests failing due to overuse of mocks

**Comment by JeroenDeDauw** [comment]
Spend some more time looking at this since it is spamming my logs. Likely make sense to make some more significant changes rather than hotfixing this. Plus the tests are getting in the way of hotfixing. I'd be inclined to just delete them but will settle on suppressing the deprecation notice for now.

**Comment by Seb35** [comment]
See #4949 where I did a lot of replacements to fix most warnings, although it currently remains details to be checked.

**Pull request closed without merging**
