### PR TITLE
Fix missing use declaration; minor clean-up

### PR DESCRIPTION
**Pull request by s7eph4n**
This PR is made in reference to: #

This PR addresses or contains:
- SMW\Query\QueryContext was used but not pulled in in ResultPrinter.
- minor clean-up and optimization.

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
so ... setQueryContext calls where broken before?

**Comment by JeroenDeDauw** [comment]
If the method was definitely broken (causing fatal error on execution) during the last 2 years then we can remove it

**Comment by mwjames** [comment]
If it isn't used then we may kick it (could have been used in past
where its usage got removed and is no longer necessary after some
refactoring).

**Comment by kghbln** [comment]
Back-ported with b75e468910ca9be0a2dcd50f3fe3df6ed1fd847b

**Pull request merged**
