### PR TITLE
Add query scode to profile, refs 2270, 2572

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2270, #2572

This PR addresses or contains:

- Adds the `Query scode` property to be able to track an internal state (using a number as status code) on when a `#ask` uses `@annotation` or `@deferred` as special execution mode

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames This one is enabled by default?

**Comment by kghbln** [comment]
I believe it is not: [Documented on wiki.](https://www.semantic-mediawiki.org/wiki/Help:Special_property_Query_scode)

**Comment by kghbln** [comment]
> @mwjames This one is enabled by default?

When looking at the logic of this [page](https://www.semantic-mediawiki.org/wiki/Help:$smwgQueryProfiler) I am not so sure any longer.

**Comment by kghbln** [comment]
> When looking at the logic of this page I am not so sure any longer.

Just had a peep at sandbox. Indeed it is enabled by default.

**Comment by mwjames** [comment]
> Just had a peep at sandbox. Indeed it is enabled by default.

First I wanted to introduce a general `Status code` property but then I thought this
may collide with many other user defined properties of the same name so I settled for `Query scode` but now after a week, I'm not so happy with the name, I might need to rename it (will keep the number coding system).

We also have #2146, which appears when a federated query (remote) is used.

The idea behind it is very simple, if you wanted to find queries with a special execution mode you'd be out of luck hence the status code (or execution mode, OR a better name??).

Using a simple number code should be enough to fill that gap and allows to extend the list in future and hopefully avoids the need to introduce other properties.

100 - `@annotation`
200 - `@deferred`
300 - halted due to expensiveness (#2476) (isn't used yet!!)

**Comment by kghbln** [comment]
@mwjames Thanks a lot for your insight on this.

>  I settled for Query scode but now after a week, I'm not so happy with the name,

Probably "Query mode code" as in execution mode is a better name for it.

**Comment by kghbln** [comment]
I have added the "requires follow-up" label to prevent this from being forgotten.

**Comment by jaideraf** [comment]
> I'm not so happy with the name, I might need to rename it (will keep the number coding system).

Maybe it's too late (sorry), but what about simply "`Query status code`"? 
Or, "`Query mode code`" as suggested by @kghbln?
We already have a name convention problem [here](https://www.semantic-mediawiki.org/wiki/Help:Special_properties): some property names start with "Has..." other don't. We have to be carefull to not introduce a third name convention here.

**Comment by kghbln** [comment]
@mwjames I think is makes sense to rename. "Query status code" makes sense to me. Most of the profiling related special properties do not have a Has ... so this could only be an alias.

**Comment by mwjames** [comment]
> I think is makes sense to rename. "Query status code" makes sense to me. Most of the profiling related special properties do not have a Has ... so this could only be an alias.

I was reviewing the issue and while the "code" part in the name isn't incorrect, I somehow feel the "status code" expresses a false semantic and therefore I'd rather go with `Query state` where "state" connotes a mode of existence which is closer to what the content of the property is to represent.

**Comment by kghbln** [comment]
> I was reviewing the issue and while the "code" part in the name isn't incorrect, I somehow feel the "status code" expresses a false semantic and therefore I'd rather go with Query state where "state" connotes a mode of existence which is closer to what the content of the property is to represent.

Fair enough. This makes sense to me.

**Comment by kghbln** [comment]
@mwjames Do you think you could still give this a shot with "Query state" if it does not consume too much time? This would really be great.

**Pull request merged**
