### PR TITLE
Rename TitleMoveComplete hook to PageMoveComplete

### PR DESCRIPTION
**Pull request by Abijeet**

### CODE REVIEW

**Comment by Abijeet** [comment]
@JeroenDeDauw - Can we now enable Jenkins, run the test case on this and get this merged if everything is OK?

**Comment by JeroenDeDauw** [comment]
Apparently the reset is on the 5th. Quite a bad situation.

**Comment by Abijeet** [comment]
@JeroenDeDauw - Shall we enable CI now?

**Comment by JeroenDeDauw** [comment]
Alright I just send yet another mail to their support since it is not working

**Pull request merged**
