### PR TITLE
Update tests so they work when used with another extension (e.g. SAR)

### PR DESCRIPTION
**Pull request by hexmode**
Since I was working on updating SAR so that tests would run in a typical way within the MW environment, I discovered and fixed a few things here.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
What is the deal with the `StoreTest.php` removal?

**Comment by hexmode** [comment]
Consolidating the `SMW\Test` namespace with the `SMW\Tests` resulted in a conflict of the two StoreTest.php instances.

I took the lazy way out and deleted the older test.

Hopefully, I'll be able to reconcile this problem and maintain all the tests tomorrow.

**Comment by hexmode** [comment]
If you can see this, here are the failures: https://github.com/hexmode/SemanticApprovedRevs/runs/3276499618

**Comment by hexmode** [comment]
Yay! the SAR test succeeded as well as these!

**Pull request merged**
