### PR TITLE
Replace usages of Revision::getRawText

### PR DESCRIPTION
**Pull request by jdforrester**
Bug: T122754
Change-Id: Ic773243325f0d58594d8c9186e4824966d0f4e0f

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Thanks for the pull request @jdforrester! At present we keep compatibility with MediaWiki 1.19 (see https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/COMPATIBILITY.md), which does not have the used `Revision::getContent` method, as indicated by our CI. Can you amend your change so it does not break compatibility with MediaWiki 1.19? If not, we can add this to #1014 and include it once we switch to SMW 3.x.

**Comment by jdforrester** [comment]
cc @FlorianSW who actually wrote this. :-)

**Comment by FlorianSW** [comment]
Sorry, I'm not a github pro, so I wasn't sure, if I can amend this pull request :/ So I created a new one, which should be able to work with both, MediaWiki 1.19 and MediaWiki 1.27 (with the removed getRawText). https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1371

**Comment by mwjames** [comment]
Thanks

Superseded by #1371.

**Pull request closed without merging**
