### PR TITLE
Performance / Cache the hash

### PR DESCRIPTION
**Pull request by mwjames**
hash-perform

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Wait... that is actually 18.1s to 1.1s?! First thought 18.1ms since using `,` to separate digit groups is evil.

**Comment by JeroenDeDauw** [comment]
Code looks good \o/

**Comment by JeroenDeDauw** [comment]
Shall I backport this onto `2.2.x`?

**Comment by mwjames** [comment]
> Shall I backport this onto 2.2.x?

:+1:

**Comment by mwjames** [comment]
> Anyway, how much difference (% of SMW cost) would this make on a normal page?

For normal pages with only a few template inclusions not much but those with large inclusions should see an effect (I used the wikiapiary `Template:Extension in use` together with a page as I was looking for something different, the screen-dump is based on that page but it is probably more dramatic because of my old notebook that runs the MW instance).

**Comment by JeroenDeDauw** [comment]
I'll backport and update rel notes

**Pull request merged**
