### PR TITLE
Changes the default setting for `smwgSparqlRepositoryConnector`

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #2752 

This PR addresses or contains:
- Changes (BREAKING) the default setting to `default` since three years of transition appear sufficient. Since the configuration parameter was renamed anyways ...

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I think that `generic` was renamed `default` along the way. Also added in `blazegraph` and changed to natural ordering.

**Comment by kghbln** [comment]
I am sorry for the noise. Now at least I am happy. So a squash and merge is required in case this is ok.

**Comment by mwjames** [comment]
>I am sorry for the noise. Now at least I am happy. So a squash and merge is required in case this is ok.

Don't worry. I'll wait on the test results.

**Comment by kghbln** [comment]
> Don't worry. I'll wait on the test results.

They should better be good otherwise I will be a grumpy old goat. Arrrgh, talk about goatifiacation. :|

**Comment by kghbln** [comment]
Thanks a lot. Now [documented.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgSparqlRepositoryConnector&type=revision&diff=55935&oldid=55928)

**Pull request merged**
