### PR TITLE
Bump version to 4.x

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
* Update SMW to MW 1.32+
* Clean CI jobs
* Increment major version

We can drop support for further MW versions before releasing. Would wait a bit with the release, even though there is some pressure to have an SMW release that does not cause a trillion warnings on MW 1.35

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@kghbln so this would bump SMW to 4.0. Maybe we also drop MW 32 and 33?

I rather keep compat back to 1.31 but that seems to be quite a bit of work in case of SMW which I do not see anyone doing at the moment.

**Comment by jaideraf** [comment]
If we will lose the bracket syntax (`[[Foo::Bar]]`) [as noted by James](https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4727), it will be also an "opportunity" to make a SMW 4.

**Comment by JeroenDeDauw** [comment]
That would definitely require a major release yes. I'd only drop the brackets if and when we are absolutely forced to, since this is not a good change for our users.

**Comment by kghbln** [comment]
Does this kill the in-text annotation syntax?

**Comment by JeroenDeDauw** [comment]
This does not remove annotation syntax.

There are tests against master which was basically 1.35 when I made this change. We can add stuff later. This change gets rid of the colossal mess with half the tests being optional and failing and the whole thing taking hours to run. I might throw the entire travis setup out in favor of GitHub actions and maybe get something that runs in a reasonable time.

**Pull request merged**
