### PR TITLE
Improve schema description

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #3749 

This PR addresses or contains:
- Improve schema description

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I am afraid I have no bloody idea how to make the indentation show up on wiki correctly. I now spent more time on formatting this markdown bulsh than improving the docu which is more than ridiculous. Perhaps you can share the magic of this with me.

**Comment by JeroenDeDauw** [comment]
Why are some of the docs in the repo here in the first place? Release notes sure, but general docs... This makes things more complicated. Also quite confusing for people on the wiki if they hit the edit button.

**Comment by kghbln** [comment]
The truth is: We had to make a decision here. Either have the docu here and embed it or not have it at all. So we went for embedding the docu. Since I do 95 % of the edits on the wiki the risk of harm to the editors is low.

Anyhow I take away from your answer that you also have no clue how to do the indenting. I was thinking of adding em-spaces but I am not sure if they will be rendered or served directly.

**Comment by JeroenDeDauw** [comment]
Is moving it to the wiki not easier for you than dealing with this formatting stuff?

And why would we not have the docs at all? Writing them in the wiki does not seem to be more of an effort than doing so on GitHub.

**Comment by kghbln** [comment]
> Is moving it to the wiki not easier for you than dealing with this formatting stuff?

In the meantime it is.

> And why would we not have the docs at all? Writing them in the wiki does not seem to be more of an effort than doing so on GitHub.

I guess this is a matter of preference. I am at the lower end of the food chain so I take what I get.

Still in grump about Markdown. Never liked it and this shows again that it is seriously flawed. Much worse that wikitext which is facing in similar criticism.

**Comment by JeroenDeDauw** [comment]
Ok, so this question remains unanswered: **Why are some of the docs in the repo here in the first place?**

**Comment by mwjames** [comment]
> @mwjames I am afraid I have no bloody idea how to make the indentation show up on wiki correctly. I now spent more time on formatting this markdown bulsh than improving the docu which is more than ridiculous. Perhaps you can share the magic of this with me.

If I have time, I try to look at it during the weekend.

> Ok, so this question remains unanswered: **Why are some of the docs in the
> repo here in the first place?**

This ticket is not about the why so please avoid hijacking the ticket
for questioning an established practice.

PS: If the answer isn't obvious, technical documentation is kept at
the source not at some distant wiki that rarely sees any update from
anyone aside from Karsten who is the only one making an effort.

**Comment by JeroenDeDauw** [comment]
@mwjames The answer is not obvious to other people. Something you started doing and no one ever seriously looked at is only an established practice for you. 

> This ticket is not about the why so please avoid hijacking the ticket
for questioning an established practice.

... 

It became evident here that putting docs in the git repo is causing a some issues.

> technical documentation

Is this technical documentation? This is a honest question. My impression was that this is something relevant to wiki users/admins, and that this is why Karsten is putting it on the wiki. Looking at the description again briefly that is not obviously wrong to me.

**Comment by mwjames** [comment]
Again, I ask you not to hijack the ticket.

Karsten has articulate his problem with the content which was received
(as I responded) but I don't think he needs a translator for his
intention.

Yes, an established practice for those developers who have contributed
consistently over the years and not and for some who think they can
suddenly question any of those practices.

PS: First the release discussion in late 2019, and now this, I find
this very unproductive and is a waste my time.

**Comment by JeroenDeDauw** [comment]
Ah, so points of view other than your own should never be brought up? What you are doing is already perfect? And everyone automatically has the same understanding as you?

Perhaps if you want more people to contribute you should not subcomunicate they should fuck off whenever they question or criticize something you do.

**Comment by JeroenDeDauw** [comment]
Seriously. Something as elementary as the question I raised here. It is very sad you cannot deal with it constructively.

**Pull request merged**
