### PR TITLE
Move cache classes to src/

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Djeez. I already amended this 3 times. What's still broken now :|

**Comment by JeroenDeDauw** [comment]
One build randomly failed (connection issue), the rest passed.

https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/builds/47716457

**Comment by JeroenDeDauw** [comment]
Rage. Rebase needed >_>

**Comment by mwjames** [comment]
Next step is to use `onoi/cache`. I already moved the necessary cache classes (the LRU `FixedInMemoryCache`) from here to `onoi/cache` (SIL uses them to be cache client autonomous). `onoi/cache` can handle both `BagOStuff` and `Doctrine` cache client providers.

```
$cacheFactory = new Onoi\Cache\CacheFactory();
$cacheFactory->newDoctrineCache( new \Doctrine\Common\Cache\FileCache( '/C/Foo' ) );
$cacheFactory->newMediaWikiCache( new \SqlBagOStuf() );
```

**Pull request merged**
