### PR TITLE
3.1.0 footer logo

### PR DESCRIPTION
**Pull request by krabina**
This PR is made in reference to: #2376

This PR addresses or contains:
- an updated version of the footer logo based on the original logo

I don't want to take up general logo discussions. I am not a designer, but I wanted to respond to the criticism of the current footer logo. Therefore I rebuilt a version suggested here https://phabricator.wikimedia.org/T44128
so we have something in place for 3.1.0

### CODE REVIEW

**Comment by krabina** [comment]
This is what it looks like
smw_button

**Comment by JeroenDeDauw** [comment]
Old one for comparison:

image

**Comment by s7eph4n** [comment]
SVG file generated from the psd in the phab ticket using [aconvert.com](https://www.aconvert.com/image/psd-to-svg/):
https://s4.aconvert.com/convert/p3r68-cdx67/cbi16-fk0l4.svg

**Comment by krabina** [comment]
In case anybody wants to improve it, here is the GIMP file I used to create it.
[PoweredBySMW.zip](https://github.com/SemanticMediaWiki/SemanticMediaWiki/files/3029016/PoweredBySMW.zip)

**Comment by jaideraf** [comment]
In case anybody wants to follow MW footer logo, this is the SVG file:
https://commons.wikimedia.org/wiki/File:Powered_by_MediaWiki.svg

**Comment by jaideraf** [comment]
I am not a designer, either, but I am in favour of removing the "Powered By" from the bottom to fit in other languages as well. Besides, "Powered By" is already on the left side, in the MW buttom. Revoving it, bring us space for writing "Semantic" improving the geral reading of the buttom.

**Comment by krabina** [comment]
Interesting idea. I didn't think about the language at all. However, the MediaWiki footer icon also shows the "powered by" and is not available in other languages...

**Comment by krabina** [comment]
Here is an alternative without the poweredby:

smw_poweredby1

**Comment by jaideraf** [comment]
I prefer a version with the MW background button. I made this:

Powered_by_Semantic_MediaWiki

**Comment by krabina** [comment]
fine with me. the font could be a bit larger, maybe.

**Comment by jaideraf** [comment]
> the font could be a bit larger, maybe.

Powered_by_Semantic_MediaWiki2

I had to remove the small yellow balls from the logo in order to acomodate the text. I also changed the font from Gill Sans [0] to Montserrat [1] just like the WMF have changed [3][4] (it seems the Gill Sans is copyrighted while the Montserrat has a Open Font License).

For comparison:

both

The source files: [PoweredBySMW.zip](https://github.com/SemanticMediaWiki/SemanticMediaWiki/files/3244945/PoweredBySMW.zip)



[0] https://fonts.google.com/?query=Gill+Sans
[1] https://fonts.google.com/specimen/Montserrat
[3] https://foundation.wikimedia.org/wiki/Wikimedia_visual_identity_guidelines/Archived#Fonts
[4] https://foundation.wikimedia.org/wiki/Visual_identity_guidelines#11

**Comment by krabina** [comment]
thank you, this is great! can be merged in my opinion

**Comment by mwjames** [comment]
We should try to create a SVG as the base64 takes quite some space as encoding for an PNG (or similar formats).

> I had to remove the small yellow balls from the logo in order to acomodate the text. I also changed the font from Gill Sans [0] to Montserrat [1] just like the WMF have changed [3][4] (it seems the Gill Sans is copyrighted while the Montserrat is under an Open Font License).

Personal opinion, the font seems fairly bold (meaning the weight) would it possible to lighten font weight a bit?

**Comment by mwjames** [comment]
I just killed the Travis-CI run for this PR to avoid hogging the resource since the content is not testable. When working with untestable changes such as documentation etc. one should use `[skip ci]` in the PR description.

**Comment by jaideraf** [comment]
>  would it possible to lighten font weight a bit?

Powered_by_Semantic_MediaWiki

Now using the Montserrat SemiBold font.
Files: [Powered_by_Semantic_MediaWiki.zip](https://github.com/SemanticMediaWiki/SemanticMediaWiki/files/3245164/Powered_by_Semantic_MediaWiki.zip)
The SVG version is in the zip file.

**Comment by krabina** [comment]
> We should try to create a SVG as the base64 takes quite some space as encoding for an PNG (or similar formats).

ok, but then I don't know what to do. The svg is in the zip file. I was happy to find the place where the DataURIs are done (have never heard of dataURIs before). I thought this is to make it faster, as formerly there was an image directory where the icon was located. Now there is no image directory anymore.

I don't know what to do now. Please delete this PR and make it right. I am not able to really help out as it seems...

**Comment by krabina** [comment]
ok, now I uploaded the svg to the dataURI converter...

**Comment by mwjames** [comment]
> We should try to create a SVG as the base64 takes quite some space as encoding for an PNG (or similar formats).

Looking at https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3875/commits/023f9447048a3ad3a2538d4a590b72ce88d78968 it seems the encoded SVG is larger (by some dimensions) than the previous PNG, so maybe we should stick with an encoded PNG.

**Comment by krabina** [comment]
done

**Comment by mwjames** [comment]
Using the latest version (242c2d8), one can see that the SMW logo is blurred compared to the crisp MW logo.

image

**Comment by jaideraf** [comment]
The PNG image uploaded in the [comment above](https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/3875#issuecomment-498061519) seems good (or at least better) to me. I do not know how to solve this (encoded or not be be encoded, why is blurred, etc.).

**Comment by mwjames** [comment]
The blurring is caused by the icon button being width 88 px height 32 px while the MW logo is set to 88x31 (see [0]).

[0] https://github.com/wikimedia/mediawiki/blob/2e1ac38485b9c78890944413cba074474c06bd34/includes/skins/SkinTemplate.php#L432-L443

**Comment by jaideraf** [comment]
Now 88 x 31 px:

Powered_by_Semantic_MediaWiki

Files: [Powered_by_Semantic_MediaWiki.zip](https://github.com/SemanticMediaWiki/SemanticMediaWiki/files/3245231/Powered_by_Semantic_MediaWiki.zip)

**Comment by mwjames** [comment]
> Now 88 x 31 px:

Looks better.

image

**Comment by mwjames** [comment]
@krabina Your change doesn't work since we need it as plain src string as seen in 787e829.

**Comment by krabina** [comment]
oh, sorry. please delete it.

**Comment by kghbln** [comment]
I see this still as an interim solution, however since I fail to attend to this including other problems that are still persisting, I am all for merging this adapted version.

**Comment by JeroenDeDauw** [comment]
> I see this still as an interim solution

Why?

**Comment by kghbln** [comment]
> Why?

It is still 3D. I personally would like to see a 2D logo which is more adaptable. Anyways this goes beyond the scope of this pull

**Comment by mwjames** [comment]
> Merged #3875 into master.

Backtrace:

#0 ...\extensions\SemanticMediaWiki\src\Setup.php(86):
SMW\Setup->registerFooterIcon(array, string)
#1 ...\extensions\SemanticMediaWiki\SemanticMediaWiki.php(101):
SMW\Setup->init(array, string)
#2 ...\includes\Setup.php(940): SemanticMediaWiki::onExtensionFunction()
#3 ...\includes\WebStart.php(88): require_once(string)
#4 ...\index.php(39): require(string)
#5 {main}

There is an issue with the last change, the array [] is missing a `;`
at the end!

**Comment by kghbln** [comment]
What the bl... h...

**Pull request merged**
