### PR TITLE
NamespaceManager avoid reset of user settings, refs 2439

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2439

This PR addresses or contains:

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by mwjames** [comment]
Back-ported to 2.5.x with 8c9c4c3.

**Comment by kghbln** [comment]
@mwjames Hmm ... there is still something in the water. I have added

```php
$wgNamespacesToBeSearchedDefault = [
        NS_MAIN => true,
        NS_FILE => true,
	SMW_NS_PROPERTY => true
        ];
```
to "LocalSettings.php" for sandbox but now neither Property nor Concept are searched by default.

**Comment by mwjames** [comment]
>  there is still something in the water. I have added

Are you sure because my local test showed the opposite. The change was made so that any setting the exists are not overridden and in case they don't exists are added with a true value.

You can check the setting by adding `var_dump( $wgNamespacesToBeSearchedDefault )` to [0].

[0] https://github.com/wikimedia/mediawiki/blob/c64e2b3fede0d7793cfefa0ff67f2ddad67febd9/includes/user/User.php#L1563-L1595

**Comment by kghbln** [comment]
Ah, oops indeed. Now it is also working in sandbox. Probably the change still somehow had to propagate through caching etc. Sorry for the noise!

**Comment by kghbln** [comment]
I may note that `$wgNamespacesToBeSearchedDefault` must be done after the inclusion of SMW as far as semantic namespaces are concerned. Otherwise one will get as to be expected the following PHP notices:

```
Notice: Use of undefined constant SMW_NS_PROPERTY - assumed 'SMW_NS_PROPERTY' in /w/LocalSettings.php on line xxx
Notice: Use of undefined constant SMW_NS_CONCEPT - assumed 'SMW_NS_CONCEPT' in /w/LocalSettings.php on line xxx
```

**Pull request merged**
