### PR TITLE
Inline use of wfShowingResults

### PR DESCRIPTION
**Pull request by octfx**
In reference to #5335

### CODE REVIEW

**Review by JeroenDeDauw — APPROVED** [review]

**Comment by jaideraf** [comment]
It needs a compatibility check to support MW 1.35.

**Comment by octfx** [comment]
> It needs a compatibility check to support MW 1.35.

The code has not changed since [REL1_35](https://github.com/wikimedia/mediawiki/blob/02449a43063791085c4a5abb793e11875e6ad940/includes/GlobalFunctions.php#L1440) :)

**Comment by jaideraf** [comment]
> The code has not changed since [REL1_35](https://github.com/wikimedia/mediawiki/blob/02449a43063791085c4a5abb793e11875e6ad940/includes/GlobalFunctions.php#L1440) :)

Weird, in this pull https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5338 MW 1.35 tests were passing.

**Comment by JeroenDeDauw** [comment]
Is unrelated. Filed at https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/5346

**Pull request merged**
