### PR TITLE
SearchByProperty replacement/escaping of -/_, refs 1594, 1744

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1594, #1744

This PR addresses or contains:
- Should address #1744 and [0]
- As for [0], the underscore `_` is generally equal to ` ` in MediaWiki when it is a `Page` type which is the reason why it can be used interchangeably, yet for a `Text` type the interpretation is different 

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

[0] http://wikimedia.7.x6.nabble.com/SMW-Special-SearchByProperty-fails-when-values-contain-underscores-td5069156.html

### CODE REVIEW

**Comment by mwjames** [comment]
- Page type: `[[SomeProperty::a_b]]` === `[[SomeProperty::A_b]]` === `[[SomeProperty::A b]]` (given that `$wgCapitalLinks=true`)
- Text type: `[[SomeProperty::a_b]]` !== `[[SomeProperty::A b]]`  !== `[[SomeProperty::A_b]]`

**Comment by mwjames** [comment]
@kghbln Not sure this needs to be highlighted in the documentation or not.

**Comment by mwjames** [comment]
http://sandbox.semantic-mediawiki.org/wiki/Search_by_property_Test_Page_1

**Comment by jongfeli** [comment]
Hello @mwjames, I did some more tests on the SMW sandbox. 

### Setup and configuration
- SMW version: 2.5.0-alpha (7c6e0d8) 21:43, 12 November 2016
- MW version: 	1.28.0-rc.0 (7625c75) 15:14, 3 November 2016
- DB (MySQL etc.): 10.0.28-MariaDB-1~jessie

All works fine except when the search string contains `-20`. See some value examples on [0] and [1]

[0] http://sandbox.semantic-mediawiki.org/wiki/Attribut:Search_by_property_value_2
[1] http://sandbox.semantic-mediawiki.org/wiki/Attribut:Search_by_property_value_3

**Comment by mwjames** [comment]
> All works fine except when the search string contains -20. See some value examples on [0] and [1]

Yes, because you found exactly the pair that contains an internal escaping sequence for special chars. In #2031 I went to some length to make it possible to distinguish auto-generated from manual entered URLs and added 10+ tests on various combination as found in [0].

[0] http://sandbox.semantic-mediawiki.org/wiki/Issue/2031

**Comment by jongfeli** [comment]
Thanks @mwjames. It works like a charm now.

**Pull request merged**
