### PR TITLE
Property page, move usage count display to tab

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

- Moves the count display from the top indicator to an individual tab

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### Example

image

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames This does not [(yet) work for special properties](https://sandbox.semantic-mediawiki.org/wiki/Attribut:Boolean)

**Comment by mwjames** [comment]
> @mwjames This does not [(yet) work for special
> properties](https://sandbox.semantic-mediawiki.org/wiki/Attribut:Boolean)

I've seen this before which relates to predefined properties (and
appears in connection with the content language) and is unrelated to
the current PR.

**Comment by kghbln** [comment]
> I've seen this before which relates to predefined properties (and appears in connection with the content language) and is unrelated to the current PR.

Ok. I guess this is on your radar. :)

**Comment by mwjames** [comment]
>Ok. I guess this is on your radar. :)

I believe that to be fixed with #3458.

**Comment by kghbln** [comment]
> I believe that to be fixed with #3458.

Affirmative. Thanks a lot!

**Comment by kghbln** [comment]
@mwjames Another thing I just realize. The information about a property being user defined or deployed by the software went missing. I guess this could still be a useful information in the old spot. Moreover we still have the info on the page being protected in this area.

**Comment by mwjames** [comment]
> Another thing I just realize. The information about a property being user defined or deployed by the software went missing. I guess this could still be a useful information in the old spot.

I thought about it but for predefined properties you always have the intro explaining that it is in fact a predefined property so creating an extra indicator seems somewhat redundant.

> Moreover we still have the info on the page being protected in this area, which is good.

The protection is displayed as indicator on the usual place because the state information is separate from the property page.

**Comment by kghbln** [comment]
> I thought about it but for predefined properties you always have the intro explaining that it is in fact a predefined property so creating an extra indicator seems somewhat redundant.

Fair enough, after a second thought I agree. :)

> The protection is displayed as indicator on the usual place because the state information is separate from the property page.

Right. I just mentioned it to convey that the spot would still be useful to put stuff there.

**Pull request merged**
