### PR TITLE
Migrate special property message keys to new naming schema

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to:
* https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2859
* https://github.com/SemanticMediaWiki/SemanticCite/issues/58

This PR addresses or contains:
- Changed message keys for special properties

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I believe to have covered all of them. A thumbs up for the merge will be cool. Thanks!

**Comment by mwjames** [comment]
+1

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/TestCases/p-0438.json has to be adapted in a follow up pr too since this one is currently failing.

**Comment by kghbln** [comment]
Ah, I believe to know why it is failing. With the latest update from twn we got the -pa- string in the message key back, which is breaking the test.

**Comment by kghbln** [comment]
Affirmative.

**Comment by kghbln** [comment]
@Nikerabbit Ready to go.

**Pull request merged**
