### PR TITLE
Replace use of Parser::$mStripState, deprecated in 1.35

### PR DESCRIPTION
**Pull request by cscott**
The replacement, Parser::getStripState(), was added to MediaWiki in
1.34.  Accordingly, the minimum required version for this extension
was bumped from 1.32 to 1.34.

Bug: T275160

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
CI: ok

**Comment by jaideraf** [comment]
@JeroenDeDauw except the `extensions.json` conflict (`"MediaWiki": ">= 1.34"`, now `"MediaWiki": ">= 1.35"`), couldn't this be merged by now?

**Comment by JeroenDeDauw** [comment]
There still is a conflict apparently

**Comment by JeroenDeDauw** [comment]
Fixed by https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/7402ca36ffa77f0c5c40478f247eaa5cb848d63e

**Pull request closed without merging**
