### PR TITLE
Add query parameters to profile

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

- Add ability to record query parameters, this would subsequently enable SMW to recreate query results using a background job

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
Without knowing the parameters, running queries independent of the MW parser is not possible because sorting and limit directly influence on how and which results are fetched from the backend, but by recording those it will enable SMW to run a background job (which is not part of this PR) without the need to parse a page in order to recreate the `Query`/`Description` object.

image

**Comment by kghbln** [comment]
This one requires to run "setupStore.php" so ...
```
Checking table smw_fpt_askpa ...
   Table not found, now creating...
   ... done.
```

**Comment by kghbln** [comment]
@mwjames I have just [enabled query profiling for duration and parameters](https://sandbox.semantic-mediawiki.org/w/index.php?title=SMW_Sandbox:Setup_information&curid=4&diff=5705&oldid=5702). However parameters do not seem to get through like for the query on [this page](https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Parcourir/:Cities)

**Comment by kghbln** [comment]
[Documended on wiki](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgQueryProfiler&type=revision&diff=49524&oldid=32161)

**Comment by kghbln** [comment]
@mwjames Hmm, even after rebuilding data nothing shows up for this special property. Is there a trick or an issue?

**Comment by mwjames** [comment]
> Hmm, even after rebuilding data nothing shows up for this special property. Is there a trick or an issue?

I know, I have to make a small adjustment. A PR is coming in soon ... stay tuned.

**Comment by kghbln** [comment]
> A PR is coming in soon ... stay tuned.

Ah, no worries.

**Comment by mwjames** [comment]
> Hmm, even after rebuilding data nothing shows up for this special property. Is there a trick or an issue?

This PR was missing an integration test and with it a misinterpretation of a setting which has now been addressed in #2305.

**Comment by kghbln** [comment]
> This PR was missing an integration test and with it a misinterpretation of a setting which has now been addressed in #2305.

Great! Now working cool!

**Pull request merged**
