### PR TITLE
Add TableBuilder::optimize, refs 1940

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1940

This PR addresses or contains:

- Runs the `ANALYZE` (and `OPTIMIZE` where available) command during the setup to ensure that "...key distribution and stores the distribution so that the query planner can use these statistics to help determine the most efficient execution plans for queries."

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln This is obligatory since most users won't run these commands ever and depending on the state of the DB can improve the query planning as outlined in the docs.

- https://dev.mysql.com/doc/refman/5.7/en/analyze-table.html
- https://dev.mysql.com/doc/refman/5.7/en/optimize-table.html

It is to be noted that depending on the size of the tables it can take a bit to run through them. The output will be accompanied by:

```
Running table optimization.
   Table smw_object_ids ...
   ... analyze, optimize done.
   Table smw_concept_cache ...
   ... analyze, optimize done.
   Table smw_query_links ...
   ... analyze, optimize done.
   Table smw_ft_search ...
   ... analyze, optimize done.
```

**Comment by kghbln** [comment]
@mwjames This is done every time "setupStore.php" is executed? So it will be possible to trigger this once in a while...

**Comment by mwjames** [comment]
> This is done every time "setupStore.php" is executed?

Yes.

> So it will be possible to trigger this once in a while...

You mean besides running `setupStore.php` or `update.php`?

**Comment by kghbln** [comment]
> You mean besides running "setupStore.php" or "update.php"?

I understand that you can run either of them, however since this is SMW specific preferably "setupStore.php" making it to a semi official "gardening" script like the others we have.

**Comment by mwjames** [comment]
> SMW specific preferably "setupStore.php" making it to a semi official "gardening" script like the others we have.

:+1: 

The first time this is run you'll see a significant lag which is an indication that the DB has to work a bit more than usual.

The PR is just a by-product for an upcoming change where the specific "optimize" part was isolated and put in here.

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Database/Table_optimization

**Pull request merged**
