### PR TITLE
MW 1.36: Fix database import during maintenance/update.php

### LINKED ISSUE #5079: Argument 2 passed to WikiPage::doUserEditContent() must implement interface MediaWiki\Permissions\Authority, null given
### Setup

- SMW version:  4.0.0-alpha (a2e0c03)
- MW version: 1.38.0-alpha (629c5e2)
- PHP version: 7.4.23
- DB system (MySQL, Blazegraph, etc.) and version: 10.1.48-MariaDB-0+deb9u2

### Issue

Detailed description of the issue and a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) if applicable:

```
* [70312cd9fa3f5539391c6815] [no req]   TypeError: Argument 2 passed to WikiPage::doUserEditContent() must implement interface MediaWiki\Permissions\Authority, null given, called in /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php on li
ne 165                                                                                                   
Backtrace:                                                                                               
from /vagrant/mediawiki/includes/page/WikiPage.php(1914)                                                 
#0 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(165): WikiPage->doUserEditContent()                                                                        
#1 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(141): SMW\Importer\ContentCreators\TextContentCreator->doCreateContent()                                   
#2 /vagrant/mediawiki/includes/libs/rdbms/database/Database.php(4347): SMW\Importer\ContentCreators\TextContentCreator->SMW\Importer\ContentCreators\{closure}()                                                  
#3 /vagrant/mediawiki/includes/libs/rdbms/database/Database.php(4136): Wikimedia\Rdbms\Database->runOnTransactionIdleCallbacks()                                                                                  
#4 /vagrant/mediawiki/includes/libs/rdbms/database/DBConnRef.php(68): Wikimedia\Rdbms\Database->onTransactionCommitOrIdle()                                                                                       
#5 /vagrant/mediawiki/includes/libs/rdbms/database/DBConnRef.php(627): Wikimedia\Rdbms\DBConnRef->__call()                                                                                                        
#6 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Connection/Database.php(822): Wikimedia\Rdbms\DBConnRef->onTransactionCommitOrIdle()                                                             
#7 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/TextContentCreator.php(142): SMW\MediaWiki\Connection\Database->onTransactionIdle()                                               
#8 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/ContentCreators/DispatchingContentCreator.php(75): SMW\Importer\ContentCreators\TextContentCreator->create()                                      
#9 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(127): SMW\Importer\ContentCreators\DispatchingContentCreator->create()                                                               
#10 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Importer/Importer.php(105): SMW\Importer\Importer->doImport()                                                                                             
#11 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1476): SMW\Importer\Importer->runImport()                                                                                             
#12 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(338): SMW\MediaWiki\Hooks->onAfterCreateTablesComplete()                                                                                          
#13 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()                                                                                     
#14 /vagrant/mediawiki/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run()             
#15 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/MediaWiki/HookDispatcher.php(276): Hooks::run()  
#16 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/Installer.php(279): SMW\MediaWiki\HookDispatcher->onInstallerAfterCreateTablesComplete()                                                         
#17 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/SQLStore/SQLStore.php(451): SMW\SQLStore\Installer->install()                                                                                             
#18 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Store.php(489): SMW\SQLStore\SQLStore->setup()   
#19 /vagrant/mediawiki/includes/installer/DatabaseUpdater.php(533): SMW\Store::setupStore()              
#20 /vagrant/mediawiki/includes/installer/DatabaseUpdater.php(501): DatabaseUpdater->runUpdates()        
#21 /vagrant/mediawiki/maintenance/update.php(193): DatabaseUpdater->doUpdates()                         
#22 /vagrant/mediawiki/maintenance/doMaintenance.php(108): UpdateMediaWiki->execute()                    
#23 /vagrant/mediawiki/maintenance/update.php(264): require_once(string)                                 
#24 {main}          
```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

1. Install SMW afresh on MW 1.38
2. Run `maintenance/update.php`

# Technical notes

When running `maintenance/update.php` we are importing following JSON files in data directory:
1. File list,
  * `SemanticMediaWiki/data/import/smw.groups.json`
  * `SemanticMediaWiki/data/import/groups/schema.json`
  * `SemanticMediaWiki/data/import/groups/predefined.properties.json`
  * `SemanticMediaWiki/data/import/smw.vocab.json`
2. The `ContentModeller` uses `import_performer` from the JSON file to determine the user performing the import. None of these files define this property.
3. `doEditContent` used to fallback to the global user, but `doUserEditContent` does not. Introduced in c6274137e116a108d1881da42db157522edfba8a

We could manually define the `import_performer` in these files to be the maintenance user but that would require using the string `Maintenance script` in the JSON files.

### PR DESCRIPTION
**Pull request by Abijeet**
Fixes TypeError: Argument 2 passed to WikiPage::doUserEditContent()
must implement interface MediaWiki\Permissions\Authority, null
given SemanticMediaWiki#5079

Also enable CI for MW 1.36

Fixes #5079, #5110

### CODE REVIEW

**Comment by Abijeet** [comment]
This PR is made to fix two exceptions noticed when running `maintenance/update.php`:

1. See #5079 
2. `TypeError: Argument 1 passed to SMW\Property\RestrictionExaminer::setUser() must be an instance of User, instance of StubGlobalUser given, called in /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Services/DataValueServiceFactory.php on line 188`. Stack trace below,

Stacktrace 
```
[f038531b3b706d9cc150527c] [no req]   TypeError: Argument 1 passed to SMW\Property\RestrictionExaminer::setUser() must be an instance of User, instance of StubGlobalUser given, called in /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Services/DataValueServiceFactory.php on line 188
Backtrace:
from /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Property/RestrictionExaminer.php(52)
#0 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Services/DataValueServiceFactory.php(188): SMW\Property\RestrictionExaminer->setUser()
#1 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/DataValues/PropertyValue.php(336): SMW\Services\DataValueServiceFactory->getPropertyRestrictionExaminer()
#2 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/DataValueFactory.php(328): SMW\DataValues\PropertyValue->isRestricted()
#3 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Parser/AnnotationProcessor.php(98): SMW\DataValueFactory->newDataValueByText()
#4 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Parser/InTextAnnotationParser.php(412): SMW\Parser\AnnotationProcessor->newDataValueByText()
#5 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Parser/InTextAnnotationParser.php(389): SMW\Parser\InTextAnnotationParser->addPropertyValue()
#6 /vagrant/mediawiki/extensions/SemanticMediaWiki/src/Parser/InTextAnnotationParser.php(353): SMW\Parser\InTextAnnotationParser->process()
```

**Comment by Abijeet** [comment]
While this solves the problem with running tests on MW 1.36, it appears that GitHub is cancelling the CI after 5 minutes as per: https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run (**See point 5**)

@JeroenDeDauw - I'll look at improving the speed for the CI in a separate PR.

**Comment by gesinn-it** [comment]
@Abijeet can you try to change CI to allow failure for parts of the matrix like 1.36+? See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

**Comment by Abijeet** [comment]
> @Abijeet can you try to change CI to allow failure for parts of the matrix like 1.36+? See: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error

Done.

**Pull request merged**
