### PR TITLE
Fix for storing and formatting dates in a compatible way with ISO8601 & XML Schema. Allowing ISO 8601 input

### PR DESCRIPTION
**Pull request by toniher**
This PR is made in reference to: #2218 and #2233 

This PR includes:
* Tests added: p-0450.json and p-0451.json.
* Tests modified: p-0413.json, p-0414.json, MediaWiki/Import/TimeDataTypeTest.php 

Now ISO dates are following the convention that 1 BC is 0000 and 2 BC is -0001, and so on...

Special care should be taken when wikis containing BC dates would be updated.

### CODE REVIEW

**Comment by kghbln** [comment]
A squash and merge classic. :) Thanks a lot for your pull!

**Comment by toniher** [comment]
Let me know if I could do anything else or more tests needed in your opinion!

**Comment by mwjames** [comment]
Before I continue, let me thank you for the effort and dedication (especially in dealing with the tests).

> Let me know if I could do anything else or more tests needed in your opinion!

At a quick glance it looks ok but I want to review the "Handle offset" in `newFromISO` to understand what is required here (and if there isn't a better way).

 > Special care should be taken when wikis containing BC dates would be updated.

Since we would break the RDF output (which doesn't say this is wrong and apparently no one has complained about the difference in BCE/CE handling before), I'd rather make the break with 3.0 otherwise we would require a BC (backwards compatibility) switch in order for people to use the existing RDF format.

It may seem nitpicky but a break is a break and we either provide a migration path for the change or break on a version (oppose to what normally happens in the MediaWiki vicinity) that allows for that to happen which according to semver [0] would be 3.x.

Of course, if you say you need the feature now and by 2.5 then we need to do something to avoid a format break.

[0] http://semver.org/ "... MAJOR version when you make incompatible API changes ..." (API changes include exchange to formats like JSON, XML, or RDF including where a format or its data no longer result in the same interpretation)

**Comment by toniher** [comment]
I agree that more work may be needed for time offsets (timezones). What I'm doing in the code above is practically ignoring that information when retrieved (actually merging the value into its UTC equivalent) from a ISO 8601 input. This means that, let's say, when the output is rendered in RDF, the detail about the timezone is lost. That's bad and I think I would rather change it (more testing would be needed).

I see your point regarding compatibility changes. However, especially if 3.0 may become too far away, I think it's worth to see if present situation can be improved. 
As a compromise, do you think it's worth a parameter that could let administrator choose whether 1 BC is 0000 or -0001 would be enough (keeping current -0001 as default option)? Being strict another parameter may also be needed for '-' vs '--' (or '−' proper) and even for zero left padding...

**Comment by mwjames** [comment]
> As a compromise, do you think it's worth a parameter that could let administrator choose whether 1 BC is 0000 or -0001 

If want this in 2.5 then we require something that leaves the output as is and have a setting to change to the new output format.

PS: I had to do a similar thing to support the IRI export [0] and avoid BC for existing outputs.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/DefaultSettings.php#L1069-L1083.

**Comment by kghbln** [comment]
@toniher In case you have some spare time this summer it will be great if you could work on this. :)

**Comment by kghbln** [comment]
This pull has not seen any updates in basically two years. Thus closing to make room for another effort.

**Pull request closed without merging**
