### PR TITLE
Test separator smw_decseparator/smw_kiloseparator key, refs 2510

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2510

This PR addresses or contains:

- Tests a required pair match when one of the `smw_decseparator`, `smw_kiloseparator` key is present
- Tests that when `smw_decseparator` are `smw_kiloseparator` exist, maintained values are different from each other

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln This fails with:

```
...............................................................  63 / 490 ( 12%)
............................................................... 126 / 490 ( 25%)
.............................F......F..............F........... 189 / 490 ( 38%)
............................................................... 252 / 490 ( 51%)
............................................................... 315 / 490 ( 64%)
............................................................... 378 / 490 ( 77%)
............................................................... 441 / 490 ( 90%)
.................................................

Time: 6.37 seconds, Memory: 20.00MB

There were 3 failures:

1) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "nb.json" ('D:\xampp\htdocs\mw-master\ext...b.json')
Failed on nb.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

D:\xampp\htdocs\mw-master\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\I18nMsgKeyIntegrityTest.php:38
D:\xampp\htdocs\mw-master\maintenance\doMaintenance.php:111

2) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "oc.json" ('D:\xampp\htdocs\mw-master\ext...c.json')
Failed on oc.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

D:\xampp\htdocs\mw-master\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\I18nMsgKeyIntegrityTest.php:38
D:\xampp\htdocs\mw-master\maintenance\doMaintenance.php:111

3) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "pt-br.json" ('D:\xampp\htdocs\mw-master\ext...r.json')
Failed on pt-br.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.
```

**Comment by kghbln** [comment]
```
1) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "arz.json" ('/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/i18n/arz.json')
Failed on arz.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Integration/System/I18nMsgKeyIntegrityTest.php:39
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:111
```
Why doesn't it fail for "ar". There we only have a "smw_kiloseparator" maintained, too: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/i18n/ar.json#L97

**Comment by mwjames** [comment]
> Why doesn't it fail for "ar". There we only have a "smw_kiloseparator" maintained, 

Good question, need to check this.

**Comment by kghbln** [comment]
> EDIT: Probably only the first fall-back is considered and since "ar" is using "en" we have a valid pair here.

Probably I added the EDIT too late. I think the fall-back is not cascading from arz to ar to en but just from arz to ar. Since there is nothing in ar ...

In `/language/messages/messagesxx.php` only the direct fall-back is maintained.

**Comment by mwjames** [comment]
> In /language/messages/messagesxx.php only the direct fall-back is maintained.

Actually, we don't do any magic here, it just reads the JSON file, looks for the key, and determines whether it is valid or not. No fallback or any other kind of voodoo.

**Comment by kghbln** [comment]
> In /language/messages/messagesXx.php only the direct fall-back is maintained.

[ar does not have a explicit fallback](https://phabricator.wikimedia.org/source/mediawiki/browse/master/languages/messages/MessagesAr.php) so I can imagine that MediaWiki takes en magically.

**Comment by kghbln** [comment]
> Actually, we don't do any magic here, it just reads the JSON file, looks for the key, and determines whether it is valid or not. No fallback or any other kind of voodoo.

So I was thinking to complicated. In this case there is indeed something in the water.

**Comment by mwjames** [comment]
> In this case there is indeed something in the water.

The issue was that since we do a recursive iteration on the directory we also found `extra/ar.json` which replaced the previous file reference. This has been fixed and now will generate:

```
There were 5 failures:

1) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "ar.json (dbb53)" ('...\ext...r.json')
Failed on ar.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

...\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\I18nMsgKeyIntegrityTest.php:38
...\maintenance\doMaintenance.php:111

2) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "arz.json (edf56)" ('...\ext...z.json')
Failed on arz.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

...\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\I18nMsgKeyIntegrityTest.php:38
...\maintenance\doMaintenance.php:111

3) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "nb.json (8e2b9)" ('...\ext...b.json')
Failed on nb.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

...\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\I18nMsgKeyIntegrityTest.php:38
...\maintenance\doMaintenance.php:111

4) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "oc.json (40354)" ('...\ext...c.json')
Failed on oc.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.

...\extensions\SemanticMediaWiki\tests\phpunit\Integration\System\I18nMsgKeyIntegrityTest.php:38
...\maintenance\doMaintenance.php:111

5) SMW\Tests\System\I18nMsgKeyIntegrityTest::testDecKiloSeparatorMsgKeySetting with data set "pt-br.json (de555)" ('...\ext...r.json')
Failed on pt-br.json with an incomplete pair of smw_decseparator/smw_kiloseparator.
Failed asserting that false is true.
```

Once those have been fixed, the PR can be merged.

**Comment by kghbln** [comment]
I extended the docu for both system messages:
* [kilo](https://translatewiki.net/w/i.php?title=MediaWiki%3ASmw_kiloseparator%2Fqqq&type=revision&diff=7435876&oldid=3456731)
* [dec](https://translatewiki.net/w/i.php?title=MediaWiki%3ASmw_decseparator%2Fqqq&type=revision&diff=7435873&oldid=3456730)

**Comment by kghbln** [comment]
So I now added the respective separators by doing educated guesses. Interestingly "Smw decseparator/oc" was present on twn but no export to the repo so I just touched the string. This one should be mergable on Thursday after the translation updates rolled in.

**Comment by kghbln** [comment]
The translations rolled in via https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/e7dea7f0349799fdfee307e44c8f8c184a945e7b. Needed to do a tweak to arz but this does not matter.

**Comment by kghbln** [comment]
Ah, this was senior. :|

**Pull request merged**
