### PR TITLE
Add TransientStatsdCollector

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1251

This PR addresses or contains:

- Collects statistical data in a temporary store for as long as the `CACHE_DB` exists and will vanish after a restart
- Implements the collection of data for the `QueryCache` usage

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
Whether the "QueryCache" has operational relevance or not, it needs data to make that decision. This PR will allow to collect some of them and can subsequently be viewed on `Special:SemanticMediaWiki&action=stats`.

 image

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by mwjames** [comment]
The collection of mentioned statistics is tight to the `smwgQueryResultCacheType` setting.

**Comment by kghbln** [comment]
I am not getting a segmentation fault. smwgQueryResultCacheType shows up with -1 on special SMW though it is set to CACHE_ANYTHING.

**Comment by mwjames** [comment]
> I am now getting a segmentation fault.

The setting should be unrelated. Any output or stack trace on the seg fault?

**Comment by kghbln** [comment]
> Any output or stack trace on the seg fault?

No, all the logs are empty or show unrelated stuff. Time for xdebug.

**Comment by mwjames** [comment]
> No, all the logs are empty or show unrelated stuff. Time for xdebug.

Just a second, let's try this https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/513432a7841a11371ca9d8789abf5c6abd637872.

**Comment by kghbln** [comment]
[This edit](https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue%2F2036&action=historysubmit&type=revision&diff=4730&oldid=4729) triggered the segmentation fault again and still now show even with xdebug enabled. Error reporting is set to `error_reporting( E_ERROR );` so we should get something this massive.

Will now update.

**Comment by kghbln** [comment]
> Just a second, let's try this 513432a.

- Updating mediawiki/semantic-media-wiki dev-master (da485ad => 7f351b7)
- Doing [this edit](https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue%2F2036&type=revision&diff=4731&oldid=4730)

-> No segmentation fault no more! :+1:

**Comment by mwjames** [comment]
Let's monitor the situation for a while.

As to what changed:

- `TransientStatsdCollector` is injected into class to collect data during a request (view, API etc.)
- When the invoking class losses its scope (and triggers a `__destruct`) we will use the event to read the current stats for the given ID, compute the difference, increments, medians, and update the storage
- With 513432a `TransientStatsdCollector::recordStats` is made an isolated encapsulated process using a callback instead of "just" executing the `recordStats` as part of the `__destruct`

**Comment by kghbln** [comment]
> Let's monitor the situation for a while.

Indeed, I will report back as soon as a worry arises again.

**Comment by kghbln** [comment]
I am afraid that this issue is still present. I just outsmarted myself by having a look at the apache log and here we are:

```
[Sat Nov 26 22:16:08.199569 2016] [:error] [pid 20912] [client 91.65.247.81:64365] PHP Fatal error:  Access to undeclared static property: MediaWiki\\Logger\\LegacyLogger::$levelMapping in /.../w/includes/debug/logger/LegacyLogger.php on line 98, referer: https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/2037/Has_property_description&action=edit
[Sat Nov 26 22:16:08.249514 2016] [:error] [pid 20912] [client 91.65.247.81:64365] PHP Fatal error:  Cannot redeclare wfEntryPointCheck() (previously declared in /.../w/includes/PHPVersionCheck.php:32) in /.../w/includes/PHPVersionCheck.php on line 32, referer: https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/2037/Has_property_description&action=edit
[Sat Nov 26 22:16:08.300470 2016] [:error] [pid 20878] [client 91.65.247.81:65261] PHP Fatal error:  Cannot redeclare wfGetRusage() (previously declared in /.../w/includes/profiler/ProfilerFunctions.php:35) in /.../w/includes/profiler/ProfilerFunctions.php on line 35, referer: https://sandbox.semantic-mediawiki.org/w/index.php?title=Issue/2037/Has_property_description&action=edit
```
This is what is happening at the times where a segmentation fault is appearing.

**Comment by mwjames** [comment]
> This is what is happening at the times when a segmentation fault is appearing.

Let me think about this because locally I cannot replicate those messages (and the seg fault).

**Comment by mwjames** [comment]
>  PHP Fatal error:  Access to undeclared static property: MediaWiki\\Logger\\LegacyLogger::$levelMapping 

Not much I can do on those (they are part of MW) and after some deliberation I decided to go for a different approach as outlined in #2054.

**Comment by kghbln** [comment]
> I decided to go for a different approach as outlined in #2054.

This appears to be the way to go. Have not done much editing on the wiki but so far no more of these nasty seg faults popped up. Still in case they re-emerge ... Keeping fingers crossed though.

**Pull request merged**
