### PR TITLE
$smwgLinksInValues to support Obfuscator approach

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1963

This PR addresses or contains:

- Add `SMW_LINV_OBFU` as approach to resolve LinkInValues, `SMW_LINV_PCRE` is kept to avoid BC breakages for users who have `$smwgLinksInValues` enabled

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
[0] is provided to enable parsing of so called "LinksInValues" (`[[SomeProperty::Foo [[link]] in value]]`). The problem with the current PCRE approach is that PHP can easily crash #1963 and is therefore a feature normally disabled despite its usefulness.

To avoid mentioned issues, a different approach is sought to be introduced by this PR including a different interpretation of the `$smwgLinksInValues` setting.

`$smwgLinksInValues` will except `false`, `true` (deprecated with 2.5 to keep BC, use `SMW_LINV_PCRE` instead), `SMW_LINV_PCRE`, `SMW_LINV_OBFU`.

The following text is used to test the `SMW_LINV_OBFU` approach:

`
[[Has text::[[Lorem ipsum]] dolor sit amet, [[Has page::consectetur adipiscing elit]]. In [http://example.org/eleifend eleifend] cursus dignissim. Suspendisse potenti. [[Has page::Curabitur aliquet|Bar]] malesuada ex sed efficitur. [[Nullam id ante|Foo]] eget lacus rutrum tincidunt eu et lacus. Aliquam sed consequat orci. Nulla sodales neque magna, nec sollicitudin erat aliquam ut. Sed sed vulputate tortor, in [[vestibulum nibh]] [[Has number::42]] [[Has date::01-01-2020]]]].
`

[0] https://www.semantic-mediawiki.org/wiki/Help:$smwgLinksInValues

**Comment by mwjames** [comment]
[0] is provided as test instrument to verify the performance impact on a single page when `SMW_LINV_OBFU`  is enabled. [0] is expected to be copied and handled by a single page.

PS: [0] would most certainly kill the Parser (and hereby the system) if the legacy `SMW_LINV_PCRE` approach is used.

[0] https://gist.github.com/mwjames/78354d4b5d36878145dbcdee2a9daa75

**Comment by mwjames** [comment]
https://sandbox.semantic-mediawiki.org/wiki/Issue/2153

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
Now [documented](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgLinksInValues&type=revision&diff=49651&oldid=49638) @mwjames Thanks for the poke.

**Comment by kghbln** [comment]
Now [serving](https://sandbox.semantic-mediawiki.org/w/index.php?title=SMW_Sandbox%3ASetup_information&type=revision&diff=5731&oldid=5705) on sandbox.

**Pull request merged**
