### PR TITLE
Show redirects (synonyms) on property page, refs 1927

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1927

This PR addresses or contains:

- Redirects to properties are assumed to be synonyms (equal to the `owl:sameAs`) and to increase visibility for a user, display those redirects on the property page
- Adds `smwgRedirectPropertyListLimit` to limit access to the amount of possible synonyms displayed (`0` indicates that the display/lookup is to be suppressed)

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
- https://sandbox.semantic-mediawiki.org/wiki/Attribut:For_area_type
- https://sandbox.semantic-mediawiki.org/wiki/PropertyLabelSimilarityTest

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by mwjames** [comment]
- https://www.semantic-mediawiki.org/wiki/Redirects
- https://www.semantic-mediawiki.org/wiki/Property_similarity

**Comment by kghbln** [comment]
https://www.semantic-mediawiki.org/wiki/Help:$smwgRedirectPropertyListLimit

**Pull request merged**
