### PR TITLE
Fix coding style issues #899

### PR DESCRIPTION
**Pull request by jongfeli**
Fixed the ones I could fix [see](https://github.com/jongfeli/Code-violations-SemanticMediaWiki/commit/f358e9722633a23940007862359eb25403f676bf). The ones that are left are in [tests/](https://github.com/jongfeli/Code-violations-SemanticMediaWiki/blob/master/tests.txt).

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Needs manual rebase. Give me a shout if you want me to have a go at it.

**Comment by jongfeli** [comment]
I did not do a manual rebase. I want to practise first on a test repository before I start messing it up completely. What I don't understand is that when I sync my local repository with mediawiki master and then push it to my fork and I happen to have a pull request that is not merged yet those changes end up as a commit in the pull request. Is that correct? Those changes are already in mediawiki master. That is probably what you ment by starting a branch and commit the changes to the branch first. Well I hope it is ok now 😀.

**Comment by JeroenDeDauw** [comment]
Yeah, that is indeed a reason to use branches and not do everything on master.

**Comment by JeroenDeDauw** [comment]
Thanks!

**Pull request merged**
