### PR TITLE
Add TurtleTriplesBuilder::getChunkedTriples, refs #1110

### PR DESCRIPTION
**Pull request by mwjames**
Based on the work done by Laurent Alquier (ref #1110).

### CODE REVIEW

**Comment by mwjames** [comment]
@lalquier It would be great if you could test this before SMW 2.3 gets released.

**Comment by mwjames** [comment]
@lalquier Any feedback?

**Comment by mwjames** [comment]
Given that tests pass and after a two-weeks adjournment, the enhancement is added to 2.3.

**Comment by lalquier** [comment]
My apologies for the delayed response.. I missed the notifications from Github and I only noticed these today. Thanks for the update!

I won't be able to test for a couple of weeks at least because of other issues I need to address (unrelated to SMW).

**Pull request merged**
