### PR TITLE
Ren `Has error` to `Has processing error` (_ERRC, _ERRT), refs #1293

### PR DESCRIPTION
**Pull request by mwjames**
#1293

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln In case you are happy with the naming, just press the merge button otherwise amend to  your liking.

**Comment by kghbln** [comment]
@mwjames I was already happy with the new name. I just failed to get GitHub accept changes when I try to push them. I just received bla, bla instead as indicated in the other post.

**Comment by mwjames** [comment]
> I just failed to get GitHub accept changes when I try to push them. I just received bla, bla instead as indicated in the other post.

If you override an existing branch content then you need 

image

**Comment by kghbln** [comment]
> If you override an existing branch content then you need 

@mwjames As I realised I tried to push master instead of the local branch, so I was destined to fail. Now things are in fluff. See other issue comment.

**Pull request merged**
