### PR TITLE
Add support for evaluation of properties in slots other than 'main'

### PR DESCRIPTION
**Pull request by 26**
This pull request adds basic support for the evaluation of properties in content slots other than the 'main' slot. It defines a new setting `$smwgExtraSlotsWithSemanticLinks`, which is an array of additional slot role names for which properties need to be evaluated. Properties in the `main` slot are always evaluated.

The changes in this pull request are sub-optimal. It uses the `importDataFrom` function in the `SemanticData` class to merge the SemanticData objects from the ParserOutputs of the slots with semantic links enabled with the SemanticData object of the ParserOutput of the `main` slot.

The best approach forward is likely to rewrite a large part of the codebase so each function that now takes just a single ParserOutput object will be able to take an array of ParserOutput objects. However, I lack the knowledge of the Semantic MediaWiki codebase to know how to do this.

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
Hi Marijin, thanks for your PR. The PR is breaking some tests in CI. Please make sure, that at least for MW 1.35 tests are passing.

**Comment by gesinn-it-gea** [comment]
see also #3345, #3911, #4704 , #4909,

**Comment by krabina** [comment]
@cicalese would you be able to test/review this PR as well? You know a thing or two about slots :-)

**Comment by 26** [comment]
Base branch is currently `master`, which is not ideal. I will re-open this PR with a new base branch.

**Pull request closed without merging**
