### PR TITLE
Convert to PHP short array syntax for /tests/

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #2318 

This PR addresses or contains:
- Converts the `tests` directory to PHP 5.4+ short array syntax

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
Please wait with the change until last otherwise I get into trouble
with my PRs and have to spent a lot of time rebasing them.

Cheers

**Comment by kghbln** [comment]
> Please wait with the change until last otherwise I get into trouble with my PRs and have to spent a lot of time rebasing them.

Ok, so just ping as soon as you are ready. I have seen you use short arrays in your PRs but did not think of things you may have prepared in the meantime.

**Comment by mwjames** [comment]
> Ok, so just ping as soon as you are ready. I have seen you use short arrays
> in your PRs but did not think of things you may have prepared in the
> meantime.

I do appreciate the initiative, it is just that those type of PRs
cause a lot of pain because it requires rebasing. Yesterday, I run
into the same issue due to some import optimization that happened
while being away.

**Comment by kghbln** [comment]
> I do appreciate the initiative, it is just that those type of PRs cause a lot of pain because it requires rebasing. Yesterday, I run into the same issue due to some import optimization that happened while being away.

Fair enough, though the mentioned merge e.g. fixed broken builds quite some time ago. So sometimes it is not so easy to avoid. This one however is definitively avoidable to make things easier.

**Pull request closed without merging**
