### PR TITLE
Enable testing for PHP 7.3

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #3579, #3556, #3585

This PR addresses or contains:
- Enable testing for PHP 7.3

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by mwjames** [comment]
Just as a note, MW master is now voting which means as soon as something erupts on the MediaWiki front the CI will fail.

**Comment by JeroenDeDauw** [comment]
Yeah I realized when merging. I think it is good to notice this. If it happens and the issue can't be dealt with then the thing can always be disabled.

**Comment by kghbln** [comment]
Wasn't this already the case before with sqlite? I actually just swapped sqlite for mysql which appeared to be a bit more realistic to me. Anyways I guess we have no issues adapting this further.

**Comment by mwjames** [comment]
> Wasn't this already the case before with sqlite?

No. See how the `allow_failures` section in the .travis.yml no longer matches relevant entries in the `include` section.

**Comment by kghbln** [comment]
> No. See how the allow_failures section in the .travis.yml no longer matches relevant entries in the include section.

Ah, yeah got it. This however means that the respective line in that section is superfluous since it is not a specified environment any longer.

**Pull request merged**
