### PR TITLE
Update ValueListBuilder.php

### LINKED ISSUE #3408: Recurring PHP Warnings in master-18403e3
### Setup and configuration

- SMW version: dev-master 18403e3
- MW version: 1.31.0
- PHP version: 7.2
- DB system (MySQL, Blazegraph, etc.) and version: MySQL 14.14

### Issue
Recurring PHP Warnings in the error log:
```
PHP Warning:  array_reverse() expects parameter 1 to be array, object given in extensions/SemanticMediaWiki/src/Page/ListBuilder/ValueListBuilder.php on line 123
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in extensions/SemanticMediaWiki/src/Page/ListBuilder/ValueListBuilder.php on line 128
```

### Steps to reproduce

Unknown,

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #3408 

This PR addresses or contains:
- Fix PHP warning as suggested in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/3408#issuecomment-418072388

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #3408

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I will merge after your ok.

**Comment by JeroenDeDauw** [comment]
@mwjames @kghbln beware that Tarversable is the better type to check here. See https://www.entropywins.wtf/blog/2017/10/16/introduction-to-iterators-and-generators-in-php/ for some explanation

**Comment by JeroenDeDauw** [comment]
And yes, the name iterator_to_array makes no sense, welcome to PHP :)

**Comment by mwjames** [comment]
> @mwjames I will merge after your ok.

+1 (Maybe change to a more verbose PR title)

**Comment by kghbln** [comment]
> Maybe change to a more verbose PR title

Expected this. :)

**Pull request merged**
