### PR TITLE
Add schema group import, refs 2874

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2874

This PR addresses or contains:

- Adds `PROPERTY_GROUP_SCHEMA` for isolating the management of group assignments via a schema
- `import/smw.groups.json`/`schema.json` define the import for creating a group for schema related properties

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by mwjames** [comment]
https://www.semantic-mediawiki.org/wiki/Help:Schema/Type/PROPERTY_GROUP_SCHEMA

**Comment by mwjames** [comment]
As with the `schema.json` import example (contains group definition for `_SCHEMA*` related properties), the intent is to have a deployment mechanism where properties can be grouped (SESP properties etc.) without a user having to manually create categories and annotated them with `Is property group`.

A  `Is property group` definition to a category (and hereby property) takes precedence over any group definition found in `PROPERTY_GROUP_SCHEMA`, so a property listed as part of a `PROPERTY_GROUP_SCHEMA` where a listed property itself is assigned to category and that category `Is property group`, the property will be a member of the category assigned group.

**Comment by kghbln** [comment]
[Examples](https://sandbox.semantic-mediawiki.org/wiki/Special:SearchByProperty/:Schema-20type/PROPERTY-5FGROUP-5FSCHEMA)

**Comment by mwjames** [comment]
> Examples

+1 but I have been scratching my head why the validation schema didn't kick in since you were using an old schema and then it occurred to me that the `justinrainbow/json-schema` (A library to validate a json schema) is missing from the sandbox [0]. `justinrainbow/json-schema` is part of MW so I'm not sure why this is missing but we need throw an error on those schemata that require a validation instead of silently ignoring it.

[0] https://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version
[1] https://github.com/wikimedia/mediawiki/blob/master/composer.json#L73

**Comment by kghbln** [comment]
> since you were using an old schema

This shortly came to my mind since e.g. manifest was missing. Since I did not see this in the other examples and the setup worked ....

> the `justinrainbow/json-schema` (A library to validate a json schema) is missing from the sandbox

Probably because both MW and SMW only do a "require-dev" for it. Will probably not hurt to put it in the "require" section on the SMW end.

**Pull request merged**
