### PR TITLE
Tidy (Hooks)

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames I think this pull caused two extensions to fail, of which I would not like to loose TemplateStyles: [gist](https://gist.github.com/kghbln/96f513b72a5105aeccd2e906200fd390)

**Comment by mwjames** [comment]
> I think this pull caused two extensions to fail, of which I would not like to loose TemplateStyles: see the gist

The stack doesn't show any involvement of SMW, so I'm going to point the finger to `TemplateStylesHooks.php on line 205` and `Notice: Undefined property: Parser::$extTemplateStylesCachwe`.

```
## Template Styles extension

# Directly after `composer update`

Notice: Undefined property: Parser::$extTemplateStylesCache in /../w/extensions/TemplateStyles/includes/TemplateStylesHooks.php on line 205

Notice: Undefined property: Parser::$extTemplateStylesCache in /../w/extensions/TemplateStyles/includes/TemplateStylesHooks.php on line 205

Fatal error: Uncaught Error: Call to a member function clear() on null in /../w/extensions/TemplateStyles/includes/TemplateStylesHooks.php:205

Stack trace: 
#0 /../w/includes/Hooks.php(174): TemplateStylesHooks::onParserClearState(Object(Parser))
#1 /../w/includes/Hooks.php(202): Hooks::callHook('ParserClearStat...', Array, Array, NULL)
#2 /../w/includes/parser/Parser.php(420): Hooks::run('ParserClearStat...', Array)
#3 /../w/includes/parser/Parser.php(4774): Parser->clearState()
#4 /../w/includes/parser/Parser.php(450): Parser->startParse(Object(Title), Object(ParserOptions), 1, true)
#5 /../w/includes/OutputPage.php(2218): Parser->parse('Currently this ...', Object(Title), Object(ParserOptions), true, true, NULL)
#6 /../w/includes/OutputPage.php(2097): OutputPage->parseInternal('Currently this ...', Object(Title), true, false, false, NULL)
#7 /var/www/htdo in /../w/extensions/TemplateStyles/includes/TemplateStylesHooks.php on line 205


# After checking out origin/REL1_32

[693bc20974b96c4b0a79b163] /wiki/Main_Page Error from line 205 of /../w/extensions/TemplateStyles/includes/TemplateStylesHooks.php: Call to a member function clear() on null

Backtrace:

#0 /../w/includes/Hooks.php(174): TemplateStylesHooks::onParserClearState(Parser)
#1 /../w/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#2 /../w/includes/parser/Parser.php(420): Hooks::run(string, array)
#3 /../w/includes/parser/Parser.php(4774): Parser->clearState()
#4 /../w/includes/parser/Parser.php(728): Parser->startParse(Title, ParserOptions, integer, boolean)
#5 /../w/includes/parser/Parser.php(4800): Parser->preprocess(string, Title, ParserOptions)
#6 /../w/includes/cache/MessageCache.php(1174): Parser->transformMsg(string, ParserOptions, Title)
#7 /../w/includes/Message.php(1282): MessageCache->transform(string, boolean, Language, Title)
#8 /../w/includes/Message.php(883): Message->transformText(string)
#9 /../w/includes/Message.php(943): Message->toString(string)
#10 /../w/includes/OutputPage.php(924): Message->text()
#11 /../w/includes/OutputPage.php(971): OutputPage->setHTMLTitle(Message)
#12 /../w/includes/OutputPage.php(2742): OutputPage->setPageTitle(string)
#13 /../w/includes/exception/MWExceptionRenderer.php(127): OutputPage->prepareErrorPage(string)
#14 /../w/includes/exception/MWExceptionRenderer.php(53): MWExceptionRenderer::reportHTML(TypeError)
#15 /../w/includes/exception/MWExceptionHandler.php(98): MWExceptionRenderer::output(TypeError, integer)
#16 /../w/includes/exception/MWExceptionHandler.php(172): MWExceptionHandler::report(TypeError)
#17 /../w/includes/MediaWiki.php(547): MWExceptionHandler::handleException(TypeError)
#18 /../w/index.php(42): MediaWiki->run()
````

**Comment by mwjames** [comment]
For the record, SMW doesn't call any hook of the name `ParserClearState`!

**Comment by kghbln** [comment]
> For the record, SMW doesn't call any hook of the name `ParserClearState`!

No worries. I was just a direct correlation, meaning that only after pulling in the latest code this extension went berserk. I will report at phabricator.

**Comment by kghbln** [comment]
Reported [here. ](https://phabricator.wikimedia.org/T215766)

**Comment by mwjames** [comment]
> Reported here. 

The response is disappointing, a simple check to guard against an uninitialized varriable shoudln't be too much to ask for as in:

```
	public static function onParserClearState( Parser $parser ) {
		if ( isset( $parser->extTemplateStylesCache ) ) {
			$parser->extTemplateStylesCache->clear();
		}
	}
```

**Pull request merged**
