### PR TITLE
Add namedargs alias to list result format

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
This PR addresses or contains:
- "namedargs" alias for "named args" to the list format including a test

This PR includes:
- [x] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw I added test cases for the alias. Apart from list also "category" and "templatefile" provide "named args". These should be getting the alias, too.

**Comment by mwjames** [comment]
> . Apart from "list" also "category" and "templatefile" provide "named args". These should be getting the alias, too.

This needs to happen otherwise `namedargs` becomes an oddity among result printers. Consistency is the key here.

**Comment by kghbln** [comment]
> This needs to happen otherwise namedargs becomes an oddity among result printers. Consistency is the key here.

Exactly. This is why I mentioned it. In the meantime I created the respective pull requests.

**Comment by kghbln** [comment]
The existing docu about named arguments was an utter mess. I really wonder why nobody justfully complained. Anyhow I created [same docu.](https://www.semantic-mediawiki.org/wiki/Help:Plainlist_format/parameter_named_args)

**Pull request merged**
