### PR TITLE
added JavaScript handling for displaytitle

### PR DESCRIPTION
**Pull request by cicalese**
This pull request replaces my earlier pull request (#1227) for display title handling in JavaScript result formats. It is based upon the enhancements in the dtitle branch. I have tested it until MediaWiki 1.26.2, and it is functioning properly.

### CODE REVIEW

**Comment by cicalese** [comment]
This pull request builds on #1410.

**Comment by mwjames** [comment]
Needs a rebase :-)

**Comment by cicalese** [comment]
Hmmm. I am not a rebase expert. I tried, but it seems to have picked up changes to two other files: docs/RELEASE-NOTES.md and res/smw/ext.smw.css. I was hoping that after what I did, it would show up as a patch to SemanticMediaWiki:master, not SemanticMediaWiki:dtitle. Thoughts on what I did wrong?

**Comment by mwjames** [comment]
> Hmmm. I am not a rebase expert. I tried, but it seems to have picked up changes to two other files: 

That should be fine. Github will sort this out as long as we don't have any possible merge conflicts.

As for the output format, a version bump (`'serializer' => __CLASS__, 'version' => 0.10`) should indicate the format change.

**Comment by cicalese** [comment]
Ah, yes, I had the version bump in at one point, but it got lost in the shuffle. I will add it back in. I'm glad for the clarification that 0.10 comes after 0.9. I had meant to ask.

**Pull request merged**
