### PR TITLE
Migrate special type message keys to new naming schema, refs 2880

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2880

This PR addresses or contains:

- Changes from `_` to `-` msg keys

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln I'm leaving this in your hand so that no msg keys disappear after migrating from `_` to `-`.

**Comment by kghbln** [comment]
@Nikerabbit FYI. A couple of moves will now be necessary on twn. Will also author a change via Gerrit.

**Comment by kghbln** [comment]
Done with https://gerrit.wikimedia.org/r/c/413122/

**Comment by kghbln** [comment]
@Nikerabbit The changes did not follow the same schema in all cases thus resulting some moved system messages ending up at the wrong place. The following moves still need to be done:
- „MediaWiki:Smw-types-geo-not-available“ to „MediaWiki:Smw-types-extra-geo-not-available“
- „MediaWiki:Smw-type-mlt rec“ to „MediaWiki:Smw-type-mlt-rec“
- „MediaWiki:Smw-types-mlt-lcode“ to „MediaWiki:Smw-types-extra-mlt-lcode“
- „MediaWiki:Smw-type-ref rec“ to „MediaWiki:Smw-type-ref-rec“

**Comment by Nikerabbit** [comment]
Okay, I'll handle those once they show up in the diff screen.

**Comment by kghbln** [comment]
> Okay, I'll handle those once they show up in the diff screen.

They should already be on the screen somethere. In my post I already added the wrong resulting string, i.e. "MediaWiki:MediaWiki:Smw-types-geo-not-available" used to be "MediaWiki:Smw-sp-types-geo-not-available" as committed with this pull however the correct string on twn should be „MediaWiki:Smw-types-extra-geo-not-available“.

**Comment by Nikerabbit** [comment]
I suppose I did not do the redirects correctly, although I did not see any diffs, lemme have a look.

**Comment by Nikerabbit** [comment]
Should be fixed now.

**Comment by kghbln** [comment]
Cool, thanks a lot!

**Pull request merged**
