### PR TITLE
Fix errors caused by calling methods not in interface

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
The ResultPrinter interface does not have this method,
hence it cannot be called without first checking it exists

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
@kghbln this is not really a bug since all current result printers have the methods defined

**Comment by JeroenDeDauw** [comment]
So there is a software design issue in that some code violates the interface contract, which leads to a bug if you add new code that just follows the contract and does nothing else. But no user visible bug, which is what the GH issue tag is for.

**Comment by kghbln** [comment]
> this is not really a bug since all current result printers have the methods defined

Fair enough though the title suggested that there is an issue happening. So "code quality" is the label to go I think.

**Comment by kghbln** [comment]
> But no user visible bug, which is what the GH issue tag is for.

Indeed.

**Comment by kghbln** [comment]
In case of merging it will be cool if "Squash and merge" will be used to avoid confusion.

**Comment by mwjames** [comment]
> So there is a software design issue in that some code violates the interface contract, which leads to a bug if you add new code that just follows the contract and does nothing else.

Yes, existing printers inherit its signature from `\SMW\Query\ResultPrinters\ResultPrinter`. If you wanted to develop only against an interface then you would need to add new interfaces to cover some of the expect methods such as:

- `DeferrablePrinter` to cover `isDeferrable`
- Method `getDefaultSort` should be covered by the `ResultPrinter` interface (knowing we extend the contract is a BC but no one uses interface besides you as far as I know).
- Method `supportsRecursiveAnnotation` and `setRecursiveTextProcessor` could be covered by something like `RecursablePrinter` (better name??!!)

**Comment by JeroenDeDauw** [comment]
If implementing the current interface is not enough then I wonder why it exists in the first place. My impression is that it used to be enough, but then things just got added to the base class that everything happens to implement and no one noticed.

Having dedicated interfaces for different types of printers is in line with my thoughts here: https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/125 I'd start with minimal interface for "normal printers" and then maybe also provide new alternatives for export printers and whatnot.

**Comment by JeroenDeDauw** [comment]
> If implementing the current interface is not enough then I wonder why it exists in the first place. My impression is that it used to be enough, but then things just got added to the base class that everything happens to implement and no one noticed.

To be more explicit: In my mind either implementing this interface should be sufficient or it should not be there

**Comment by mwjames** [comment]
>  but then things just got added to the base class that everything happens to implement and no one noticed.

Well, yes because along the way we needed to fix a couple of things. So, for example, the text processor was added to be able to use the `Parser` instance from the #ask call without exposing the `Parser` object directly to printer and track any recursive parsing which is needed when #ask is part of a template or embedded processing chain and a printer itself requires additional parsing on the text output. 

Deferred printer as the name suggests allows to defer the process and has been design in a way that it impacts existing printers to a minimum while allowing some to support that feature.

Default sort was necessary because there was a hidden expectation on the a default sort and has been made explicit.

**Comment by JeroenDeDauw** [comment]
These methods can still be added to the interface right? That is probably better than what I did here.

**Comment by mwjames** [comment]
> These methods can still be added to the interface right? That is probably better than what I did here.

Yes, which is why instead of extending the `ResultPrinter` interface add new once as proposed above and check against them without breaking the `ResultPrinter` contract by adding those methods to its interface.

**Comment by JeroenDeDauw** [comment]
In my mind the `ResultPrinter` contract was already broken. The code relies on new methods. By not adding them to the interface this break is hidden but still there. So I would not consider adding the missing methods a BC break.

**Pull request closed without merging**
