### PR TITLE
DNM test for travisci

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by gesinn-it** [comment]
@JeroenDeDauw I think we need to subscribe to the free OSS plan:

grafik

Not sure if the free minutes included are sufficient or if we have to beg for more in the future. Or switch to GH actions if Travis is not willing to help OSS any more.

https://travis-ci.community/t/oss-only-credits-request-processing-time-estimate/10446

**Comment by JeroenDeDauw** [comment]
Ah indeed. https://travis-ci.com/github/SemanticMediaWiki/SemanticMediaWiki/builds/231804096

**Comment by gesinn-it** [comment]
:-) logo tests failing now

**Comment by JeroenDeDauw** [comment]
Don't think so. Last commit was about the logo, yes, but the error is not.

> There was 1 error:
> 
> 1) SMW\Tests\Utils\LogoTest::testGet_Small
> 
> PHPUnit\Framework\Exception: Argument #2 (No Value) of PHPUnit\Framework\Assert::assertContains() must be a array, traversable or string
> 
> /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/PHPUnitCompat.php:45
> 
> /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/Utils/LogoTest.php:25
> 
> /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:94

**Comment by JeroenDeDauw** [comment]
https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/5015

**Pull request closed without merging**
