### PR TITLE
Correct lowest supported MW version in 2.5.x

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
I think this was a typo or confusion of the version number

### CODE REVIEW

**Comment by mwjames** [comment]
>I think this was a typo or confusion of the version number

I'm not sure about this but since you are changing the boundaries, you might want to adjust [0].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/.travis.yml

**Comment by JeroenDeDauw** [comment]
It's essentially what we presented on last SMWCon: https://jeroendedauw.github.io/slides/smwcon/2015fall/yearly/#/14/1

1.23 is an LTS, 1.25 is not. I have no idea where 1.25 would be coming from apart from a typo

**Comment by kghbln** [comment]
> 1.23 is an LTS, 1.25 is not. I have no idea where 1.25 would be coming from apart from a typo

I also believe that this branch should continue to support 1.23 since this is an LTS.

**Comment by JeroenDeDauw** [comment]
Travis updated with https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1967

**Pull request merged**
