### PR TITLE
Fix "smwtable-clean" class being broad by default

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #4048 

This PR addresses or contains:
- Fix "smwtable-clean" class being broad by default

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames Sometimes solutions are easier than one may expect. Thanks for your guidance.

**Comment by kghbln** [comment]
@mwjames While this works for the special pages including Ask it does not work for format [broadtable](https://sandbox.semantic-mediawiki.org/wiki/Broadtable). This is basically why I wanted to introduce a "smwbroadtable-clean" class.

**Comment by mwjames** [comment]
> This is basically why I wanted to introduce a "smwbroadtable-clean" class. However it is still much better this way around than it was before.

This should work with one CSS class but it requires I slight addition (the `broadtable` is added by `|format=broadtable`):

```
@@ -250,10 +250,14 @@ border-top: 1px solid #dddddd;
 
 .smwtable-clean tr > th.headerSort {
 	padding-right: 21px !important;
 }
 
+.smwtable-clean.broadtable {
+	width: 100%;
+}
```

**Comment by mwjames** [comment]
PS: When doing CSS or documentation changes, use `[skip ci]` as we don't check those via the CI framework.

**Comment by kghbln** [comment]
> This should work with one CSS class but it requires I slight addition (the broadtable is added by |format=broadtable):

It took me a while to figure this out, however came up with the same result. :)

**Comment by kghbln** [comment]
@mwjames Paradise regained. Thanks a lot!

**Pull request merged**
