### PR TITLE
[DNM] Fixes alias being identical to name

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #3829 

This PR addresses or contains:
- Fixes alias being identical to name

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
Actually I found many more which does not make sense to me except for these are needed to map additional aliases to a name. Do not think that this is likely but ...

**Comment by kghbln** [comment]
@mwjames There is probably a reason for doing this, i.e. having alias and name being indentical?

**Comment by mwjames** [comment]
> @mwjames There is probably a reason for doing this, i.e. having alias and name being identical?

As far as I remember that was required by the old lang object handling (1.8x) to allow traversing the lookup. It could be that we still rely on it somewhere in the `Lang.php` when building the mapping between those literals. It shouldn't be necessary but I would have to confirm that which I cannot guarantee to happen anytime soon.

**Comment by kghbln** [comment]
Thanks for the info. I just wanted to avoid unnecessary pull request rot.

**Pull request closed without merging**
