### PR TITLE
Update BeforePageDisplay.php

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #2852

This PR addresses or contains:
- Fixes link type according to https://www.w3.org/TR/html5/links.html#link-type-alternate
- Adapts related test as suggested by @mwjames 

This PR includes:
- [x] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
> There was 1 failure:
> 
> 1) SMW\Tests\MediaWiki\Hooks\BeforePageDisplayTest::testProcess with data set #0 (array(), array(true))
> 
> Failed asserting that false is true.
> 
> /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/MediaWiki/Hooks/BeforePageDisplayTest.php:100

**Comment by kghbln** [comment]
That's what tests are there for. Adapted the test. Toi, toi, toi ...

**Comment by kghbln** [comment]
ok, so alternate = alternate is false. Hmm ...

**Comment by JeroenDeDauw** [comment]
> There was 1 failure:
> 
> 1) SMW\Tests\MediaWiki\Hooks\BeforePageDisplayTest::testProcess with data set #1 (array(Mock_Title_5be11802 Object (...)), array(false))
> 
> Failed asserting that true is false.
> 
> /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Unit/MediaWiki/Hooks/BeforePageDisplayTest.php:95
> 
> /home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:111

Opposite error this time :)

**Comment by kghbln** [comment]
> Opposite error this time :)

Do you have a hint for me. I do not know what is going on.

**Comment by mwjames** [comment]
> Do you have a hint for me. I do not know what is going on.

Try changing it to:

```
	public function testProcess( $setup, $expected ) {

		$expected = $expected['result'] ? $this->atLeastOnce() : $this->never();

		$skin = $this->getMockBuilder( '\Skin' )
			->disableOriginalConstructor()
			->getMock();

		$outputPage = $this->getMockBuilder( '\OutputPage' )
			->disableOriginalConstructor()
			->getMock();

		$outputPage->expects( $this->atLeastOnce() )
			->method( 'getTitle' )
			->will( $this->returnValue( $setup['title'] ) );

		$outputPage->expects( $expected )
			->method( 'addLink' );

		$instance = new BeforePageDisplay( $outputPage, $skin );

		$this->assertTrue(
			$instance->process()
		);
	}
```

**Comment by mwjames** [comment]
... and to avoid something like:

```
Expectation failed for method name is equal to
<string:getPageLanguage> when invoked at least once.
Expected invocation at least once but it never occurred.
```

try removing the following (no longer needed since we use a mock).

```

 	public function titleDataProvider() {

-		$language = Language::factory( 'en' );
-
 		#0 Standard title
 		$title = MockTitle::buildMockForMainNamespace();

 		$title->expects( $this->atLeastOnce() )
 			->method( 'getPrefixedText' )
@@ -113,14 +113,10 @@ class BeforePageDisplayTest extends
\PHPUnit_Framework_TestCase {

 		$title->expects( $this->atLeastOnce() )
 			->method( 'isSpecialPage' )
 			->will( $this->returnValue( false ) );

-		$title->expects( $this->atLeastOnce() )
-			->method( 'getPageLanguage' )
-			->will( $this->returnValue( $language ) );
-
 		$provider[] = array(
 			array(
 				'title'  => $title
 			),
 			array(
@@ -133,14 +129,10 @@ class BeforePageDisplayTest extends
\PHPUnit_Framework_TestCase {

 		$title->expects( $this->atLeastOnce() )
 			->method( 'isSpecialPage' )
 			->will( $this->returnValue( true ) );

-		$title->expects( $this->atLeastOnce() )
-			->method( 'getPageLanguage' )
-			->will( $this->returnValue( $language ) );
-
 		$provider[] = array(
 			array(
 				'title'  => $title
 			),
 			array(
```

**Comment by kghbln** [comment]
Looks like we are cool now for a squash and merge. :) Resistance is futile.

**Pull request merged**
