### PR TITLE
Use a better index for smwbrowse search, refs 2696

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2696

This PR addresses or contains:

- To make use of the new index, `update.php` or `setupStore.php` is required

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by mwjames** [comment]
Primary select:

```sql
SELECT /* SMW\MediaWiki\Api\Browse\ListLookup::search  */  smw_id,smw_title,smw_sort,smw_sortkey  
FROM `smw_object_ids`   
WHERE smw_namespace = '102' AND smw_iw = '' AND smw_subobject = '' AND (smw_sortkey LIKE '%Date%' OR smw_sortkey LIKE '%Date%' OR smw_sortkey LIKE '%DATE%' OR smw_sortkey LIKE '%date%')  
ORDER BY smw_sort LIMIT 11
```

```json
{
 "query_block": {
   "select_id": 1,
   "table": {
     "table_name": "smw_object_ids",
     "access_type": "index",
     "possible_keys": ["smw_iw", "smw_iw_2"],
     "key": "smw_sort",
     "key_length": "296",
     "used_key_parts": ["smw_sort", "smw_id", "smw_iw"],
     "rows": 11,
     "filtered": 100,
     "attached_condition": "((smw_object_ids.smw_iw = '') and (smw_object_ids.smw_subobject = '') and (smw_object_ids.smw_namespace = '102') and ((smw_object_ids.smw_sortkey like '%Date%') or (smw_object_ids.smw_sortkey like '%Date%') or (smw_object_ids.smw_sortkey like '%DATE%') or (smw_object_ids.smw_sortkey like '%date%')))"
   }
 }
}
```
"queryTime": 2.98219 on `smw_object_ids` with `175,088` rows

New index:

```json
{
 "query_block": {
   "select_id": 1,
   "read_sorted_file": {
     "filesort": {
       "table": {
         "table_name": "smw_object_ids",
         "access_type": "ref",
         "possible_keys": ["smw_iw", "smw_iw_2", "smw_namespace"],
         "key": "smw_namespace",
         "key_length": "38",
         "used_key_parts": ["smw_namespace", "smw_iw"],
         "ref": ["const", "const"],
         "rows": 12719,
         "filtered": 100,
         "index_condition": "(smw_object_ids.smw_iw = '')",
         "attached_condition": "((smw_object_ids.smw_namespace <=> '102') and (smw_object_ids.smw_iw <=> '') and ((smw_object_ids.smw_subobject = '') and ((smw_object_ids.smw_sortkey like '%Date%') or (smw_object_ids.smw_sortkey like '%Date%') or (smw_object_ids.smw_sortkey like '%DATE%') or (smw_object_ids.smw_sortkey like '%date%'))))"
       }
     }
   }
 }
}
```

"queryTime": 1.13102 on `smw_object_ids` with `175,088` rows

The old `smw_sort` index should be faster as it only deals with `"rows": 11` but in reality it is slower, so for now we try the new index.

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by mwjames** [comment]
Of course, when the `api.browse` cache is enabled, query times become significant faster such as "queryTime": 0.00066 but any request that isn't cached would hit the `Store` on its first iteration before being served from cache considering that the same search string is used.

**Comment by kghbln** [comment]
Another nice performance improvement. [Now live on sandbox!](https://gist.github.com/kghbln/a2cc58c673522cb5dd3669651b66fd78)

**Pull request merged**
