### PR TITLE
Changes default setting for `smwgExportResourcesAsIri` (breaking)

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #2207 

This PR addresses or contains:
- Switches (BREAKING) the default to use IRIs for resource export
- Fixes test per [comment](#2788 (comment)) by @mwjames

This PR includes:
- [x] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@mwjames Oops, would not have guessed that this will be failing. I am not sure why `true` is not returning the expected. Probably some extra fiddle is needed perhaps even in light of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2781

**Comment by mwjames** [comment]
> @mwjames Oops, would not have guessed that this will be failing. I am not
> sure why `true` is not returning the expected. Probably some extra fiddle is

There is a small misstep in the `EscaperTest` and the reason why the
setting isn't reset.

```
@@ -24,11 +24,11 @@ class EscaperTest extends \PHPUnit_Framework_TestCase {

 		$this->testEnvironment = new TestEnvironment();
 		$this->testEnvironment->addConfiguration(
'smwgExportResourcesAsIri', false );
 	}

-	protected function setU() {
+	protected function tearDown() {
 		$this->testEnvironment->tearDown();
 		parent::tearDown();
 	}

```

PS: Maybe changing the title of the PR to indicate what has changed
(making it easier when browsing the git log).

Cheers

**Comment by kghbln** [comment]
@mwjames Looks like we are cool!

**Comment by mwjames** [comment]
> @mwjames Looks like we are cool!

That needs a definite section in the release notes since it would make any non-ASCII resource export invalid (and hereby RDF and SPARQL). As to why, #2781 contains some clarification.

PS: I may consolidate the export settings at the later point but this is orthogonal to what is being addressed here.

**Comment by kghbln** [comment]
[Documented on wiki.](https://www.semantic-mediawiki.org/w/index.php?title=Help%3A%24smwgExportResourcesAsIri&type=revision&diff=57116&oldid=56130)

**Pull request merged**
