### PR TITLE
Check `wgLanguageCode` and raise exception, refs 4680

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #4680

This PR addresses or contains:

- raison d'être https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4680#issuecomment-609011987

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #

### CODE REVIEW

**Comment by mwjames** [comment]
For those who do:

```
$wgLanguageCode = "en";

enableSemantics( 'example.org' );

$wgLanguageCode = "fr";
```

This PR will raise an exception similar to:

```
[f24fe34d6c06a0e7d72b2713] /.../Property:Modification_date SMW\Exception\SiteLanguageChangeException from line 220 of...\extensions\SemanticMediaWiki\src\NamespaceManager.php: A change to the `wgLanguageCode` was detected showing a discrepancy (en, fr) and is preventing Semantic MediaWiki from modifying related namespace settings.

LocalSettings.php should only contain one `wgLanguageCode` definition and the declaration should happen before `enableSemantics`.

Backtrace:

#0...\extensions\SemanticMediaWiki\src\NamespaceManager.php(190): SMW\NamespaceManager->getLanguageCode(array)
#1...\extensions\SemanticMediaWiki\src\NamespaceManager.php(79): SMW\NamespaceManager::initCustomNamespace(array)
#2...\extensions\SemanticMediaWiki\src\MediaWiki\Hooks.php(196): SMW\NamespaceManager::initCanonicalNamespaces(array)
#3...\includes\Hooks.php(174): SMW\MediaWiki\Hooks::SMW\MediaWiki\{closure}(array)
#4...\includes\Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#5...\includes\MWNamespace.php(244): Hooks::run(string, array)
#6...\includes\MWNamespace.php(270): MWNamespace::getCanonicalNamespaces()
#7...\languages\Language.php(754): MWNamespace::getCanonicalIndex(string)
#8...\includes\title\MediaWikiTitleCodec.php(306): Language->getNsIndex(string)
#9...\includes\Title.php(3752): MediaWikiTitleCodec->splitTitleString(string, integer)
#10...\includes\Title.php(377): Title->secureAndSplit()
#11...\includes\MediaWiki.php(83): Title::newFromURL(string)
#12...\includes\MediaWiki.php(140): MediaWiki->parseTitle()
#13...\includes\MediaWiki.php(776): MediaWiki->getTitle()
#14...\includes\MediaWiki.php(517): MediaWiki->main()
#15...\index.php(42): MediaWiki->run()
#16 {main}
```

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by kghbln** [comment]
[Documented](https://www.semantic-mediawiki.org/wiki/Help:Installation/Troubleshooting/LocalSettings.php_should_only_contain_one_$wgLanguageCode_definition)

**Comment by alex-mashin** [comment]
This change seems to have broken `RebuildLocalisationCache.php`.
```
MW_INSTALL_PATH='/var/www/wiki/w' php maintenance/rebuildLocalisationCache.php --lang=de --force --wiki='(my project)'
```
Result:
```
Rebuilding de...
SMW\Exception\SiteLanguageChangeException from line 243 of /var/www/wiki/w/extensions/SemanticMediaWiki/src/NamespaceManager.php: A change to the `wgLanguageCode` was detected showing a discrepancy (de, en) and is preventing Semantic MediaWiki from modifying related namespace settings.

LocalSettings.php should only contain one `wgLanguageCode` definition and the declaration should happen before `enableSemantics`.
#0 /var/www/wiki/w/extensions/SemanticMediaWiki/src/NamespaceManager.php(200): SMW\NamespaceManager->getLanguageCode()
#1 /var/www/wiki/w/extensions/SemanticMediaWiki/src/NamespaceManager.php(92): SMW\NamespaceManager::initCustomNamespace()
#2 /var/www/wiki/w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(221): SMW\NamespaceManager::initCanonicalNamespaces()
#3 /var/www/wiki/w/includes/Hooks.php(174): SMW\MediaWiki\Hooks::SMW\MediaWiki\{closure}()
#4 /var/www/wiki/w/includes/Hooks.php(202): Hooks::callHook()
#5 /var/www/wiki/w/includes/title/NamespaceInfo.php(356): Hooks::run()
#6 /var/www/wiki/w/languages/Language.php(487): NamespaceInfo->getCanonicalNamespaces()
#7 /var/www/wiki/w/languages/Language.php(563): Language->getNamespaces()
#8 /var/www/wiki/w/includes/title/MediaWikiTitleCodec.php(108): Language->getNsText()
#9 /var/www/wiki/w/includes/title/MediaWikiTitleCodec.php(138): MediaWikiTitleCodec->getNamespaceName()
#10 /var/www/wiki/w/includes/title/MediaWikiTitleCodec.php(266): MediaWikiTitleCodec->formatTitle()
#11 /var/www/wiki/w/includes/cache/LinkCache.php(246): MediaWikiTitleCodec->getPrefixedDBkey()
#12 /var/www/wiki/w/includes/Title.php(3142): LinkCache->addLinkObj()
#13 /var/www/wiki/w/includes/Revision/RevisionRecord.php(109): Title->getArticleID()
#14 /var/www/wiki/w/includes/Revision/RevisionStoreRecord.php(64): MediaWiki\Revision\RevisionRecord->__construct()
#15 /var/www/wiki/w/includes/Revision/RevisionStore.php(1893): MediaWiki\Revision\RevisionStoreRecord->__construct()
#16 /var/www/wiki/w/includes/Revision/RevisionStore.php(1816): MediaWiki\Revision\RevisionStore->newRevisionFromRowAndSlots()
#17 /var/www/wiki/w/includes/Revision/RevisionStore.php(2538): MediaWiki\Revision\RevisionStore->newRevisionFromRow()
#18 /var/www/wiki/w/includes/Revision/RevisionStore.php(1513): MediaWiki\Revision\RevisionStore->loadRevisionFromConds()
#19 /var/www/wiki/w/includes/Revision.php(139): MediaWiki\Revision\RevisionStore->getRevisionByTitle()
#20 /var/www/wiki/w/extensions/Gadgets/includes/MediaWikiGadgetsDefinitionRepo.php(139): Revision::newFromTitle()
#21 /var/www/wiki/w/extensions/Gadgets/includes/MediaWikiGadgetsDefinitionRepo.php(108): MediaWikiGadgetsDefinitionRepo->fetchStructuredList()
#22 /var/www/wiki/w/includes/libs/objectcache/wancache/WANObjectCache.php(1423): MediaWikiGadgetsDefinitionRepo->{closure}()
#23 /var/www/wiki/w/includes/libs/objectcache/wancache/WANObjectCache.php(1278): WANObjectCache->fetchOrRegenerate()
#24 /var/www/wiki/w/extensions/Gadgets/includes/MediaWikiGadgetsDefinitionRepo.php(115): WANObjectCache->getWithSetCallback()
#25 /var/www/wiki/w/extensions/Gadgets/includes/MediaWikiGadgetsDefinitionRepo.php(31): MediaWikiGadgetsDefinitionRepo->loadGadgets()
#26 /var/www/wiki/w/extensions/Gadgets/includes/GadgetHooks.php(134): MediaWikiGadgetsDefinitionRepo->getGadgetIds()
#27 /var/www/wiki/w/includes/Hooks.php(174): GadgetHooks::registerModules()
#28 /var/www/wiki/w/includes/Hooks.php(202): Hooks::callHook()
#29 /var/www/wiki/w/includes/ServiceWiring.php(690): Hooks::run()
#30 /var/www/wiki/w/includes/libs/services/ServiceContainer.php(458): Wikimedia\Services\ServiceContainer->{closure}()
#31 /var/www/wiki/w/includes/libs/services/ServiceContainer.php(427): Wikimedia\Services\ServiceContainer->createService()
#32 /var/www/wiki/w/includes/MediaWikiServices.php(901): Wikimedia\Services\ServiceContainer->getService()
#33 /var/www/wiki/w/maintenance/rebuildLocalisationCache.php(98): MediaWiki\MediaWikiServices->getResourceLoader()
#34 /var/www/wiki/w/includes/cache/localisation/LocalisationCache.php(1049): RebuildLocalisationCache->{closure}()
#35 /var/www/wiki/w/includes/cache/localisation/LocalisationCacheBulkLoad.php(100): LocalisationCache->recache()
#36 /var/www/wiki/w/maintenance/rebuildLocalisationCache.php(178): LocalisationCacheBulkLoad->recache()
#37 /var/www/wiki/w/maintenance/rebuildLocalisationCache.php(138): RebuildLocalisationCache->doRebuild()
#38 /var/www/wiki/w/maintenance/doMaintenance.php(99): RebuildLocalisationCache->execute()
#39 /var/www/wiki/w/maintenance/rebuildLocalisationCache.php(197): require_once('/var/www/wiki/w...')
#40 {main}

```
Without `--force` it fails for the first time and kind of succeeds (`0 languages rebuilt out of 1`) if called again.

**Comment by jaideraf** [comment]
Just to understand, does your `LocalSettings.php` have 2 [`$wgLanguageCode` ](https://www.mediawiki.org/wiki/Manual:$wgLanguageCode)statements?

**Comment by alex-mashin** [comment]
> Just to understand, does your `LocalSettings.php` have 2 [`$wgLanguageCode` ](https://www.mediawiki.org/wiki/Manual:$wgLanguageCode)statements?
Of course, not.

**Comment by alex-mashin** [comment]
`RebuildLocalisationCache::finalSetup()`, line 59:
```
		global $wgLanguageCode;
		$wgLanguageCode = 'en';
```
And if `$wgLanguageCode` is not `'en'`, you're in trouble.

**Pull request merged**
