### PR TITLE
Added safeguards to SMWDIGeoCoord

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by mwjames** [comment]
PHPUnit 5.x! We only test against 3.x and 4.x.

```
.PHP Fatal error:  Call to undefined method SMW\Tests\SMWDIGeoCoordTest::expectException() in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/includes/dataitems/DI_GeoCoordTest.php on line 37
PHP Stack trace:
PHP   1. {main}() /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php:0
PHP   2. PHPUnit_TextUI_Command::main() /home/travis/build/SemanticMediaWiki/mw/tests/phpunit/phpunit.php:250
PHP   3. PHPUnit_TextUI_Command->run() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php:129
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/TextUI/Command.php:176
PHP   5. PHPUnit_Framework_TestSuite->run() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php:350
PHP   6. PHPUnit_Framework_TestSuite->run() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:709
PHP   7. PHPUnit_Framework_TestSuite->run() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:709
PHP   8. PHPUnit_Framework_TestSuite->runTest() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:749
PHP   9. PHPUnit_Framework_TestCase->run() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php:779
PHP  10. PHPUnit_Framework_TestResult->run() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php:783
PHP  11. PHPUnit_Framework_TestCase->runBare() /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php:648
```

**Comment by JeroenDeDauw** [comment]
Right. Not sure why my IDE was showing me the wrong PHPUnit.

Another reason to up to PHP 5.6 btw, then we can stop using obsolete PHPUnit

**Comment by mwjames** [comment]
> Another reason to up to PHP 5.6 btw, then we can stop using obsolete PHPUnit

If there is a tool that converts all the `setExpectedException` and converts the `createMock` calls then fine by me but I don't think I'm too eager to go through each test and make those changes manually.

**Comment by mwjames** [comment]
In case such transition takes place, I'd prefer that to happen later in 3.0 otherwise it is possible that some back-ports fail for the 2.5.x Travis setup (which remains on 3.x/4.x) and create a rather tedious cherry-picking process.

**Comment by JeroenDeDauw** [comment]
I think simple search and replace works well enough for such migration. Not had any issues with it in other projects.

**Pull request merged**
