### PR TITLE
Fulltext to add support for TYPE_WIKIPAGE, refs 1481, 1801, 1912

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #1481, #1801, #1912 

This PR addresses or contains:

- Adds `smwgFulltextSearchIndexableDataTypes` which can be extended to what datatype are allowed to be index using the full-text index with the default being `BLOB` and `URI`
- Adds support for page type properties to use the same `~` matching operation (incl. case insensitivity) as text or uri property types

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln as Christmas present! `SMW_FT_WIKIPAGE` as indexable dataType is NOT enabled by default  because:

```
##
# List of indexable DataTypes
#
# - SMW_FT_BLOB property values of type Blob (Text)
# - SMW_FT_URI property values of type URI
# - SMW_FT_WIKIPAGE property values of type Page
#
# SMW_FT_WIKIPAGE has not been added as default value as no performance
# impact analysis is available as to how indexing and search performance would
# be affected by a wiki with a large pool of pages (10K+) or extended page
# type value assignments on a full-text index.
#
# Enabling SMW_FT_WIKIPAGE will support the same search features (case
# insensitivity, phrase matching etc.) as available for Text or URI values
# when searches are executed using the ~/!~.
#
# @since 2.5
# @default: SMW_FT_BLOB | SMW_FT_URI
##
'smwgFulltextSearchIndexableDataTypes' => SMW_FT_BLOB | SMW_FT_URI,
##
```

**Comment by mwjames** [comment]
Feel free to add the rest of the queries from [0] to [1].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/ac83f02d79d3eaeb101e866e6eacbdf69a083d65/tests/phpunit/Integration/JSONScript/TestCases/q-0105.json
[1] https://sandbox.semantic-mediawiki.org/wiki/Issue/2122/Queries

**Comment by mwjames** [comment]
```
$ php maintenance/rebuildFulltextSearchTable.php
```
Will indicated which types are enabled:

```
- DataTypes (Indexable)            BLOB, URI, WIKIPAGE
...
- smw_di_wikipage                   100% (13076/13076)
```

Some external properties with a `WIKIPAGE` type has been preemptively exempted from the index.
```
- _ASKFO, _ASKST, _IMPO, _LCODE, _UNIT, _CONV, _TYPE, _ERRT, _INST
- _ASK, _SOBJ, ___EUSER, ___CUSER, ___SUBP, ___EXIFDATA, __sci_cite
- __sil_iwl_lang, __sil_ill_lang
```

- https://github.com/SemanticMediaWiki/SemanticCite/pull/39
- https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/pull/70
- https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/pull/47

**Comment by kghbln** [comment]
@mwjames Setting `$smwgFulltextSearchIndexableDataTypes = $smwgFulltextSearchIndexableDataTypes | SMW_FT_WIKIPAGE;` to add datatype page should work, too?

**Comment by mwjames** [comment]
> Setting $smwgFulltextSearchIndexableDataTypes = $smwgFulltextSearchIndexableDataTypes | SMW_FT_WIKIPAGE; to add datatype page should work, too?

Yes (for `| ` see http://php.net/manual/en/language.operators.bitwise.php)

**Comment by kghbln** [comment]
> Yes

Thanks a lot for the info!

**Comment by krabina** [comment]
> SMW_FT_WIKIPAGE has not been added as default value as no performance impact analysis is available as to how indexing and search performance would be affected by a wiki with a large pool of pages (10K+)

Can I help by doing a performance impact analysis on a large wiki (40k pages)? I'd just need instructions what to do and how to provide results valuable to you...

**Pull request merged**
