### PR TITLE
add index on "p_id" for DIBooleanHandler

### PR DESCRIPTION
**Pull request by gesinn-it-gea**
fixing #4950

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
All other handlers do have indizes on p_id. Only DIBooleanHandler did not have one. Tested on my local instance where I had the same performance issues as @Nikerabbit. The fix brought significant performance improvement.

**Comment by JeroenDeDauw** [comment]
Great fix, thanks! Due to [our release policy](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/docs/RELEASE-POLICY.md) we have to bump to 5.0 if we merge this. So let's hold of a little bit an first get another 4.x release out of the door.

**Comment by JeroenDeDauw** [comment]
Actually... if you pull in this code change and do not run the update script, nothing should break, riiiight? The index simply will not be there, just like it currently is not. So this isn't a breaking change and thus does not need to be delayed till 5.0.

Or am I wrong, and does pulling this in without running the update script cause errors or other problems?

**Comment by gesinn-it-gea** [comment]
@JeroenDeDauw it does not break but create the index automatically if required. No update.php is required.

**Pull request merged**
