### PR TITLE
smw.dataItem.time to support historic dates

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: # N/A

This PR addresses or contains:

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln I do hope I didn't break anything (cannot be tested by our standard suite since this is JS)!

https://sandbox.semantic-mediawiki.org/wiki/Issue/2108

## Before 

image

## After

DataTables should appear with a similar output as the `format=table`.

**Comment by kghbln** [comment]
Indeed we now also have the databables. The only thing I realize is that datatables does not show the Julian date indicator "JL"

**Comment by mwjames** [comment]
> The only thing I realize is that datatables does not show the Julian date indicator "JL"

Added with 4a141ed.

**Comment by kghbln** [comment]
> Added with 4a141ed.

Works perfect! Great, great, great.

**Pull request merged**
