### PR TITLE
#info tooltip to use flat icon set

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

image

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI

**Comment by mwjames** [comment]
https://sandbox.semantic-mediawiki.org/wiki/Issue/2691

**Comment by kghbln** [comment]
[Documented on wiki](https://www.semantic-mediawiki.org/w/index.php?title=Help%3AAdding_tooltips&type=revision&diff=54677&oldid=44543)

**Comment by stefahn** [comment]
Hi mwjames and Karsten,

I updated to SMW 3 recently and found that the tooltips now open automatically if one hovers over them with the mouse. This is okay for me.
But is it intended behaviour that the info bubbles don't close if I move my mouse away from the icon? All other bubbles (note, warning, error) close themselves.
If it is on purpose, is there any way so that info bubbles behave like the other 3?

**Pull request merged**
