### PR TITLE
Removes unmatched "ghost" pages from the ID_TABLE, refs #1110

### PR DESCRIPTION
**Pull request by mwjames**
refs #1100

- Matches (and returns) all ids for the DBKey/NS pattern that can include possible ghost pages
- Removes the special pages cache for properties deleted

### CODE REVIEW

**Comment by mwjames** [comment]
When looking at [0] I came across properties being created multiple times (probably during a DB deadlock or a failed rollback), anyway the previous (before this PR) `delete` action would only find one match and left all remaining properties untouched in the ID_TABLE making it impossible to correct the ID_TABLE without direct SQL intervention.

As of this PR, the `delete` action will mark all IDs as `SMW_SQL3_SMWDELETEIW`  that match the same DBKEY/NS. It furthermore invalidates the cache entry for special pages where properties will no longer be available (those marked as deleted) for display without having to alter the `$GLOBALS['smwgCacheUsage']` setting.

@SemanticMediaWiki/testers Anyone care to test?
@kghbln In case someone encounters [0] then the proposed process is to deleted the property and re-created it.

[0] http://www.vanhamel.nl/vhcodecs/index.php?title=Special:Properties&limit=500&offset=500

image

**Comment by jaideraf** [comment]
Tested. It seems fine to me.

**Comment by mwjames** [comment]
> Tested. It seems fine to me.

:+1: Thanks

**Comment by thingles** [comment]
I get these [all over the place on WikiApiary](https://wikiapiary.com/wiki/Special:Properties). To remove the ghosts I need to delete the Property and recreate them? Is that the right way to read the above?

**Comment by mwjames** [comment]
> To remove the ghosts I need to delete the Property and recreate them? Is that the right way to read the above?

This is one way but if you wait a bit #1216 should also make it possible to avoid having them the be deleted /re-created in the first place by using an algo to determine which of the properties are unused and remove them as well.

In combination with `rebuildData.php --shallow-update` it should remove all those entities that are without reference.

**Pull request merged**
