### PR TITLE
Add smwgDetectOutdatedData setting

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Partially deals with https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4674

This default can be changed when the issues with the current behavior
are fixed.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Merging this to retain 3.1 behavior. I don't agree with changing it without first resolving the issues described in the linked issue. And neither does the community, without even knowing about said issues https://twitter.com/SemanticMW/status/1302022612219035648

**Comment by kghbln** [comment]
> Merging this to retain 3.1 behavior.

From the name of the parameter I get that it disables outdated data detection which is the opposite of what 3.1 is doing if set to false.

**Comment by JeroenDeDauw** [comment]
You are right, I got confused here. The behavior that is retained is not showing the issue panel in case the data is outdated. No issue panel in 3.1.

**Comment by JeroenDeDauw** [comment]
Wait no - the revision check was added in 3.2. https://www.semantic-mediawiki.org/wiki/Help:Entity_examinations @kghbln what are you talking about?

**Pull request merged**
