### PR TITLE
Convert log-show-hide-{$type} messages to logeventslist-{$type}-log

### PR DESCRIPTION
**Pull request by prtksxna**
This PR is made in reference to: https://phabricator.wikimedia.org/T199657

This PR addresses or contains:
- A follow-up after https://gerrit.wikimedia.org/r/c/mediawiki/core/+/428871
- i18n message changes

This PR includes:
- [ ] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
@prtksxna Thanks a lot for the pull!

**Comment by mwjames** [comment]
The old messages should remain since I suspect the current PR only
takes into account MW 1.32. The next release of SMW is still planned
to support MW 1.27 so removing those message will cause trouble for
non MW 1.32 environments.

Of course, if the new messages are also available for MW 1.27 then
there are no objections.

**Comment by prtksxna** [comment]
> Of course, if the new messages are also available for MW 1.27 then
there are no objections.

I don't think these changes will be backported, so yes, in that case we need to keep the old ones. Give me some time to update this PR? I have raised your concern on the main task as well - https://phabricator.wikimedia.org/T199657#4426776

**Comment by kghbln** [comment]
>  Give me some time to update this PR?

Yes. :)

**Comment by prtksxna** [comment]
Updated PR to not remove old messages.

**Comment by kghbln** [comment]
> Updated PR to not remove old messages.

Cool, thanks a lot!

**Comment by kghbln** [comment]
Back-ported to 2.5.x with 954ff207d58e7ca24dc84d843293c86a9281539b

**Pull request merged**
