### PR TITLE
Fix execution of query with conjunction of disjunctions

### PR DESCRIPTION
**Pull request by vitalif**
SQL store of SMW tried to execute (a OR b) AND (c OR d) query like
(a OR b) AND c AND d (where a, b, c, d are some query terms).

This patch fixes it.

### CODE REVIEW

**Comment by mwjames** [comment]
Just had a look at this (due to #1056) and the conclusion cited is not appropriate because using the following sample:
- page `Issue19/A` with [[Prop1::Value1]] [[Prop2::Value1]] 
- page `Issue19/B` with [[Prop1::Value2]] [[Prop2::Value2]]
- page `Issue19/C` with [[Prop1::Value1]] [[Prop2::Value3]]

for 

```
{{#ask: [[Prop1::Value1||Value2]] AND [[Prop2::Value1||Value2]]
 |format=table
}}
```

## SQLStore
```
SQL Query
SELECT DISTINCT t11.smw_title AS t,t11.smw_namespace AS ns FROM `smw_object_ids` AS t11 INNER JOIN `smw_di_wikipage` AS t1 ON t11.smw_id=t1.s_id INNER JOIN `t3` AS t3 ON t1.o_id=t3.id INNER JOIN `smw_di_wikipage` AS t6 ON t1.s_id=t6.s_id INNER JOIN `t8` AS t8 ON t6.o_id=t8.id WHERE (t1.p_id='1955' AND (t6.p_id='1957')) ORDER BY t11.smw_sortkey ASC LIMIT 55 OFFSET 0;
Auxilliary Tables Used
Temporary table t3
  INSERT IGNORE INTO `t3` (id) VALUES ('1956')
  INSERT IGNORE INTO `t3` (id) VALUES ('1959')
Temporary table t8
  INSERT IGNORE INTO `t8` (id) VALUES ('1956')
  INSERT IGNORE INTO `t8` (id) VALUES ('1959')
```

### SPARQLStore
```
PREFIX wiki: <http://example.org/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <http://example.org/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?result WHERE {
?result swivt:wikiPageSortKey ?resultsk .
?result property:Prop1 ?v1 .
FILTER( ?v1 = wiki:Value1 || ?v1 = wiki:Value2 )
?result property:Prop2 ?v2 .
FILTER( ?v2 = wiki:Value1 || ?v2 = wiki:Value2 )

}
ORDER BY ASC(?resultsk) 
OFFSET 0
LIMIT 51
```
will return `Issue19/A` and `Issue19/B` as subjects

The issue is that `[[Prop1::Value1||Value2]] AND [[Prop2::Value1||Value2]]` is expected to be equal to `<q>[[Prop1::Value1]] OR [[Prop1::Value2]]</q> AND <q>[[Prop2::Value1]] OR [[Prop2::Value2]]</q>` which is not the case because the `QueryParser` interprets those queries differently hence the issue is with the `QueryParser` and the `QueryEngine`.

for
```
{{#ask: <q>[[Prop1::Value1]] OR [[Prop1::Value2]]</q> AND <q>[[Prop2::Value1]] OR [[Prop2::Value2]]</q>
 |format=table
}}
```

### SQLStore
returns nothing

### SPARQLStore

```
PREFIX wiki: <http://example.org/id/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX swivt: <http://semantic-mediawiki.org/swivt/1.0#>
PREFIX property: <http://example.org/id/Property-3A>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT DISTINCT ?result WHERE {
?result swivt:wikiPageSortKey ?resultsk .
{
?result property:Prop1 wiki:Value1 .
} UNION {
?result property:Prop1 wiki:Value2 .
}{
?result property:Prop2 wiki:Value1 .
} UNION {
?result property:Prop2 wiki:Value2 .
}
}
ORDER BY ASC(?resultsk) 
OFFSET 0
LIMIT 51
```
will return `Issue19/A` and `Issue19/B` as subjects

**Comment by mwjames** [comment]
## Description
### [[Prop1::Value1||Value2]] AND [[Prop2::Value1||Value2]]
```
    [description:SMWQuery:private] => SMW\Query\Language\Conjunction Object
        (
            [m_descriptions:protected] => Array
                (
                    [0] => SMW\Query\Language\SomeProperty Object
                        (
                            [description:protected] => SMW\Query\Language\Disjunction Object
                                (
                                    [descriptions:SMW\Query\Language\Disjunction:private] => Array
                                        (
                                            [0] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value1
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] =>
                                                            [m_subobjectname:protected] =>
                                                            [sortkey:SMW\DIWikiPage:private] =>
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop1
                                                            [m_inverse:SMW\DIProperty:private] =>
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                            [1] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value2
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] =>
                                                            [m_subobjectname:protected] =>
                                                            [sortkey:SMW\DIWikiPage:private] =>
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop1
                                                            [m_inverse:SMW\DIProperty:private] =>
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                        )

                                    [classDescription:SMW\Query\Language\Disjunction:private] =>
                                    [isTrue:SMW\Query\Language\Disjunction:private] =>
                                    [m_printreqs:protected] => Array
                                        (
                                        )

                                )

                            [property:protected] => SMW\DIProperty Object
                                (
                                    [m_key:SMW\DIProperty:private] => Prop1
                                    [m_inverse:SMW\DIProperty:private] =>
                                    [m_proptypeid:SMW\DIProperty:private] => _wpg
                                )

                            [m_printreqs:protected] => Array
                                (
                                )

                        )

                    [1] => SMW\Query\Language\SomeProperty Object
                        (
                            [description:protected] => SMW\Query\Language\Disjunction Object
                                (
                                    [descriptions:SMW\Query\Language\Disjunction:private] => Array
                                        (
                                            [0] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value1
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] =>
                                                            [m_subobjectname:protected] =>
                                                            [sortkey:SMW\DIWikiPage:private] =>
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop2
                                                            [m_inverse:SMW\DIProperty:private] =>
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                            [1] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value2
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] =>
                                                            [m_subobjectname:protected] =>
                                                            [sortkey:SMW\DIWikiPage:private] =>
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop2
                                                            [m_inverse:SMW\DIProperty:private] =>
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                        )

                                    [classDescription:SMW\Query\Language\Disjunction:private] =>
                                    [isTrue:SMW\Query\Language\Disjunction:private] =>
                                    [m_printreqs:protected] => Array
                                        (
                                        )

                                )

                            [property:protected] => SMW\DIProperty Object
                                (
                                    [m_key:SMW\DIProperty:private] => Prop2
                                    [m_inverse:SMW\DIProperty:private] =>
                                    [m_proptypeid:SMW\DIProperty:private] => _wpg
                                )

                            [m_printreqs:protected] => Array
                                (
                                )

                        )

                )

            [m_printreqs:protected] => Array
                (
                    [0] => SMW\Query\PrintRequest Object
                        (
                            [m_mode:protected] => 2
                            [m_label:protected] =>
                            [m_data:protected] =>
                            [m_typeid:protected] =>
                            [m_outputformat:protected] =>
                            [m_hash:protected] =>
                            [m_params:protected] => Array
                                (
                                )

                        )

                )

        )

    [errors:SMWQuery:private] => Array
        (
        )

    [queryString:SMWQuery:private] => [[Prop1::Value1||Value2]] AND [[Prop2::Value1||Value2]]
```

### <q>[[Prop1::Value1]] OR [[Prop1::Value2]]</q> AND <q>[[Prop2::Value1]] OR [[Prop2::Value2]]</q>
```
    [description:SMWQuery:private] => SMW\Query\Language\Conjunction Object
        (
            [m_descriptions:protected] => Array
                (
                    [0] => SMW\Query\Language\Disjunction Object
                        (
                            [descriptions:SMW\Query\Language\Disjunction:private] => Array
                                (
                                    [0] => SMW\Query\Language\SomeProperty Object
                                        (
                                            [description:protected] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value1
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] => 
                                                            [m_subobjectname:protected] => 
                                                            [sortkey:SMW\DIWikiPage:private] => 
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop1
                                                            [m_inverse:SMW\DIProperty:private] => 
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                            [property:protected] => SMW\DIProperty Object
                                                (
                                                    [m_key:SMW\DIProperty:private] => Prop1
                                                    [m_inverse:SMW\DIProperty:private] => 
                                                    [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                )

                                            [m_printreqs:protected] => Array
                                                (
                                                )

                                        )

                                    [1] => SMW\Query\Language\SomeProperty Object
                                        (
                                            [description:protected] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value2
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] => 
                                                            [m_subobjectname:protected] => 
                                                            [sortkey:SMW\DIWikiPage:private] => 
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop1
                                                            [m_inverse:SMW\DIProperty:private] => 
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                            [property:protected] => SMW\DIProperty Object
                                                (
                                                    [m_key:SMW\DIProperty:private] => Prop1
                                                    [m_inverse:SMW\DIProperty:private] => 
                                                    [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                )

                                            [m_printreqs:protected] => Array
                                                (
                                                )

                                        )

                                )

                            [classDescription:SMW\Query\Language\Disjunction:private] => 
                            [isTrue:SMW\Query\Language\Disjunction:private] => 
                            [m_printreqs:protected] => Array
                                (
                                )

                        )

                    [1] => SMW\Query\Language\Disjunction Object
                        (
                            [descriptions:SMW\Query\Language\Disjunction:private] => Array
                                (
                                    [0] => SMW\Query\Language\SomeProperty Object
                                        (
                                            [description:protected] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value1
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] => 
                                                            [m_subobjectname:protected] => 
                                                            [sortkey:SMW\DIWikiPage:private] => 
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop2
                                                            [m_inverse:SMW\DIProperty:private] => 
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                            [property:protected] => SMW\DIProperty Object
                                                (
                                                    [m_key:SMW\DIProperty:private] => Prop2
                                                    [m_inverse:SMW\DIProperty:private] => 
                                                    [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                )

                                            [m_printreqs:protected] => Array
                                                (
                                                )

                                        )

                                    [1] => SMW\Query\Language\SomeProperty Object
                                        (
                                            [description:protected] => SMW\Query\Language\ValueDescription Object
                                                (
                                                    [dataItem:SMW\Query\Language\ValueDescription:private] => SMW\DIWikiPage Object
                                                        (
                                                            [m_dbkey:protected] => Value2
                                                            [m_namespace:protected] => 0
                                                            [m_interwiki:protected] => 
                                                            [m_subobjectname:protected] => 
                                                            [sortkey:SMW\DIWikiPage:private] => 
                                                        )

                                                    [comparator:SMW\Query\Language\ValueDescription:private] => 1
                                                    [property:SMW\Query\Language\ValueDescription:private] => SMW\DIProperty Object
                                                        (
                                                            [m_key:SMW\DIProperty:private] => Prop2
                                                            [m_inverse:SMW\DIProperty:private] => 
                                                            [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                        )

                                                    [m_printreqs:protected] => Array
                                                        (
                                                        )

                                                )

                                            [property:protected] => SMW\DIProperty Object
                                                (
                                                    [m_key:SMW\DIProperty:private] => Prop2
                                                    [m_inverse:SMW\DIProperty:private] => 
                                                    [m_proptypeid:SMW\DIProperty:private] => _wpg
                                                )

                                            [m_printreqs:protected] => Array
                                                (
                                                )

                                        )

                                )

                            [classDescription:SMW\Query\Language\Disjunction:private] => 
                            [isTrue:SMW\Query\Language\Disjunction:private] => 
                            [m_printreqs:protected] => Array
                                (
                                )

                        )

                )

            [m_printreqs:protected] => Array
                (
                    [0] => SMW\Query\PrintRequest Object
                        (
                            [m_mode:protected] => 2
                            [m_label:protected] => 
                            [m_data:protected] => 
                            [m_typeid:protected] => 
                            [m_outputformat:protected] => 
                            [m_hash:protected] => 
                            [m_params:protected] => Array
                                (
                                )

                        )

                )

        )

    [errors:SMWQuery:private] => Array
        (
        )

    [queryString:SMWQuery:private] => <q>[[Prop1::Value1]] OR [[Prop1::Value2]]</q> AND <q>[[Prop2::Value1]] OR [[Prop2::Value2]]</q>
```

**Comment by mwjames** [comment]
After another look (and incorporating the proposed change) on this issue the

* `Issue19/A` with [[Prop1::Value1]] [[Prop2::Value1]]
* `Issue19/B` with [[Prop1::Value2]] [[Prop2::Value2]]
* `Issue19/C` with [[Prop1::Value1]] [[Prop2::Value3]]
* `Issue19/D` with [[Prop1::Value2]]

`[[Prop1::Value1||Value2]] [[Prop2::Value1||Value2]]` would produce
```
Debug Output by SQLStore
Generated Wiki-Query
[[Prop1::Value1||Value2]] [[Prop2::Value1||Value2]]
Query Metrics
Query-Size:6
Query-Depth:1
SQL Query
SELECT DISTINCT t11.smw_title AS t,t11.smw_namespace AS ns FROM `smw_object_ids` AS t11 INNER JOIN `smw_di_wikipage` AS t1 ON t11.smw_id=t1.s_id INNER JOIN `t3` AS t3 ON t1.o_id=t3.id INNER JOIN `smw_di_wikipage` AS t6 ON t1.s_id=t6.s_id INNER JOIN `t8` AS t8 ON t6.o_id=t8.id WHERE (t1.p_id='1955' AND (t6.p_id='1957')) ORDER BY t11.smw_sortkey ASC LIMIT 55 OFFSET 0;
Auxilliary Tables Used
Temporary table t3
  INSERT IGNORE INTO `t3` (id) VALUES ('1956')
  INSERT IGNORE INTO `t3` (id) VALUES ('1959')
Temporary table t8
  INSERT IGNORE INTO `t8` (id) VALUES ('1956')
  INSERT IGNORE INTO `t8` (id) VALUES ('1959')
Errors and Warnings
None
```

and `<q>[[Prop1::Value1]] OR [[Prop1::Value2]]</q> AND <q>[[Prop2::Value1]] OR [[Prop2::Value2]]</q>`

```
Generated Wiki-Query
  [[Prop1::Value1]]  OR  [[Prop1::Value2]]     [[Prop2::Value1]]  OR  [[Prop2::Value2]]  
Query Metrics
Query-Size:8
Query-Depth:1
SQL Query
SELECT DISTINCT t15.smw_title AS t,t15.smw_namespace AS ns FROM `smw_object_ids` AS t15 INNER JOIN `t1` AS t1 ON t15.smw_id=t1.id INNER JOIN `t8` AS t8 ON t1.id=t8.id ORDER BY t15.smw_sortkey ASC LIMIT 55 OFFSET 0;
Auxilliary Tables Used
Temporary table t1
  INSERT IGNORE INTO `t1` SELECT t2.s_id FROM `smw_di_wikipage` AS t2 WHERE t2.p_id='1955' AND t2.o_id='1956'
  INSERT IGNORE INTO `t1` SELECT t5.s_id FROM `smw_di_wikipage` AS t5 WHERE t5.p_id='1955' AND t5.o_id='1959'
Temporary table t8
  INSERT IGNORE INTO `t8` SELECT t9.s_id FROM `smw_di_wikipage` AS t9 WHERE t9.p_id='1957' AND t9.o_id='1956'
  INSERT IGNORE INTO `t8` SELECT t12.s_id FROM `smw_di_wikipage` AS t12 WHERE t12.p_id='1957' AND t12.o_id='1959'
Errors and Warnings
None
```

Both queries would return with `Issue19/A` and `Issue19/B` as expected result subjects.

**Comment by vitalif** [comment]
i.e. do you say everything is ok now? :)

**Comment by mwjames** [comment]
> i.e. do you say everything is ok now? :)

As I said (due to #1056) I had to do another look and using your proposed change the result is as reported above which means it needs to be added but I'd like to have some other OR/AND queries added as test case before to ensure we don't create an oversight.

I did quick test run against https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/tests/phpunit/Integration/Query/Fixtures and queries seemed to run as expected with the proposed changed.

**Comment by mwjames** [comment]
Merged with 4bcfea2

@vitalif Thanks for the PR and sorry that it took so long. I hope the added integration tests will keep us safe from a possible unanticipated oversight.

**Pull request closed without merging**
