### PR TITLE
Fix RAND query for sqlite, refs #764

### PR DESCRIPTION
**Pull request by mwjames**
refs #764

### CODE REVIEW

**Comment by mwjames** [comment]
It turns out not only sqlite has an issue with `RAND` but also postgres.

```
SMW\Tests\Integration\Query\RandomQueryResultOrderIntegrationTest::testRandomOrder
pg_query(): Query failed: ERROR:  function rand() does not exist
LINE 1: ....smw_id=t0.s_id  WHERE (t0.p_id='134')  ORDER BY  RAND()  LI...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by mwjames** [comment]
Next issue for `postgres` is `  for SELECT DISTINCT, ORDER BY expressions must appear in select list`:

```
1) SMW\Tests\Integration\Query\RandomQueryResultOrderIntegrationTest::testRandomOrder
pg_query(): Query failed: ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ....smw_id=t0.s_id  WHERE (t0.p_id='134')  ORDER BY  RANDOM()  ...
```

http://stackoverflow.com/questions/11401229/how-to-use-select-distinct-with-random-function-in-postgresql

**Comment by mwjames** [comment]
@JeroenDeDauw Using `RANDOM` with postgres is a bit more complicated than switching the function, apparently `SELECT DISTINCT` and `RANDOM` do not work together [0] in ways specified by `sqlite` or `mysql`. I propose we do not support `RANDOM` (function just being set `` to avoid any failure) on postgres otherwise you would have to re-write [1].

[0] http://www.postgresql.org/message-id/27009.1171559417@sss.pgh.pa.us

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/includes/storage/SQLStore/SMW_SQLStore3_Queries.php#L385

**Comment by JeroenDeDauw** [comment]
Two questions:

1. what is this used for anyway? sort=random in ask queries?

2. have you looked at DBAL to see if it provides a usable abstraction?

**Comment by mwjames** [comment]
> what is this used for anyway? sort=random in ask queries?

Yes (order=random) and it would create a failure for `sqlite` and `postgres` as seen in #764.

> have you looked at DBAL to see if it provides a usable abstraction?

No

**Comment by JeroenDeDauw** [comment]
So far for our complete SQLite and Postgres support :)

**Comment by JeroenDeDauw** [comment]
watz

**Comment by mwjames** [comment]
> So far for our complete SQLite and Postgres support :)

SQLite is fine but postgres is a pain (similar to the  `Concept` https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/779#issuecomment-73592464 issue).

**Comment by JeroenDeDauw** [comment]
I can't find anything in the DBAL docs. Asking on IRC now

**Comment by mwjames** [comment]
The postgres issues hasn't been solved satisfactory but to avoid any failures the current approach is to disable random support for postgres.

**Comment by JeroenDeDauw** [comment]
> JeroenDeDauw | Does DBAL have a suitable abstraction that I can use?

> zeroedin-bill | afaik no, doctrine doesnt have a convenient way to do that, as it varies between vendors a lot

**Comment by yoonghm** [comment]
MySQL allowing **non-select column to be used for sorting provided** only **safe** or **correct** under certain condition. Other RDBMS's do not allow this is actually doing the right thing. [0].

Does it really make sense to have this feature?

[0] http://www.programmerinterview.com/index.php/database-sql/sql-select-distinct-and-order-by/

**Pull request merged**
