### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #

This PR addresses or contains:
- Add MySQL and PHP 5.6 as the most popular environment to test if MW 1.30.x is working with SMW 2.5.x

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #

### CODE REVIEW

**Comment by mwjames** [comment]
> - Add MySQL and PHP 5.6 as the most popular environment to test if MW 1.30.x
> is working with SMW 2.5.x

>Notice: unserialize(): Error at offset 32 of 33 bytes in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/vendor/phpunit/phpunit-mock-objects/PHPUnit/Framework/MockObject/Generator.php on line 247

You need to add an appropriate PHPUNIT (see the 3.0 travis file).

**Comment by kghbln** [comment]
> You need to add an appropriate PHPUNIT (see the 3.0 travis file).

Thanks for the note. There were a couple of tests without PHPUnit so I figured. However looking at them closer ...

**Comment by mwjames** [comment]
Failed because of:

> 1) SMW\Tests\MediaWiki\Api\BrowseBySubjectTest::testExecuteForInvalidSubjectThrowsException
Use of ApiBase::dieUsage was deprecated in MediaWiki 1.29. [Called from SMW\MediaWiki\Api\BrowseBySubject::getRawFormat in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Api/BrowseBySubject.php at line 80]

#2553

>There was 1 failure: 1) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::executeTestCases with data set "s-0014.json" ('/home/travis/build/SemanticMe...4.json')
Failed on `#0` for <div data-subject="Example/S0014/L&#039;oéal#0#" data-options="{&quot;

I'm guessing #2827 is biting!

Those are tests are failing because of MW not because SMW has a dysfunctional implementation.

**Comment by kghbln** [comment]
> #2553

https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2941

> #2827

https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2959

Should the respective pull be piggybacked to this branch by back-porting them? I guess so.

**Comment by mwjames** [comment]
I looked at them and they should not carry any risk on bringing down the 2.5.x branch. Maybe the added msg in #2941 can cause a conflict due to msg files being out of sync.

**Comment by kghbln** [comment]
#2959 was also creating a conflict for "tests/phpunit/JsonTestCaseFileHandler.php". Hopefully I resolved correctly.

**Comment by kghbln** [comment]
@mwjames I believe we are now in fluff. I guess we could do a 2.5.6 release next week and officially declare compatibility with MW 1.30.

**Comment by mwjames** [comment]
>#2959 was also creating a conflict for "tests/phpunit/JsonTestCaseFileHandler.php". Hopefully I resolved correctly.

Nice follow-up.

> @mwjames I believe we are now in fluff. I guess we could do a 2.5.6 release next week

:+1:

**Pull request merged**
