### PR TITLE
Fix "Trying to access array offset on value of type ...", refs 4545, 4547, 4541, 4308

### LINKED ISSUE #4308: PropertyLabelFinder::findCanonicalPropertyLabelById returns bool
Users of this code are not expecting that which leads to warnings and likely bugs.

Warnings: https://gist.github.com/mszabo-wikia/bf2745970f308a24c908c1b4734acb37 (most are caused by this issue, some by https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/4307) (originally reported in https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/4294)

### LINKED ISSUE #4541: Notices and warnings on PHP 7.4
### Setup and configuration

image

image

### Issue
Okay so I installed SMW with composer. I added
 "mediawiki/semantic-media-wiki": "~3.1"
and followed the installation instructions at https://www.semantic-mediawiki.org/wiki/Help:Installation/Quick_guide

Now if I go to random pages on my wiki, I get this error at the top and bottom of my pages:

### Stack trace
image

If I hit refresh (sometime a couple times) the errors go away. On the mage page of the wiki though, the error stays no matter what I do. I tried disabling all extensions. The errors stay. I tried rolling back and doing the install again ( a couple times) and the errors stay.

anyone with any clues on whats going on?

```

Notice: Trying to access array offset on value of type bool in /var/www/worldafropedia/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

Notice: Trying to access array offset on value of type bool in /var/www/worldafropedia/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

Notice: Trying to access array offset on value of type bool in /var/www/worldafropedia/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

Notice: Trying to access array offset on value of type bool in /var/www/worldafropedia/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

Notice: Trying to access array offset on value of type bool in /var/www/worldafropedia/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

Notice: Trying to access array offset on value of type bool in /var/www/worldafropedia/wiki/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508
```

### Steps to reproduce
If I go to any page while SMW is active, the pages load, but the errors are at the top and/or bottom of the content. If I disable SMW, the errors arent there.

### LINKED ISSUE #4545: Type mismatches
PHP 7.4.2, MW 1.34.0, SMW 3.1.3.

Sometimes, `maintamance/runJobs.php` and `maintenance/fixDoubleRedirects.php` issue warnings like this:
```
2020-02-12 20:40:02 refreshLinksPrioritized Шаблон:Tnavbar isOpportunistic=1 rootJobTimestamp=20200212202618 namespace=10 title=Tnavbar requestId=c8b843c55ee62b88a4d07cd2 causeAction=unknown causeAgent=unknown (id=12874279,timestamp=20200212202618) STARTING
PHP Notice:  Trying to access array offset on value of type int in /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 469
PHP Notice:  Trying to access array offset on value of type bool in /var/www/wiki/w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php on line 508

```

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #4545, #4547, #4541, #4308

This PR addresses or contains:

- PHP 7.4+ started to emit a "Trying to access array offset on value of type ..." warning when trying to access an offset on a non string type

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes #4545, Fixes #4541, Fixes #4308

### CODE REVIEW

**Comment by mwjames** [comment]
The change in PHP 7.4+ to emit "Trying to access array offset on value of type ..." on non strings is unhelpful and creates unnecessary work in casting values to strings to avoid the warning. Anyway, with this PR the remaining issue on PHP 7.1/ MW 1.35 are:

No idea what "ApiUsageException: Unrecognized value for parameter "api_version": 2.
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiUsageException.php:68" is about!

```
There were 3 errors:
1) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "a-0002.json" ('/home/travis/build/SemanticMe...2.json')
ApiUsageException: Unrecognized value for parameter "api_version": 2.
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiUsageException.php:68
/home/travis/build/SemanticMediaWiki/mw/includes/api/Validator/ApiParamValidator.php:326
/home/travis/build/SemanticMediaWiki/mw/includes/api/Validator/ApiParamValidator.php:352
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiBase.php:1033
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiBase.php:686
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiMain.php:1185
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiMain.php:1569
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiMain.php:491
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/MwApiFactory.php:63
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/ApiTestCaseProcessor.php:76
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/ExtendedJsonTestCaseScriptRunner.php:220
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/ExtendedJsonTestCaseScriptRunner.php:52
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/JsonTestCaseScriptRunner.php:232
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/DatabaseTestCase.php:173
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:99
Caused by
Wikimedia\ParamValidator\ValidationException: Validation of `api_version` failed: badvalue
/home/travis/build/SemanticMediaWiki/mw/includes/libs/ParamValidator/TypeDef.php:60
/home/travis/build/SemanticMediaWiki/mw/includes/libs/ParamValidator/TypeDef/EnumDef.php:78
/home/travis/build/SemanticMediaWiki/mw/includes/libs/ParamValidator/ParamValidator.php:595
/home/travis/build/SemanticMediaWiki/mw/includes/libs/ParamValidator/ParamValidator.php:549
/home/travis/build/SemanticMediaWiki/mw/includes/api/Validator/ApiParamValidator.php:350
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiBase.php:1033
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiBase.php:686
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiMain.php:1185
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiMain.php:1569
/home/travis/build/SemanticMediaWiki/mw/includes/api/ApiMain.php:491
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/MwApiFactory.php:63
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/ApiTestCaseProcessor.php:76
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/ExtendedJsonTestCaseScriptRunner.php:220
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/ExtendedJsonTestCaseScriptRunner.php:52
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/JsonTestCaseScriptRunner.php:232
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/DatabaseTestCase.php:173
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:99
```

Some "Use of Title::userCan was deprecated in MediaWiki 1.33. [Called from SMW\Protection\ProtectionValidator::hasEditProtection in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Protection/ProtectionValidator.php at line 197]"

```
2) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "p-0111.json" ('/home/travis/build/SemanticMe...1.json')
Use of Title::userCan was deprecated in MediaWiki 1.33. [Called from SMW\Protection\ProtectionValidator::hasEditProtection in /home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Protection/ProtectionValidator.php at line 197]
/home/travis/build/SemanticMediaWiki/mw/includes/debug/MWDebug.php:333
/home/travis/build/SemanticMediaWiki/mw/includes/debug/MWDebug.php:265
/home/travis/build/SemanticMediaWiki/mw/includes/GlobalFunctions.php:1046
/home/travis/build/SemanticMediaWiki/mw/includes/Title.php:2414
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Protection/ProtectionValidator.php:197
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Property/DeclarationExaminer/ProtectionExaminer.php:71
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Property/DeclarationExaminer/ProtectionExaminer.php:48
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Property/DeclarationExaminer/DeclarationExaminer.php:80
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Property/DeclarationExaminer/DeclarationExaminer.php:78
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Property/DeclarationExaminer/DeclarationExaminer.php:78
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Page/PropertyPage.php:109
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Page/Page.php:92
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/ParserTestCaseProcessor.php:190
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/ParserTestCaseProcessor.php:109
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/LightweightJsonTestCaseScriptRunner.php:308
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/LightweightJsonTestCaseScriptRunner.php:117
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/ExtendedJsonTestCaseScriptRunner.php:48
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/JsonTestCaseScriptRunner.php:232
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/DatabaseTestCase.php:173
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:99
```

Cannot be fixed by SMW because it is related to the `vendor/zordius/lightncandy` library.

```
3) SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest::testCaseFile with data set "s-0027.json" ('/home/travis/build/SemanticMe...7.json')
implode(): Passing glue string after array is deprecated. Swap the parameters
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:306
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:715
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:375
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:64
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/LightnCandy.php:51
/home/travis/build/SemanticMediaWiki/mw/includes/TemplateParser.php:188
/home/travis/build/SemanticMediaWiki/mw/includes/TemplateParser.php:143
/home/travis/build/SemanticMediaWiki/mw/includes/TemplateParser.php:221
/home/travis/build/SemanticMediaWiki/mw/includes/changes/RSSFeed.php:84
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Query/ResultPrinters/FeedExportPrinter.php:215
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Query/ResultPrinters/FeedExportPrinter.php:178
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php:337
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Query/ResultPrinters/ResultPrinter.php:302
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/Query/ResultPrinters/FeedExportPrinter.php:82
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php:338
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/src/MediaWiki/Specials/SpecialAsk.php:170
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/SpecialPageTestCaseProcessor.php:108
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/Utils/JSONScript/SpecialPageTestCaseProcessor.php:88
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/LightweightJsonTestCaseScriptRunner.php:367
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/LightweightJsonTestCaseScriptRunner.php:119
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/ExtendedJsonTestCaseScriptRunner.php:48
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/JsonTestCaseScriptRunner.php:232
/home/travis/build/SemanticMediaWiki/mw/extensions/SemanticMediaWiki/tests/phpunit/DatabaseTestCase.php:173
/home/travis/build/SemanticMediaWiki/mw/maintenance/doMaintenance.php:99
--
```

**Comment by mwjames** [comment]
```
implode(): Passing glue string after array is deprecated. Swap the parameters
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:306
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:715
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:375
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/Compiler.php:64
/home/travis/build/SemanticMediaWiki/mw/vendor/zordius/lightncandy/src/LightnCandy.php:51
```

Should be reported to the WMF guys and they should see to it that it gets fixed.

**Comment by reedy** [comment]
> Should be reported to the WMF guys and they should see to it that it gets fixed.

I've been trying for 5 weeks since we upgraded the version of lightncandy in MW core...

**Comment by kghbln** [comment]
> I've been trying for 5 weeks since we upgraded the version of lightncandy in MW core...

I believe you are in the loop. Thanks for your effort. Touching wood!

**Comment by reedy** [comment]
I did get some traction fixing up some of the other PHP 7.4 issues (for some reason, they fixed one of the implode issues, but not the others...), and some other general cleanup. Finding out that the tests failing didn't make travis fail the build wasn't exactly great either, so hopefully that lands too

Fingers crossed we can get it sorted and a release; we (as the wider MediaWiki community) can't be the only people potentially affected by this.

https://github.com/zordius/lightncandy/network/dependents suggests 554 repositories (possibly including forks and stuff?), and 28 packagist packages... I know PHP 7.4 is still relatively new (7.4.0 isn't even 3 months old as of writing), but the usages are only going to increase, so I would suspect people complaining over there will only increase if a release isn't tagged soon to be incorporated into other releases. I might have a look later at the other reports that led to some of the fixes, and try and gain some further traction/support to the issue. However Zordius only seems to be intermittently active, for whatever reason :(

MW 1.35 isn't due for release for a few months still, so hopefully we'll have a proper fix for it by then, rather than having to fork it to just include a couple of patches... Even more so with MW 1.35 being an LTS that we've got to support till June 2023 (even if we can backport a vendor library bump, it'd be nice to have this resolved by the final version of 1.35.0).... And as per #4547 at least the SMW release isn't due immediately either

**Comment by alex-mashin** [comment]
This patch is not a part of SMW 3.1.6, is it?

**Comment by hexmode** [comment]
> This patch is not a part of SMW 3.1.6, is it?

Doesn't look like it: #4735

**Comment by JeroenDeDauw** [comment]
I'm hopeful we will have the 3.2 release out in the next week or two.

**Pull request merged**
