### PR TITLE
Fix category / owl:Class declaration for vocab import, #1081

### PR DESCRIPTION
**Pull request by mwjames**

### CODE REVIEW

**Comment by mwjames** [comment]
Backported with 37740a3 to 2.2.x.

**Comment by mwjames** [comment]
@kghbln 2.2.2 patch release for https://github.com/SemanticMediaWiki/SemanticMediaWiki/compare/2.2.1...2.2.x?

**Comment by kghbln** [comment]
:+1:

**Comment by jaideraf** [comment]
:+1: thanks @mwjames

**Comment by mwjames** [comment]
> 2.2.2 patch release

Done with https://github.com/SemanticMediaWiki/SemanticMediaWiki/releases/tag/2.2.2

**Comment by kghbln** [comment]
:+1: Just done with publicising it + Sourceforge.

**Pull request merged**
