### PR TITLE
Faster builds

### PR DESCRIPTION
**Pull request by paladox**
https://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by mwjames** [comment]
We need sudo, this will not work for SMW.

**Comment by paladox** [comment]
I doint see any sudo in travis ci file on this repo.

**Comment by mwjames** [comment]
> I doint see any sudo in travis ci file on this repo.

Please have a look at the file linked, SMW uses extra services beyond the normal MW setup to allow for an elaborate test environment.

image

**Comment by paladox** [comment]
Oh ok. Sorry I wasn't able to view any build information since it keeps erroring out everytime I go to the link. But since it is using sudo apt you can change it Like it was in https://github.com/hexchat/hexchat/commit/edd57fdc868c2547a182705ffbf478ea4134169d

**Comment by JeroenDeDauw** [comment]
That's cool @paladox. Thanks for the suggestion!

**Comment by mwjames** [comment]
> But since it is using sudo apt you can change it Like it was in hexchat/hexchat@edd57fd

That won't work, it requires whitelisted packages and we use things like `sudo chown -R tomcat6:tomcat6 /usr/share/tomcat6`.

**Comment by paladox** [comment]
You can request that packages you want can be whitelisted at https://github.com/travis-ci/apt-package-whitelist

**Comment by paladox** [comment]
https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

**Pull request closed without merging**
