### PR TITLE
Add support for mandatory properties, refs 2669

### LINKED ISSUE #2669: Mandatory properties, "empty" properties, and the search for non-existing assignments
refs: https://sourceforge.net/p/semediawiki/mailman/message/36025265/

## Issue

As noted in an old email exchange [0], finding any non-existing assignments to a property is a herculean effort that if you use an inverted index (as those in a triple store) and a special syntax [1] in `SPARQL` is less of a problem.

For the `SQLStore` we don't have that luxury and creating an inverted index via the RDBMS layer isn't an affordable practice.

## Proposal

Hence this proposal goes into a different direction, instead of trying to prove that something does not exists by matching all existing members and compare them, we use the so called mandatory properties and a `NULL` assignment with the support of `!+` (such as `[[SomeProperty::!+]]`) to declare all `NULL`  (means no real value) matched instances as being "non-existing assignments" in context of any other value assignment.

This proposal is about an affordable (in terms of codifying the outlined requirements) practice that offers a solution for the long standing issue of finding specific properties that have no value assigned.

Under the premise that proving the existence can be easily validated using the current RDBMS, we will use `NULL` as technical identity for that purpose which by normal means cannot be assigned through any user action.

Since we cannot assume users to be a responsible in the amount [2] of properties used or declared, updating any entity with those from an arbitrary list of properties would seem to invite performance issues from the start and therefore the approach of mandatory properties is introduced with:

- Setting `$smwgMandatoryProperties`  declares a list of properties that are expected to exists on each single entity created (e.g. `$smwgMandatoryProperties = [  'Has description', 'Has keyword' ]`)
- Parser function `{{#mandatory: ... }}` can be used to override that list as in `{{#mandatory: |property=Age, AnotherValue ...}}` on each subject (it also invalidates the list declared in `smwgMandatoryProperties` for this subject)
- The definition of mandatory properties is extended to user defined subobjects that are embedded in the subject where above rules applies as well
- Any update will ensure that those listed requirements are reevaluated
- Query syntax `!+` can be used to find those entities that have not been assigned as in `{{#ask: [[AnotherValue::!+]]`

Using either `$smwgMandatoryProperties` or `{{#mandatory: ... }}` allows us to control which properties are required and mandatory during the update process.

When changing the content of `$smwgMandatoryProperties` , running the `rebuildData` script is required since each subject has to be reevaluated against the altered list of mandatory properties. Changing the content of `{{#mandatory: ... }}` does not require `rebuildData` since each subject will be reevaluated during the update itself.

Assignments with a `NULL` value will not be listed in `Special:Browse` or the `Property:...` page.

## Use case

A simple document management system with the requirement that each document (article) contains:

- Document version
- Document status
- Document description
- Keywords

Document SomeDocument

```
{{Document
 |version=123
}}
```

Template: Document
```
<includeonly>

* [[Document version::{{{version|}}}]]
* [[Document status::{{{status|}}}]]
* [[Document description::{{{description|}}}]]
* {{#set: |Has keyword={{{keyword|}}} |+sep=, |template=FormatKeywordValue}}

{{#mandatory:
 |property=Document version, Document status, Document description, Has keyword
}} [[Category:Document]]
</includeonly>
```

A query to list all entities where a `Document description` assignment is missing.
```
{{#ask: [[Category:Document]] [[Document description::!+]]
 |format=table
}}
```

## Performance

- Updates are performed on listed properties which is limited and should therefore not have any significant impact.
- Query execution is done on a `NULL` value (as `IS NULL` and `IS NOT NULL`) therefore should use the existing table indices
- Depending on the list of requested mandatory properties, table entries with `NULL` will increase but once assigned a discrete value, the `NULL` is replaced and will use the same table space

## Limitations

Categories are a somewhat difficult topic in this respect and are therefore __not__ covered here.

[0] http://wikimedia.7.x6.nabble.com/Empty-property-query-possible-td556352.html
[1] https://stackoverflow.com/questions/7097307/selecting-using-sparql-based-on-triple-does-not-exist
[2] https://wikiapiary.com/wiki/Semantic_statistics (see `The Third Turn` with `1,101,729` used properties)

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2669

This PR addresses or contains:

- Implements requirements as outlined in #2669
- Adds `#mandatory` parser function and `$smwgMandatoryProperties` setting
- Does NOT add support in `SPARQLStore` for the newly added `!+` syntax
- Missing unit and integration tests, for now changes at least pass the existing test suite which means that the PR does not introduce any testable regression

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #2669

### CODE REVIEW

**Comment by mwjames** [comment]
I probably missed something during the coding sprint therefore having this tested by hand before the merge would be highly appreciated.

**Comment by jaideraf** [comment]
> ... having this tested by hand before the merge would be highly appreciated.

@mwjames when I `composer update` to `dev-mandatory`, `php maintenance/update.php`, and I just created a new property (even without set up `$smwgMandatoryProperties`), I got:

```
[WbfYaFPPUe3ASie5QD-OIQAAAAg] /w/index.php?title=Property:Has_child&action=formedit Error from line 169 of /w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php: Call to undefined method SMWSql3StubSemanticData::setMandatoryProperties()

Backtrace:

#0 /w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3.php(265): SMWSQLStore3Writers->doDataUpdate(SMWSql3StubSemanticData)
#1 /w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(220): SMWSQLStore3->doDataUpdate(SMWSql3StubSemanticData)
#2 /w/extensions/SemanticMediaWiki/src/Updater/StoreUpdater.php(262): SMW\Store->updateData(SMWSql3StubSemanticData)
#3 /w/extensions/SemanticMediaWiki/src/Updater/StoreUpdater.php(170): SMW\Updater\StoreUpdater->updateData()
#4 /w/extensions/SemanticMediaWiki/src/Updater/StoreUpdater.php(126): SMW\Updater\StoreUpdater->performUpdate()
#5 /w/extensions/SemanticMediaWiki/src/ParserData.php(452): SMW\Updater\StoreUpdater->doUpdate()
#6 [internal function]: SMW\ParserData->SMW\{closure}()
#7 /w/extensions/SemanticMediaWiki/src/Updater/DeferredCallableUpdate.php(236): call_user_func(Closure)
#8 /w/extensions/SemanticMediaWiki/src/Updater/DeferredTransactionalUpdate.php(134): SMW\Updater\DeferredCallableUpdate->doUpdate()
#9 /w/extensions/SemanticMediaWiki/src/Updater/DeferredCallableUpdate.php(265): SMW\Updater\DeferredTransactionalUpdate->doUpdate()
#10 /w/extensions/SemanticMediaWiki/src/ParserData.php(468): SMW\Updater\DeferredCallableUpdate->pushUpdate()
#11 /w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/LinksUpdateConstructed.php(94): SMW\ParserData->updateStore(boolean)
#12 /w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/HookRegistry.php(363): SMW\MediaWiki\Hooks\LinksUpdateConstructed->process(LinksUpdate)
#13 /w/includes/Hooks.php(186): SMW\MediaWiki\Hooks\HookRegistry->SMW\MediaWiki\Hooks\{closure}(LinksUpdate)
#14 /w/includes/deferred/LinksUpdate.php(160): Hooks::run(string, array)
#15 /w/includes/content/AbstractContent.php(234): LinksUpdate->__construct(Title, ParserOutput, boolean)
#16 /w/includes/page/WikiPage.php(2168): AbstractContent->getSecondaryDataUpdates(Title, NULL, boolean, ParserOutput)
#17 /w/includes/page/WikiPage.php(1789): WikiPage->doEditUpdates(Revision, User, array)
#18 [internal function]: WikiPage->{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#19 /w/includes/libs/rdbms/database/Database.php(2693): call_user_func_array(Closure, array)
#20 /w/includes/deferred/AtomicSectionUpdate.php(35): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#21 /w/includes/deferred/DeferredUpdates.php(257): AtomicSectionUpdate->doUpdate()
#22 /w/includes/deferred/DeferredUpdates.php(210): DeferredUpdates::runUpdate(AtomicSectionUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#23 /w/includes/deferred/DeferredUpdates.php(127): DeferredUpdates::execute(array, string, integer)
#24 /w/includes/MediaWiki.php(603): DeferredUpdates::doUpdates(string, integer)
#25 /w/includes/MediaWiki.php(572): MediaWiki::preOutputCommit(RequestContext, Closure)
#26 /w/includes/MediaWiki.php(878): MediaWiki->doPreOutputCommit(Closure)
#27 /w/includes/MediaWiki.php(523): MediaWiki->main()
#28 /w/index.php(43): MediaWiki->run()
#29 {main}

Notice: JobQueueGroup::__destruct: 1 buffered job(s) of type(s) SMW\MediaWiki\Jobs\ChangePropagationDispatchJob never inserted. in /w/includes/jobqueue/JobQueueGroup.php on line 451
```

**Comment by kghbln** [comment]
@jaideraf Hmm, this destructable jobs look like you are seeing an issue of MediaWiki which struggles along its way down to SMW. Which version of MW are you using? You could try master of any REL and see if it is still there.

**Comment by jaideraf** [comment]
Oh, yes, sorry, I forgot to mention. I am using the updated `REL1_29, PHP 7.0.22 (cgi-fcgi), MySQL 5.6.37-82.2.`

The error is still there. I know nothing about MW or SMW internal things, but before de JobQueue notice there is

Error from line 169 of SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php: **Call to undefined method SMWSql3StubSemanticData::setMandatoryProperties()**

Maybe, fixing the MandatoryProperties thing could fix the JobQueue thing.

**Comment by kghbln** [comment]
Ah my mistake, too. I did not scroll to the right. :| Yeah this indeed looks like an issue here. Thanks for your effort!

**Comment by mwjames** [comment]
> [WbfYaFPPUe3ASie5QD-OIQAAAAg] /w/index.php?title=Property:Has_child&action=formedit 
Error from line 169 of /w/extensions/SemanticMediaWiki/includes/storage/SQLStore/SMW_SQLStore3_Writers.php: 
Call to undefined method SMWSql3StubSemanticData::setMandatoryProperties()

> Ah my mistake, too. I did not scroll to the right. :| Yeah this indeed looks like an issue here.

My bad.

Thanks for testing (when only halfway through), I'll be making an update to the code and concept during the weekend and will respond to #2669 as well.

**Comment by kghbln** [comment]
> My bad.

@mwjames No worries. I wish I had half of your coding skills.

**Comment by mwjames** [comment]
Okay. let's try this again!

The expected behaviour is described in [0] together with what and how to test. As noted in [1] it is required :warning:  to run either `update.php` or `setupStore.php`.

To make debugging and testing a bit more rewarding, you can use `$wgDebugLogGroups` and see messages send by this PR with the following setting:

```
$wgDebugLogGroups  = array(
 'smw-mreq' => ".../tmp/logs/debug-test-{$wgDBname}.log"
);
```
which should output something like:

```
2017-09-17 15:32:31 ... mw-master: MandatoryRequirements: Created new GlobalRequirements list with 0 member(s)
2017-09-17 15:32:31 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Main_Page#0#
2017-09-17 15:33:00 ... mw-master: MandatoryRequirements: GlobalRequirements cache invalidated due to a ChangePropListener event
2017-09-17 15:33:00 ... mw-master: MandatoryRequirements: GlobalRequirements cache invalidated due to a ChangePropListener event
2017-09-17 15:33:12 ... mw-master: MandatoryRequirements: Adding LocalRequirements on NullTest#0# with 2 member(s)
2017-09-17 15:33:12 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on NullTest#0#
2017-09-17 15:33:12 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on NullTest#0##_a6acf6df3faac485376b65b28a51f663
2017-09-17 15:33:44 ... mw-master: MandatoryRequirements: Created new GlobalRequirements list with 1 member(s)
2017-09-17 15:33:45 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Lorem_ipsum-1eab#0#
2017-09-17 15:33:45 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Lorem_ipsum-1eab#0##_0bb59d34944b1eb887e08dcf5d07fc3b
2017-09-17 15:33:45 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Lorem_ipsum-1eab#0##f1
2017-09-17 15:33:45 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Lorem_ipsum-1eab#0##f2
2017-09-17 15:33:45 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Lorem_ipsum-1eab#0##f3
2017-09-17 15:33:45 ... mw-master: MandatoryRequirements: Checking requirements (PropertyTableRowDiffer) on Lorem_ipsum-1eab#0##f4
```

Default setting is:

```
	'smwgMandatoryRequirementsNamespaceList' => [
		NS_MAIN => true
	],
```

We now cache the "Global requirements" list (those defined by `Is mandatory`) therefore `[[Is mandatory::true]]` will enable the requirement while `[[Is mandatory::false]]` (or its removal) will disable it.

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2669#issuecomment-329985998
[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/2680#issuecomment-329983369

**Comment by jaideraf** [comment]
I tested it, as described by https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2669#issuecomment-329985998 (and I changed the property to boolean datatype)...
It seems fine to me. Although `$wgDebugLogGroups` didn't worked, but I suspect that's is something to do with my environment... So: :+1: to the obtained result.

**Comment by mwjames** [comment]
> I tested it, as described by #2669 (comment) (and I changed the property to boolean datatype)...
It seems fine to me.

Thanks for the continuing effort and confirmation. I'll have to write some unit and integration tests first before this can be merged with master.

**Comment by mwjames** [comment]
Closing the PR for now, I may resurrect at at later time but currently it seems unfeasible that it will make the 3.0 cut.

**Pull request closed without merging**
