### PR TITLE
[ES] Try to fetch SIGTERM in `rebuildElasticIndex`

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #

This PR addresses or contains:

- On systems that support `pcntl_signal_dispatch` fetch the `SIGTERM` and reset the settings

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln FYI

When `rebuildElasticIndex` is run and for some reason the build is terminated (exception etc.) `refresh_interval` remains on `-1` (see [0]). This PR should help recover the `refresh_interval` setting from before the build (only works where `pcntl_signal_dispatch` is available, not on Windows) .

Currently, the sandbox `refresh_interval` is set to -1 [1] which is the reason why updates to the ES cluster (hereby the query) are delayed. Details on `refresh_interval` are described in [2].

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/tree/master/src/Elastic#refresh-interval
[1] https://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial:SemanticMediaWiki&action=elastic%2Fsettings
[2] https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_disable_refresh_and_replicas_for_initial_loads

**Comment by kghbln** [comment]
I suspect that this will not help the issues I am still experiencing with sandbox. I just tried to run `php update.php` and this script also fails though `"refresh_interval": "1s",` 
```
[9e1c139ec61b4b9ed36c8664] [no req]   Elasticsearch\Common\Exceptions\Forbidden403Exception from line 605 of /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php: {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}
Backtrace:
#0 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(279): Elasticsearch\Connections\Connection->process4xxError(array, array, array)
#1 /../w/vendor/react/promise/src/FulfilledPromise.php(25): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(array)
#2 /../w/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Closure, NULL, NULL)
#3 /../w/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Closure, NULL, NULL)
#4 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(299): GuzzleHttp\Ring\Core::proxy(GuzzleHttp\Ring\Future\CompletedFutureArray, Closure)
#5 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(177): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(array, Elasticsearch\Connections\Connection, Elasticsearch\Transport, array)
#6 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php(110): Elasticsearch\Connections\Connection->performRequest(string, string, array, string, array, Elasticsearch\Transport)
#7 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/AbstractNamespace.php(72): Elasticsearch\Transport->performRequest(string, string, array, array, array)
#8 /../w/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Namespaces/IndicesNamespace.php(897): Elasticsearch\Namespaces\AbstractNamespace->performRequest(Elasticsearch\Endpoints\Indices\Aliases\Update)
#9 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rollover.php(84): Elasticsearch\Namespaces\IndicesNamespace->updateAliases(array)
#10 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Indexer.php(182): SMW\Elastic\Indexer\Rollover->update(string)
#11 /../w/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(298): SMW\Elastic\Indexer\Indexer->setup()
#12 /../w/extensions/SemanticMediaWiki/maintenance/setupStore.php(161): SMW\Elastic\ElasticStore->setup()
#13 /../w/maintenance/doMaintenance.php(94): SMW\Maintenance\SetupStore->execute()
#14 /../w/extensions/SemanticMediaWiki/maintenance/setupStore.php(265): require_once(string)
#15 {main}
```

**Comment by kghbln** [comment]
I am just installing Kibana. Probably not having this is the issue. Apart form that there are contradictory information how to overcome the api lock.

**Comment by kghbln** [comment]
So it seems that Kibana is a hard requirement since Elasticsearch 6.3.1 and later. After installing it I got a bit further down the script but eventually failed with even thoug ES and Kibana were running.

```
...titlekey table already exists.
[02dd91f838cf4673575f0a4c] [no req]   SMW\Elastic\Exception\NoConnectionException from line 48 of /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rollover.php: Could not establish a connection to Elasticsearch using [{"host":"217.197.83.171","port":9200,"scheme":"http"},"localhost:9200"]
Backtrace:
#0 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Indexer.php(178): SMW\Elastic\Indexer\Rollover->update(string)
#1 /../w/extensions/SemanticMediaWiki/src/Elastic/ElasticStore.php(298): SMW\Elastic\Indexer\Indexer->setup()
#2 /../w/extensions/SemanticMediaWiki/src/Store.php(470): SMW\Elastic\ElasticStore->setup(boolean)
#3 /../w/includes/installer/DatabaseUpdater.php(482): SMW\Store::setupStore(boolean, SMW\Options)
#4 /../w/includes/installer/DatabaseUpdater.php(450): DatabaseUpdater->runUpdates(array, boolean)
#5 /../w/maintenance/update.php(200): DatabaseUpdater->doUpdates(array)
#6 /../w/maintenance/doMaintenance.php(94): UpdateMediaWiki->execute()
#7 /../w/maintenance/update.php(245): require_once(string)
#8 {main}
```
Trying to do an update.php for a third time again results in the original failure.

**Comment by kghbln** [comment]
I  will try [this](https://benjaminknofe.com/blog/2017/12/23/forbidden-12-index-read-only-allow-delete-api-read-only-elasticsearch-indices/) though in the end this appears to be bull to me. I believe 25 GB disk space should be sufficient to run ES for such a micro wiki as sandbox.

**Comment by kghbln** [comment]
Unbelievable. This worked.

**Comment by mwjames** [comment]
>  update.php and this script also fails though "refresh_interval": "1s",

The idea here is (for this particular PR) that when something aborts the script (as above) then it switches back the the original `refresh_interval` which should be 1s otherwise any abort would result in -1. The  `-1` is needed as refresh rate (as outlined in the ES documentation) to have an optimal throughput when doing bulk updates.

> So it seems that Kibana is a hard requirement since Elasticsearch 6.3.1

I'm unaware of this, xpack comes with the 6.3 but Kibana is a different product and I don't think it is a requirement unless I'm mistaken.

**Comment by mwjames** [comment]
> ...titlekey table already exists.
[02dd91f838cf4673575f0a4c] [no req]   SMW\Elastic\Exception\NoConnectionException from line 48 of /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rollover.php: Could not establish a connection to Elasticsearch using [{"host":"217.197.83.171","port":9200,"scheme":"http"},"localhost:9200"]
Backtrace:

Something happened here, `NoConnectionException` indicates that we cannot connect to ES.

**Comment by kghbln** [comment]
> I'm unaware of this, xpack comes with the 6.3 but Kibana is a different product and I don't think it is a requirement unless I'm mistaken.

Affirmative, Kibana is not a hard requirement. I somehow thought that xpack is connected with Kibana ... :(

**Comment by kghbln** [comment]
> Something happened here, NoConnectionException indicates that we cannot connect to ES.

Indeed, but I issued `curl 'http://localhost:9200/?pretty'` immediately after and got the expected result from a running ES.

In the end I fixed the issues by rebooting the server to give all these components a fresh start.

**Comment by mwjames** [comment]
> Indeed, but I issued curl 'http://localhost:9200/?pretty' immediately after and got the expected result from a running ES.

Could be related to #3247 because I switched from the standard ping (which uses the full access chain) to a "quick_ping" as we always ping ES first before we proceed to ensure we can replicate in safe mode.

**Pull request merged**
