### PR TITLE
Update squizlabs/php_codesniffer to 2.5.0

### PR DESCRIPTION
**Pull request by paladox**
Update squizlabs/php_codesniffer to 2.5.0

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Why disallow installation with 2.1 and 2.6?

**Comment by paladox** [comment]
This is updating to use a more recent version.

There is no 2.6.0 version either.

**Comment by JeroenDeDauw** [comment]
~2.1 already includes the most recent version. What you submitted now just disallows explicitly using older versions

**Comment by mwjames** [comment]
What is this PR about can be closed or merged?

**Comment by paladox** [comment]
This pr is updating squizlabs/php_codesniffer to 2.5.0.

**Comment by kghbln** [comment]
@paladox @mwjames We are already on version 2.6 of the mentioned software. So this may go?

**Pull request closed without merging**
