### PR TITLE
Add ElasticStore, refs 2274

### PR DESCRIPTION
**Pull request by mwjames**
This PR is made in reference to: #2274, #586 

This PR addresses or contains:

- Introduces the `ElasticStore` as interface between Semantic MediaWiki and Elasticsearch (aka ES) with the objective to provide ES as drop-in replacement for the SQL based __QueryEngine__ (not the entity or data store).
- Information about the how, the why, and any requirements can be found in the [readme](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/es/src/Elastic/README.md).
- It doesn't require or use any `CirrusSearch` specific elements or bindings, the implementation is genuine to avoid yet another MW dependency. Indices are separated and are not suppose to share any query context.

This PR includes:
- [x] Tests (unit/integration)
- [x] CI build passed

Fixes: #586, #2274

## ES and SMW

For the last couple of weeks we enabled ES and this branch on the sandbox to verify its functionality in a live setting and @kghbln can share some experiences. A [short video](https://www.youtube.com/watch?v=o2LSYRMOKBI) demonstrates some aspects of the supported functionality.

image

### Target audience

- `SQLStore` small wikis, technical novice users, non-technical environments
- `SPARQLStore` RDF enthusiast, semantic web researchers
- `ElasticStore` enterprise users, wiki farms

## What's next?

This PR is tested with ES 6.1.x and 6.2.x (sandbox) and ES 5.6.6 (Travis) with the test suite which means that all test cases pass as they do with the `SQLStore` (or respectively `SPARQLStore`). Yet, this PR does not provide any tests on its own and before the PR can be merged it requires some effort to reach a coverage that is necessary for a merge.

As a result, SMW 3.0 will not be released in Q1/2018 and pending the progress of this PR and how good the documentation incorporates changes made in SMW 3.0 (see #2762) further postponement may be necessary.

### CODE REVIEW

**Comment by kghbln** [comment]
https://www.semantic-mediawiki.org/w/index.php?title=Help:SMWElasticSearch

**Comment by agcunha** [comment]
I'm an enterprise user, interested in continue using sparql store for graphs. AWS launches Neptune that will be a nice, fast and robust option for creating knowledge bases. In my point of view, key/value stores, like lucene used in Elastic or Solr, aren't the best architecture for knowledge representation. It could be used to develop search engines(eg: OpenSemanticSearch) because of the capabilities to process different formats of documents. OCR, text mining and index. What is the motivation to use Elastic in the architecture of SMW? I'm sorry if it's not the right channel to ask this.

**Comment by mwjames** [comment]
> I guess #2274 is the better spot.

Yes (see https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2274#issuecomment-381318251).

This PR is about the technical implementation.

**Comment by mwjames** [comment]
Some lessons learned from running the sandbox as live instance:

### ES related

- If you use the `ingest-plugin` and upgrade, avoid a "java.lang.IllegalArgumentException: plugin [ingest-attachment] is incompatible with version [6.2.4]; was designed for version [6.2.3]" by removing the plugin before doing the upgrade (remember to add it after the upgrade)

**Comment by mwjames** [comment]
> After the most recent update on sandbox I get the following when rebuilding data:
> PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /../w/extensions/SemanticMediaWiki/src/Elastic/QueryEngine/TermsLookup.php on line 504

The case for this is that I added support for `[[-Has subobject::+]]` but I didn't filter requests on something that looks like ` [[-Has number::+]]` (which only returns gibberish since `Has number` is not a resource aka page type) so by the next update this should be fixed. There will be an extra `p-0709` integration test to cover this scenario since we hadn't covered this before.

**Comment by mwjames** [comment]
> Yet, this PR does not provide any tests on its own and before the PR can be merged it requires some effort to reach a coverage that is necessary for a merge.

I'm going to merge this PR even though it does not yet fulfill the stated requirement for the unit coverage but #3165 has been created to ensure that coverage does happen before the 3.0 release.

@kghbln This should make the administration of the master branch a bit easier and since I'm off for the next eight weeks, no changes or merges will happen from my side during that time.

Something may change later on but it has been two months+ since we enabled the es-branch on the sandbox without major incidents.

**Pull request merged**
