### PR TITLE
Fix postgres failing on mw 1.28

### PR DESCRIPTION
**Pull request by paladox**
This PR is made in reference to: #

This PR addresses or contains:
- ...
- ...
- ...

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by mwjames** [comment]
The change doesn't test postgres with MW 1.28!

**Comment by paladox** [comment]
Oh woops, your right.

**Comment by paladox** [comment]
It seems that prefixing the tables in postgres in mediawiki is broken.

Per https://travis-ci.org/paladox/SemanticMediaWiki/builds/171479961

https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/c87e501aa908d55481d0538179d712a0695dbb44/tests/phpunit/Utils/MwDatabaseTableBuilder.php#L138

**Comment by mwjames** [comment]
The `doDropObsoleteIndicies` has a reference to `$this->connection->tableName( $tableName, 'raw' )` not sure this needs an update as well. This is such mess here (PS: not your fault!).

**Comment by mwjames** [comment]
Using #1923 as reference for testing.

**Pull request closed without merging**
