### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #1965 

This PR addresses or contains:
- Update to reflect usage with versions of MediaWiki compatible with this version of Semantic MediaWiki

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by kghbln** [comment]
I guess this should be it. Perfection is always possible but basically it should be fluffy now.

**Comment by kghbln** [comment]
@mwjames Oh, this was quick and dirty. :)

**Comment by mwjames** [comment]
> Oh, this was quick and dirty. :)

I canceled the TravisCI to avoid blocking other tests on changes that only affect documentation. Generally, when changing documentation `[skip ci]` can be used to avoid running the test suite.

https://docs.travis-ci.com/user/customizing-the-build#Skipping-a-build

**Comment by kghbln** [comment]
> I canceled the TravisCI to avoid blocking other tests on changes that only affect documentation. Generally, when changing documentation [skip ci] can be used to avoid running the test suite.

Thanks for the note! I have see that one can do this but thought that it may involve more voodoo.

**Comment by kghbln** [comment]
Refs https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/1752

**Pull request merged**
